### ISSUE TITLE
build-instructions(documentation): Missing dependency

### ISSUE THREAD

**Issue by jesperolsson-se** [schemaspy/schemaspy#1003]
When following the build instructions for generating the documentation, `make html` will complain about `sphinx_rtd_theme`.

## Expected Behavior
Following the build instructions should not result in any errors. 

## Current Behavior
`make html` fails with the following message:

```
Running Sphinx v3.2.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3.9/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
    exec(code, _globals)
  File "/home/jesper/development/schemaspy/docs/source/conf.py", line 22, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'

make: *** [Makefile:20: html] Error 2
```

## Possible Solution
Add a step for installing the dependency.

## Steps to Reproduce (for bugs)
1.  [Install Sphinx](https://www.sphinx-doc.org/en/master/usage/installation.html#linux)
2. `cd docs`
3. `make html`

## Context
N/A

## Your Environment
* Version used: 6.1.0
* Operating System: Linux (fedora)

**Comment by npetzall** [comment]
Is this in main or a branch that has missed to update the documentation?
