### ISSUE TITLE
CLI(flags): Long format not respected

### ISSUE THREAD

**Issue by jesperolsson-se** [schemaspy/schemaspy#1004]
The long format of `-dp`(`--driverPath`) and `-t` (`--database-type`) are not effective, even though they are listed in `-h`.

## Expected Behavior
All flag alternatives listed in `-h` should be valid and equivalent.

## Current Behavior
Executing SchemaSpy with `--driverPath` is treated as if `-dp` is missing. Same with `--database-type` vs. `-t`

## Context
* Full command including arguments how you run SchemaSpy:
```
java -jar schemaspy-6.1.0.jar --database-type pgsql11 --driverPath postgresql-42.5.4.jar -db postgres -host localhost -port 5432 -u postgres -p <pw> -o out
```

## Your Environment

* Version used: 6.1.0
* Operating System and version: Linux (fedora)

**Comment by Fryguy** [comment]
I saw the same problem but via the properties file, e.g `schemaspy.database-type=pgsql`

**Comment by npetzall** [comment]
`--database-type` isn't working

**Comment by npetzall** [comment]
We can re-assign it to me since I'm moving everything to JCommander and then it should work as expected.

**Comment by jesperolsson-se** [comment]
@npetzall
Please clarify. Does your argument not enter the system at all, or is there some logic in SchemaSpy that doesn't respect the CLI (e.g., just uses `config`)?

**Comment by npetzall** [comment]
It enters the system, but there are part that's still uses config. So it doesn't work as expected. That's why I can take over the issue and close it when I've completed the migration.

**Comment by jesperolsson-se** [comment]
Thank for the clarification! I'm fine with either option

**Comment by npetzall** [comment]
In think it's the getDbProperties that internally uses getDbType

**Comment by npetzall** [comment]
Everything has been moved to JCommander, and as such long formats reported by `-help` should work.
