### ISSUE TITLE
H2-2 databaseType

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#1012]
@marcelstoer Sorry to wake this up but I have a question regarding the 
```
selectSequencesSql=SELECT seqs.sequence_name, (seqs.base_value + seqs.increment) as start_value, seqs.increment FROM information_schema.sequences seqs WHERE seqs.sequence_schema = :schema
```

Specifically  `(seqs.base_value + seqs.increment) as start_value` when there is a start_value column.
https://h2database.com/html/systemtables.html#information_schema_sequences

It should be noted that there is a change between 1.x and 2.x in this regard. 1.x hade current_value as start_value - 1 and didn't store start_value at all. So there is sort of an issue in 1.x where it will give you next instead of start, unless the table i empty.

So the real question is do you want next_value or should we change to start_value?

**Comment by marcelstoer** [comment]
I had discussed this with a colleague before I raised PR #970. We weren't quite sure what the SchemaSpy semantics for "start value" is - given that the [SchemaSpy configuration for H2 1.x](https://github.com/schemaspy/schemaspy/blob/master/src/main/resources/org/schemaspy/types/h2.properties#L17) leads to "start" being dynamic (counter intuitive for me).

Personally I favor always pulling `start_value` straight from the database as-is if it has such a field. In theory this means that SchemaSpy can't give any guarantees as to what the "start value" it displays represents. However, I feel SchemaSpy should take the position of "we display whatever there is in the database" and leave the interpretation to the viewer.

**Comment by npetzall** [comment]
I think the start_value is important since there is a feature for rolling over/re-cycle.

So changing to start_value for 2.x.

But I'll add a feature for next_value it's included in SQL standard 2003 and when documenting a live database this might provide some insight.

I'm gonna double check i think `START WITH` is part of the same standards so that could be the semantics for start_value and we could also add that to the docs.

Thank you for your feedback @marcelstoer
