### ISSUE TITLE
Schemaspy 6.2.0: Failed to connect to database

### ISSUE THREAD

**Issue by Marius-Kazlauskas** [schemaspy/schemaspy#1099]
schemaspy-**6.1.0**.jar runs ok with schemaspy.properties:

schemaspy.t=pgsql
schemaspy.dp=postgresql-42.3.6.jar
schemaspy.host=localhost
schemaspy.port=5432
schemaspy.db=mydb
schemaspy.u=postgres
schemaspy.p=mypassword
schemaspy.o=Generated

but schemaspy-**6.2.0**.jar (with the same schemaspy.properties) fails with error:
`Failed to connect to database URL [jdbc:postgresql://localhost:5432/mydb] The server requested password-based authentication, but no password was provided by plugin null`

More details:
PostgreSQL version: 15
postgresql.conf: password_encryption = md5, listen_addresses = '*'
pg_hba.conf: METHOD is md5

Any ideas?

**Comment by npetzall** [comment]
A w has snuck it's self into 6.2.0, so `schemsspy.p` needs to be `schemaspy.pw`

**Comment by npetzall** [comment]
I'll create a patch release.

**Comment by npetzall** [comment]
We'll retain the `pw` and just add `p`, so if any one changes to `pw` they don't have to switch back for 6.2.1

**Comment by Marius-Kazlauskas** [comment]
Thanks, it works

**Comment by npetzall** [comment]
@Marius-Kazlauskas 6.2.1 also contains a fix för pgsql11 which is the dbType to use för PostgreSQL 11 and never.
