### ISSUE TITLE
Ignored port definition in properties file

### ISSUE THREAD

**Issue by filipemanuelofs** [schemaspy/schemaspy#111]
Trying to generate diagram from database which port is different from default 5432, but doesn't matter, the error that I get in console is from port 5432:

**Console**
> $ java -jar schemaspy6.jar -configFile schemaspy.properties

> 12:19:32.315 WARNING: Main.main - Connection Failure
> org.schemaspy.model.ConnectionFailure: org.postgresql.util.PSQLException: Connection to database:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**schemaspy.properties**
> schemaspy.t=pgsql
> schemaspy.dp=/home/schemaspy/postgresql-42.0.0.jar
> schemaspy.host=host
> schemaspy.port=5444
> schemaspy.db=database
> schemaspy.u=user
> schemaspy.p=root
> schemaspy.o=/home/schemaspy/generated

**Comment by npetzall** [comment]
@filipemanuelofs check #109

**Comment by npetzall** [comment]
connectionSpec=jdbc:postgresql://<host>/<db>
host=hostname[:port] (possibly just localhost)
db=database name

Port should be added to host. Such as
schemaspy.host=host:port

**Comment by filipemanuelofs** [comment]
It works, thanks.
