### ISSUE TITLE
Postgres 11 Long Routine Names Cause Crash

### ISSUE THREAD

**Issue by HuanRuan** [schemaspy/schemaspy#1115]
## Expected Behavior
With a Postgres 14.6 database that has a routine with a long name, running schemaspy with the `schemaspy.t=pgsql11` option should successfully retrieve the routine's information.

## Current Behavior
It crashes with this stack trace:
```
Caused by: java.lang.NullPointerException
  at org.schemaspy.util.CaseInsensitiveMap.put(CaseInsensitiveMap.java:59)
  at org.schemaspy.util.CaseInsensitiveMap.put(CaseInsensitiveMap.java:35)
  at org.schemaspy.input.dbms.service.RoutineService.initRoutines(RoutineService.java:95)
  at org.schemaspy.input.dbms.service.RoutineService.gatherRoutines(RoutineService.java:46)
  at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:132)
  at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:269)
  at org.schemaspy.SchemaAnalyzer.analyzeMultipleSchemas(SchemaAnalyzer.java:185)
  at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:126)
  at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
  at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
  at org.schemaspy.Main.main(Main.java:55)
```

## Possible Solution
It appears that it's broken by this change,

https://github.com/schemaspy/schemaspy/blob/96cfe166b5e578d4479070fce62632529174a023/src/main/resources/org/schemaspy/types/pgsql11.properties#L43

Usually, `r.specific_name` is made up of `pp.proname || '_' || pp.oid`. However, when that expression exceeds Postgres's max length for SQL identifiers, i.e. 63, `pp.proname` is truncated to ensure `r.specific_name` meets the maximum length. When the truncation occurs, the above SQL returns NULL `routine_name`, which leads to the above NPE.

A possible solution is to revert it to its previous implementation,
```sql
LEFT JOIN pg_proc p ON ns.oid = p.pronamespace
    AND r.routine_name = p.proname
```

Perhaps, it's even better to not mix up `information_schema` with `pg_catalog` tables and views. See https://www.postgresql.org/docs/current/infoschema-routines.html,
> specific_name sql_identifier
> The “specific name” of the function. This is a name that uniquely identifies the function in the schema, even if the real name of the function is overloaded. The format of the specific name is not defined, it should only be used to compare it to other instances of specific routine names.

## Steps to Reproduce (for bugs)
1. Run this SQL to create a function in a Postgres 14.6 database
  ```sql
CREATE FUNCTION loooooooooooooooooooooooooooooooong_function_with_63_characters()
  RETURNS integer
AS $$
  SELECT 1
$$
LANGUAGE SQL;
  ```
2. Run schemaspy with the `schemaspy.t=pgsql11` option.

## Your Environment
* Version used: 6.2.2
* Operating System and version: Windows 10
* Java version: AdoptJDK/jdk-17.0.6+10
* Postgres version: 14.6

**Comment by npetzall** [comment]
It was introduced to handle overloading
>routine_name sql_identifier
Name of the function (might be duplicated in case of overloading)

Reverting will lead to all combinations of original and overloaded
original + original paramters
original + overloaded parameters
overloaded + original paramters
overloaded + overloaded parameters

And that will only grow if there are multipl overloads.

But as we now see there is a problem. I think you are correct in that we shouldn't mix information_schema and pg_catalog.

Two options exists, modify the code and require specific_name for all routines but treat is opaque and just use it for mapping parameters to routines, and use a "toString" on routine to get a name that includes parameters, just to distinguish in the overloaded cases. This will have an effect on all current dbms that has routines. It's probably the correct implementation.

The second option is to only use pg_catalog and just answere the questions that schemaspy expects to be answered.

> selectRoutinesSql=
Fetch routines, expected columns:
routine_name, routine_type, dtd_identifier, routine_body, routine_definition,sql_data_access, security_type, is_deterministic, routine_comment

> selectRoutineParametersSql=
Fetch parameters for routines, expected columns:
specific_name, parameter_name, dtd_identifier, parameter_mode

Updating the query is probably going to be faster for now a work around.
It just expects that `selectRoutinesSql.routine_name` = `selectRoutineParametersSql.specific_name`

Sadly it's late I have to sleep before work i've gotten this far, which isn't much

selectRoutineSql
```
select p.proname || '(' || pg_get_function_arguments(p.oid) || ')' as routine_name 
from pg_proc p
left join pg_namespace n ON n.oid = p.pronamespace
where n.nspname = :schema
```

selectRoutineParametersSql
```
select 
p.proname || '(' || pg_get_function_arguments(p.oid) || ')' as routine_name,
unnest(p.proargnames) as parameter_name,
format_type(unnest(p.proargtypes), null) as dtd_identifier
from pg_proc p
left join pg_namespace n ON n.oid = p.pronamespace
where n.nspname = :schema
```

**Comment by HuanRuan** [comment]
Thanks @npetzall for the quick response.

**Comment by pyrocks** [comment]
>It just expects that selectRoutinesSql.routine_name = selectRoutineParametersSql.specific_name

this indeed causes issues for me with the updated queries:
```
Gathering schema details........................................................WARN  - Failed to retrieve stored procedure/function details using SQL 'select p.proname || '(' || pg_get_function_arguments(p.oid) || ')' as routine_name, unnest(p.proargnames) as parameter_name, format_type(unnest(p.proargtypes), null) as dtd_identifier from pg_proc p left join pg_namespace n ON n.oid = p.pronamespace where n.nspname = :schema'
The column name specific_name was not found in this ResultSet.
```

so I just replaced `as routine_name` with `as specific_name`

if you want to merge the fix PR with `routine_name` - the code which handles the resultset needs to be modified as well.

**Comment by npetzall** [comment]
@pyrocks I'll lock into that I've created a PR but haven't merged yet i think so I'll double check.

**Comment by npetzall** [comment]
@HuanRuan @pyrocks 
I found some additional issues with queries I've update the previous answer and the changes going into the PR can be found at https://github.com/schemaspy/schemaspy/blob/1e9c7b4e4a4eeb05eda261a867807225a1b1b14e/src/main/resources/org/schemaspy/types/pgsql11.properties

If you have the time to double check that would be super.

**Comment by HuanRuan** [comment]
Thanks, @npetzall. I will test it and let you know.

**Comment by HuanRuan** [comment]
Hi @npetzall, my testing went well. It works as expected, thank you.

One minor note, you use `oidvectortypes(pg_proc.proargtypes)` to get the function argument types without names, e.g. `date, text`. `pg_get_function_arguments(pg_proc.oid)` returns both types and names, e.g. `dob date, name text`. I don't know if the latter helps or not, as I don't know how you render non-Postgres databases.

**Comment by pyrocks** [comment]
Seems to be working correctly for me

**Comment by npetzall** [comment]
@HuanRuan Yeah, I did the pg_get_function_arguments first, but the lines became very long and the "original" was `oidvectortypes(pg_proc.proargtypes)` but I'll have a seconds look. I just reverted since it got the tests passing. But if it looks better I'll change and just update the test.
