### ISSUE TITLE
Decimal type not showing the number of decimals

### ISSUE THREAD

**Issue by cheoAlejo** [schemaspy/schemaspy#112]
When the field is type "DECIMAL (M, D)", the decimal part is not showing:

![2017-06-22 11_59_10-cnp database](https://user-images.githubusercontent.com/10518807/27446214-63155492-5742-11e7-8860-034809c4f36a.png)

In this example the type of the **latitud** field is `DECIMAL(7, 6)`, 7 digits maximum and 6 decimals.

**Comment by npetzall** [comment]
@cheoAlejo
Which database?

**Comment by cheoAlejo** [comment]
I forgot to mention, it's MySQL 5.6

**Comment by wkasa** [comment]
i've checked this also on MSSQL and problem was the same. Now should be good.

**Comment by cheoAlejo** [comment]
Excellent !

**Comment by npetzall** [comment]
@cheoAlejo You can download a snapshot at [snapshot](]https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1.jar) it should contain the fix.

**Comment by cheoAlejo** [comment]
Wow thanks @npetzall .

**Comment by cheoAlejo** [comment]
mm, it now throws this error:

![2017-06-28 17_40_17- 1_2 mingw64__d_delfineco_gitlab-repos_db-design_modelo-cnp](https://user-images.githubusercontent.com/10518807/27663795-a905849a-5c29-11e7-8aa2-a7efca1292e8.png)

This is the command i'm using:
```
java -jar schemaspy-6.0.0-rc1.jar -dp mysql-connector.jar -gv graphviz -configFile config.config -db cnp -o data-dict/
```

The name of the mysql database is **cnp**, and this is my config file:

![2017-06-28 17_44_29-clipboard](https://user-images.githubusercontent.com/10518807/27663858-f264cf24-5c29-11e7-8ff3-02a1e76a2214.png)

**Versions of the components:**

- schemaspy-6.0.0-rc1
- graphviz-2.38
- mysql-connector-java-5.1.42-bin

After rolling back to my previous .jar it works again.

**Comment by npetzall** [comment]
@cheoAlejo probably has to do with the commandline parsing. Try adding `-s cnp` i believe mysql treats schema and database as the same thing.

**Comment by cheoAlejo** [comment]
Yes, it works, and the decimals show perfect too.

I had to write twice the name of database:
```
java -jar schemaspy-6.0.0-rc1.jar -dp mysql-connector.jar -gv graphviz -configFile config.config -db cnp -s cnp -o data-dict/
```

**Comment by npetzall** [comment]
Read the docs, it should be optional in some cases. But not this case, but since it worked in release rc1 but not snapshot. I think it needs a new issue for investigation.

**Comment by cheoAlejo** [comment]
Ok, thanks for all the help.

**Comment by npetzall** [comment]
Your welcome, and thank you for helping us improve schemaspy

**Comment by wkasa** [comment]
@cheoAlejo If everything is correct you can close the issue. And as @npetzall said, thanks for helping improve schemaspy!  :)
