### ISSUE TITLE
drivers_inc/remotecontent may be JAR File now.

### ISSUE THREAD

**Issue by maeda-d** [schemaspy/schemaspy#1149]
drivers_inc/remotecontent may be JAR File in schemaspy:snapshot.
```
~/snap/1b6d1ad9aa4cb283aa4c848d78401ec33487701416ab2a94f56a0b8da39b5eb6
$file drivers_inc/remotecontent
drivers_inc/remotecontent: Java archive data (JAR)
```

**Comment by npetzall** [comment]
Hi @maeda-d thanks for noticing, and reporting.
I checked and it seems to be a recent issue that has only affected the snapshot tag.

I'll look into it.
