### ISSUE TITLE
Bundle all files from external libraries into the generated schema documentation

### ISSUE THREAD

**Issue by jensberke** [schemaspy/schemaspy#118]
Hi, first of all thanks for continuing SchemaSpy.

Currently some libraries like jQuery and some Bootstrap files are already bundled with the schema files created by SchemaSpy and therefore don't need to be downloaded by the browser from the libraries' web sites when you open a schema documentation.

However, several other external libraries (from cloudflare.com, datatables.net and so on) are not. 

Would it be possible to bundle **all** external libraries into the generated schema documentation so that one could fully view it offline?

**Comment by npetzall** [comment]
Duplicate of #56?

**Comment by jensberke** [comment]
Oh, yes, sorry.
