### ISSUE TITLE
[Regression 6.2.2 -> 6.2.3] Broken link to PostgreSQL function w/ custom type arg

### ISSUE THREAD

**Issue by albrechtd** [schemaspy/schemaspy#1200]
## Current Behavior

Schemaspy v. 6.2.3 produces broken links to PostgreSQL functions with custom type args.  This used to work with Schemaspy 6.2.2 (and before).

## Possible Solution

Maybe this issue is linked to the fix of #1115.

## Steps to Reproduce

Please see the attached ZIP file containing a minimalistic PostgreSQL schema:
1. unpack [issue_demo.zip](https://github.com/schemaspy/schemaspy/files/11837296/issue_demo.zip) (on a Linux box)
2. copy `schemaspy-6.2.2.jar` and `schemaspy-6.2.3.jar` into the folder `issue_demo`, or set proper paths in `commands.sh`
3. say `cd issue_demo && ./commands.sh` (note: tries to install the demo SQL schema as user `postgres` by calling `sudo`)

Result:
* open the output in sub-folder `test_622` (version 6.2.2), select _Routines_ and click on _demofn_ -> ok
* open the output in sub-folder `test_623` (version 6.2.3), select _Routines_ and click on _demofn_ -> file `demofn_arg1_text__arg2_mytype_D_17666397.html` does not exist; the proper name would be   `demofn_arg1_text__arg2_mytype_D_2c10faf9.html`

Note that afaict this error does **not** occur with functions without any custom type args (e.g. _otherfn_).

## Context
* Database type (e.g. MySQL): PostgreSQL 15 (official 15.3 DEB packages from postgresql.org)
* Full command including arguments how you run SchemaSpy: see `commands.sh`

## Your Environment
* Version used: 6.2.2, 6.2.3
* Operating System and version (e.g. Windows 10): Debian Bookworm x86/64
* Java version: openjdk-17-jre 17.0.7+7-1~deb12u1

**Comment by npetzall** [comment]
Suspect that mustasch might do some escaping on the name and that we need additional curly braces in the routines template.

So that there are different names going into the FilenameGenerator.

**Comment by npetzall** [comment]
`demofn(arg1 text, arg2 mytype DEFAULT 'one'::mytype)` is rendered with mustach escpaing as `demofn(arg1 text, arg2 mytype DEFAULT &#39;one&#39;::mytype)` which then results in a filename `demofn_arg1_text__arg2_mytype_D_17666397`.

Having mustach render the raw value to the toFileName function results in a filename `demofn_arg1_text__arg2_mytype_D_2c10faf9`.

So I think I've solved it. I'm gonna double check the usage of toFileName and see that we provide raw value everytime.
