### ISSUE TITLE
dot output

### ISSUE THREAD

**Issue by jlee-made** [schemaspy/schemaspy#121]
I would find it useful to be able to use schemaspy to generate .dot format output for further processing outside of schemaspy.

There are tools and libraries available to process dot files, and no matter how featureful a tool like schemaspy is, I tend to find there is always another ad-hoc automated transformation I want to do that isn't supported but could be achieved with a Python script or similar.

**Comment by npetzall** [comment]
@jlee-made I'm not sure, but I think in the diagrams sub-folder of the output folder, you'll find the the .dot files.

**Comment by npetzall** [comment]
@jlee-made you'll find the .dot files in [ouput]/diagrams(/orphans,/summary)
