### ISSUE TITLE
Informix error when processing routines

### ISSUE THREAD

**Issue by philocritus** [schemaspy/schemaspy#1220]
## Expected Behavior
Schema diagrams will be generated.

## Current Behavior
When running schemaspy on a informix DB I get an NullPointerException when running the routine service.
I ran with debug and got the query which runs fine on dbaccess.
Also tried to manipulate the query by setting the property selectRoutinesSql but it seems to be ignored.

`INFO  - Gathering schema details
Gathering schema details...DEBUG - select t.tabname as table_name, c.constrname as constraint_name, k.checktext as text from sysconstraints c,syschecks k,systables t where c.constrid = k.constrid and c.tabid = t.tabid and c.constrtype = 'C' and k.type = 'T' order by k.seqno []
DEBUG - SELECT p.procname || '(' || ifx_param_types(p.procid) || ')' AS routine_name, case p.isproc when "f" then "Function" when "t" then "Procedure" end as routine_type, ifx_ret_types(p.procid) as dtd_identifier, l.langname as routine_body, b.data as routine_definition, b.seqno, 'N/A' as sql_data_access, case LOWER (p.mode) when "d" then "DBA" when "o" then "Owner" when "p" then "Protected" when "r" then "Restricted" when "t" then "trigger" end as security_type, p.variant as is_deterministic, "N/A" as routine_comment from sysprocedures p join sysroutinelangs l on p.langid = l.langid join sysprocbody b on p.procid = b.procid and b.datakey = 'T' order by p.procid, b.seqno []
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NullPointerException
        at org.schemaspy.util.CaseInsensitiveMap.merge(CaseInsensitiveMap.java:71)
        at org.schemaspy.util.CaseInsensitiveMap.merge(CaseInsensitiveMap.java:35)
        at org.schemaspy.input.dbms.service.RoutineService.initRoutines(RoutineService.java:91)
        at org.schemaspy.input.dbms.service.RoutineService.gatherRoutines(RoutineService.java:46)
        at org.schemaspy.input.dbms.service.DatabaseService.gatherSchemaDetails(DatabaseService.java:132)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:270)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:135)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:109)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:98)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
`

## Possible Solution
Fixing a possible bug or disabling routine processing

## Steps to Reproduce (for bugs)
Run on a informix DB with routines.
Probably a specific routine is the culprit.

## Context
* Database type (e.g. MySQL): Informix 11.50.FC9W3
* Database driver version (is you use a special one): jdbc-4.50.8.jar
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:
`java -jar lib/schemaspy-6.2.3.jar -t informix -host apaxsys004:15030 -server adx_dev_tcp -dp lib/jdbc-4.50.8.jar -db scg -o $OUTDIR -u XXXX -p XXXX -noschema -noads -meta meta/leaseDbAdm.xml`

## Your Environment
* Version used: SchemaSpy 6.2.3
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10): AIX 7.1
* Java version: 1.8.0

**Comment by npetzall** [comment]
I'm just eyeballing from my phone but it seems that the routine_name would be null.

I'm not super knowledgeable about Informix but it does `SELECT p.procname || '(' || ifx_param_types(p.procid) || ')' AS routine_name`

Which contains concatenation so it should never be null.

If you manually run
```
SELECT p.procname || '(' || ifx_param_types(p.procid) || ')' AS routine_name, 
case p.isproc when "f" then "Function" when "t" then "Procedure" end as routine_type, 
ifx_ret_types(p.procid) as dtd_identifier, 
l.langname as routine_body, 
b.data as routine_definition, b.seqno, 'N/A' as sql_data_access, case LOWER (p.mode) when "d" then "DBA" when "o" then "Owner" when "p" then "Protected" when "r" then "Restricted" when "t" then "trigger" end as security_type, 
p.variant as is_deterministic, "N/A" as routine_comment 
from sysprocedures p 
join sysroutinelangs l on p.langid = l.langid 
join sysprocbody b on p.procid = b.procid and b.datakey = 'T' 
order by p.procid, b.seqno
```

You don't get any rows with an empty `routine_name` column?

Wonder if it could be a strange join or anything related to access, if the queries are run with different accounts.

Since it seems that the query executes correctly but there is an issue with the returned data.

**Comment by philocritus** [comment]
I had already ran the query manually and it works fine. 
I has no procedure with procname or procid = NULL.
I'm currently reviewing the procedures to see if anything gives me a clue to which one might be the culprit.
I'm also going to try a different DB on the same server.
I can also try to drop all the procedures and recreate them by sets of 50 at a time to narrow it down to the offending code.

**Comment by npetzall** [comment]
Could you create procedure that has the issue and post here so that I can have a look at how we can handle it. I assume that it's supported by informix so we should handle it I SchemaSpy.

**Comment by philocritus** [comment]
I can create two situations:
In this case, table contrato does not exist. This makes ifx_param_types return null
```
create procedure proctest1(oTipoProposta like contrato.ctotipo, aProposta like contrato.ctonum )
        returning int, char(50), char(255), char(512) ;

        return 0, " ", "", "";

end procedure ;
```
In this case its a combination of 2 things:
* user "usr does not exist on the databse
* there's a variable defined with like to another database

```
create procedure "usr".proctest2( aTabela char(18), aDescricao integer)
        define oModulo     like dbadm:tabela.modulo;

        let oModulo = "leaseDBAdm";
end procedure;
```

**Comment by npetzall** [comment]
Nice, thanks
