### ISSUE TITLE
Problem with "carriage return" in Markdown Syntax

### ISSUE THREAD

**Issue by TrapperBug** [schemaspy/schemaspy#124]
Hi,

I am using schemaspy-6.0.0-rc1.jar to document an Oracle Database Schema and
used "carriage return" (13) for linebreaks in then column comments.

But in the html output the comments are without breaks.

How must the comments in an Oracle Database look like to get breaks?

**Comment by npetzall** [comment]
Should carriage return work. Sounds like you really want the line feed 10.

But then again different systems uses different handling.

Schemaspy has markdown handling. So a space, space, linebreaks might work.

**Comment by TrapperBug** [comment]
I used the "Markdown" documentation from the "old" projekt https://sourceforge.net/p/schemaspy/wiki/markdown_syntax/.

In the examples "A carriage return makes a line break". 

But CHR(13) which is "carriage return" is not working. There are not linebreaks in the html-Output.

**Comment by npetzall** [comment]
How did you enter the comment? Give an example and I might have time to look at it in 12hrs.

**Comment by TrapperBug** [comment]
I am using PL/SQL to generate comments based on a data lineage. I stripped down an example:

DECLARE
  v_comment VARCHAR2(4000):='''A carriage return'||chr(13)||'makes a linebreake'''  ;
BEGIN
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN TEST_SCHEMA.TEST_TABLE.TEST_COLUMN IS '||v_comment;
END;

Checking encoding by:

select DUMP(COMMENTS) from ALL_COL_COMMENTS where column_name='TEST_COLUMN' and table_name='TEST_TABLE';

I can see that CHR(13) ist correctly in the columns comment.

Thanks in advance

**Comment by npetzall** [comment]
If your able could you try `chr(13)||chr(10)`

I haven't had time yet. But I believe it's sloppy documentation. Carriage return just return to beginning of line (type writer) what you want is 10 which is line feed. Move to next row.

**Comment by npetzall** [comment]
Did some digging add two spaces after CR LF to get html <br />

**Comment by npetzall** [comment]
Tested now and following works.
```
SQL> DECLARE
  2  v_comment VARCHAR2(4000):='''Two spaces and a linefeed  '||CHR(10)||'makes a br''';
  3  BEGIN
  4  EXECUTE IMMEDIATE 'COMMENT ON COLUMN orait.test.name IS '||v_comment;
  5  END;
  6  /
```

**Comment by TrapperBug** [comment]
Hi,

thanks a lot. It's working now.

Regards
Frank

**Comment by rafalkasa** [comment]
Thank you @npetzall for your help as usually you find working solution :-)
