### ISSUE TITLE
Support Type4 DB2z Database Driver

### ISSUE THREAD

**Issue by dhermanns** [schemaspy/schemaspy#126]
Hi!

I managed to do this by modifying your db2zos.properties File to simply extends db2net:

`# details in db2net.properties:
extends=db2net`

In db2net.properties I had to change the driver package name to:

`# use the 'net' driver (Type 4) instead of the default 'app' driver
driver=com.ibm.db2.jcc.DB2Driver`

Maybe you could provide a db2zosnet.properties with these settings?

**Comment by npetzall** [comment]
Either create a code block with the complete properties content or create a pull request so we can add it.

**Comment by dhermanns** [comment]
No problem:

Here you go:
https://github.com/schemaspy/schemaspy/pull/127

**Comment by rafalkasa** [comment]
This issue was fixed in PR #127

**Comment by dhermanns** [comment]
Is there a release date for the rc2 already?

**Comment by dhermanns** [comment]
Sorry - for bumping this. Any update?

**Comment by rafalkasa** [comment]
Hi @dhermanns 

Sorry for not answer for your first question...

During the summer time project was a littler on hold. We come back from vacations and we will continue the support and improve the project. I can't specify the day for release rc2 but I would like to have it to the end of the month.

**Comment by dhermanns** [comment]
Sounds great - thx!
