### ISSUE TITLE
Orphans diagram has all nodes on same rank creating a long list

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#1272]
This can either be solved with setting `packmode="graph"` or changing the layout engine to neato, osage or fdp.

Changing the layout engine is a bigger thing, it will actually only work with Orphans. But using `packmode="graph"` will also make the relationship diagrams look better, since when a schema has lots of orphans they are put on the same rank, creating a "row"/"coulm" which will be of all the nodes.

Adding packmode will move them to available space instead. I strange thing is that "ratio" in the graph is misspelled if this is corrected it seems like `packmode` gets disabled.

I'll add example images later and we can discuss adding `packmode="graph"` and removing `ration`.

I sort of have the feeling that we have had packmode and removed it. So I'll dig into the history to double check if it was removed for any good reason.

**Comment by npetzall** [comment]
## Orphans
Dot with `packmode="graph"`
<img width="668" alt="image" src="https://github.com/schemaspy/schemaspy/assets/4175123/85451dfb-4c3e-491b-907b-b438d1d01a0a">

Dot without `packmode`
<img width="668" alt="image" src="https://github.com/schemaspy/schemaspy/assets/4175123/19827a63-b46c-4f36-8951-1eef8e8208b5">

Osage
<img width="704" alt="image" src="https://github.com/schemaspy/schemaspy/assets/4175123/5e1c415d-fe0c-49a3-b585-48f1751b2c19">


## Relationships Implied

Dot with `packmode="graph"`
<img width="704" alt="image" src="https://github.com/schemaspy/schemaspy/assets/4175123/c02ec2a3-d994-4df9-bc21-594d3d386034">

Dot without `packmode`
<img width="704" alt="image" src="https://github.com/schemaspy/schemaspy/assets/4175123/4e828e01-ede2-4864-aefc-5d45d2eb1c15">

Osage:
<img width="704" alt="image" src="https://github.com/schemaspy/schemaspy/assets/4175123/fd90324a-a3d3-4ed5-9551-ff3a88472522">

**Comment by npetzall** [comment]
@jesperolsson-se any objections to adding `packmode="graph"`?

**Comment by jesperolsson-se** [comment]
> @jesperolsson-se any objections to adding `packmode="graph"`?

Not for these examples. Please be sure to check graphs with more complicated relationships.

**Comment by npetzall** [comment]
@jesperolsson-se we sort of need to maybe have a set of data that we can test against. 

Since your comment is valid but un-verifiable.

What exactly is more complicated is it depth or additional entanglement(realising I'm not sure what that means).

Currently we can work with `mediawiki only implied`, with meta connection. What more can we create/include?

I propose that we sync this with examples.

**Comment by npetzall** [comment]
We'll try it out, we can always revert if we find issues.
