### ISSUE TITLE
Configuration problem for TeraData (schema)

### ISSUE THREAD

**Issue by mocista** [schemaspy/schemaspy#1278]
I am using schemaspy towards a **TeraData** system.

In the config File I have 

schemaspy.s=[my_schema]

When I am running the programm I get an error:

INFO  - The following profiles are active: default
INFO  - Found configuration file: schemaspy.properties
INFO  - Started Main in 21.074 seconds (JVM running for 23.313)
INFO  - Starting schema analysis
ERROR - *** Required parameter 's' (?????) was not specified.  It is required for this database type. ***
INFO  - Missing required connection parameters for '-t teradata'
INFO  -    Standard (-t teradata)
INFO  -       -db               database name
INFO  -       -s                ?????
INFO  -       -port             ?????

Why do I get 

ERROR - *** Required parameter 's' (?????) was **not specified**.  It is required for this database type. ***

?

I have very well specified schemaspy.s in the configuration file!

## Expected Behavior
should work fine, the config file is correct.

## Current Behavior
doesn't work and the error message is nonsensical

## Your Environment

* Version used: schemaspy-6.2.4.jar
* Operating System and version (e.g. Windows 10): Windows 10 Enterprise
* Java version: 1.8

**Comment by npetzall** [comment]
Do you still get the error if you specify `-s` on the Commandline.

Trying to figure out if the messages is correct.

Is that the complete config file? 

Need to figure out if it might be overwritten by something. Need the details so I can reproduce and fix the issue.

But I'll just give it a go, because I'm not sure any other database typ actually uses s as an argument so this might be an issue introduced when I did the complete migration to jcommander.

**Comment by npetzall** [comment]
Seems to be a bug introduced during JCommander migration.

Quickest workaround would be to create a file in the same folder as SchemaSpy named myteradata.properties with the following content
```
#
# see http://schemaspy.org/dbtypes.html
# for configuration / customization details
#
dbms=Teradata
description=Standard

# Teradata typically requires *many* more configuration options
# Put those in a specialized .properties file and point to them with -connprops
# Example of connectionSpec: jdbc:teradata://TD.DB.ROOT1.NET/DATABASE=DB1,DBS_PORT=1025
connectionSpec=jdbc:teradata://<host>/DATABASE=<db>,DBS_PORT=<port>
db=database
host=host name
port=dbs port

driver=com.teradata.jdbc.TeraDriver
```

Then use `-host`, `-db` and `-port` togethere with the required parameter `-s` where `-s` and `-db` probably should be the same value.

**Comment by npetzall** [comment]
To avoid creating over complicated arguments handling. The above workaround will be the fix. This will be counted as a breaking change within 7.0.0 release.

**Comment by mocista** [comment]
Hi

I have made it work independently (similarly). Thanks anyway!
