### ISSUE TITLE
Support Oracle Service Names

### ISSUE THREAD

**Issue by elygre** [schemaspy/schemaspy#128]
When connecting to Oracle, you may choose to use a SID or a Service Name. Service names are the future (and have been for the last many years), but are not supported by schemaspy.

https://klauer.wordpress.com/2011/12/29/schemaspy-with-oracle-exadata-service-names/ shows how to fix this.

**Comment by elygre** [comment]
I was going to give this a small shot, but it seems that the packaging has changed; at least "mvnw install" created a jar file very different from the one I downloaded. So, no go.

But the change is still there, in my cloned repo, in case someone wants to try it out.

**Comment by npetzall** [comment]
The download from release page is the release so, if you want identical except your changes. You need to checkout the  RC tag from git.

In the readme.md there is a link to a snapshot Rc which I updated with each commit

**Comment by npetzall** [comment]
So [orathin.properties](https://github.com/schemaspy/schemaspy/blob/master/src/main/resources/org/schemaspy/types/orathin.properties)

But with `/` instead of `:` before db?

**Comment by npetzall** [comment]
@rafalkasa improve the documentation on dbtypes that one can actually create a file in the same directory and reference it, that it doesn't need to be bundled. But I think we should bundle this.
