### ISSUE TITLE
schemespy is not creating folder

### ISSUE THREAD

**Issue by Nurlan199206** [schemaspy/schemaspy#1291]
currently i'm testing schemaspy

on PSQL 15 it's creating folder with  generated report

on PSQL 11 that's not working.

```
select version();
                                                              version
-----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.14 (Ubuntu 11.14-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
(1 row)
```

i'm running with command.

```
#!/bin/bash
java -jar schemaspy-6.2.4.jar -db $DATABASE -s public -u $USER -p $PASSWORD -host $HOST -port $PORT -debug -t $DB_TYPE -vizjs -o $OUTPUT -dp /app/postgresql-42.5.4.jar
```

`docker run -e DATABASE=market -e SCHEME=public -e USER=admin_core_service -e PASSWORD=pwd -e HOST=10.204.11.139 -e PORT=5532 -e DB_TYPE=pgsql -e OUTPUT=/mnt/c/Users/Nurlan/Documents/admin-core -e DB_DRIVER=postgresql-42.5.4.jar db:v1`

output of result script:

```
DEBUG - Writing table page -> accounting
.DEBUG - Writing details of accounting_old_090623
DEBUG - Writing table page -> accounting_old_090623
(5sec)
Wrote relationship details of 35 tables/views to directory '/mnt/c/Users/Nurlan/Documents/admin-core' in 14 seconds.
View the results by opening /mnt/c/Users/Nurlan/Documents/admin-core/index.html
INFO  - Wrote table details in 5 seconds
INFO  - Wrote relationship details of 35 tables/views to directory '/mnt/c/Users/Nurlan/Documents/admin-core' in 14 seconds.
INFO  - View the results by opening /mnt/c/Users/Nurlan/Documents/admin-core/index.html
```

**Comment by Nurlan199206** [comment]
i'm sorry, it's my fail

forgot mount folder.

`docker run -v /mnt/c/Users/Nurlan/Documents/delivery:/tmp/delivery -e DATABASE=delivery_service -e SCHEME=public -e USER=ds_user -e PASSWORD=ztnhkFbKPQSEx4dHBghF -e HOST=10.204.11.139 -e PORT=5532 -e DB_TYPE=pgsql11 -e OUTPUT=/tmp/delivery -e DB_DRIVER=postgresql-42.5.4.jar db:v1`

**Comment by npetzall** [comment]
Are you doing exactly the same thing with PSQL 15 and 11?

Since your using your own Docker image I can't really speak regarding its functionality. But from the Docker command your not doing any host mounting so the files will be left in the execution layer of the container.
