### ISSUE TITLE
Wrong queries for Postgres

### ISSUE THREAD

**Issue by pressing-buttons** [schemaspy/schemaspy#1312]
When using SchemaSpy against a Postgres database, the queries to retrieve functions/procedures and the query to retrieve the database comments are no longer working with modern Postgres versions. 

I was able to fix this using a custom DatabaseType using the following two queries.

The `selectRoutinesSql` should be:

    select r.routine_name||'('||pg_get_function_arguments(p.oid)||')' as routine_name, 
               case p.prokind 
                when 'a' then 'AGGREGATE' 
                when 'p' then 'PROCEDURE' 
                else 'FUNCTION' 
           end as routine_type, 
           case when p.proretset then 'SETOF ' else '' end || case when r.data_type = 'USER-DEFINED' then r.type_udt_name else r.data_type end as dtd_identifier, 
           r.external_language as routine_body, 
           r.routine_definition, 
           r.sql_data_access, 
           r.security_type, 
           r.is_deterministic, 
           d.description as routine_comment 
    from information_schema.routines r 
      left join pg_namespace ns on r.routine_schema = ns.nspname 
      left join pg_proc p on ns.oid = p.pronamespace and r.routine_name = p.proname 
      left join pg_description d on d.objoid = p.oid 
    where r.routine_schema = :schema

The `selectCatalogsSql` should be: 

    SELECT datname AS catalog_name, 
                pg_catalog.shobj_description(oid, 'pg_database') AS catalog_comment 
    FROM pg_catalog.pg_database 
    WHERE datname = :catalog

Note the use of `shobj_description()` which is used for "shared objects" (like a database) rather than `obj_description()` which only works for database level objects.

**Comment by npetzall** [comment]
Which `-t` argument are you using? Need to figure out if we need to add an additional.

Also from which version

I think we have `pgsql` for up to version 10 and then it's `pgsl11` and it should work up to 15 I thinks so.

So do we need to add a pgsql16 which is for 16 and newer?

**Comment by pressing-buttons** [comment]
Oops, I missed the new `pgsql11` type. Using that, things are fine (using Postgres 16). 
Sorry for the noise

**Comment by npetzall** [comment]
No worries, we really appreciate that you raised an issue. Worst things for us, since we can't keep track of all databases, is if user don't create issues at all.

So you made an effort/invested time and we appreciate that.
