### ISSUE TITLE
Type of diagramming symbols used by Schemaspy

### ISSUE THREAD

**Issue by pplll** [schemaspy/schemaspy#135]
What type of diagramming symbols does Schemaspy use to show table relationships? I am a non-database developer, a writer, with limited database experience and am developing a database design document for a project that I am working on.

Thanks!

**Comment by npetzall** [comment]
I'm gonna be honest, I'm not a db administrator/designer. I'm actually not that knowledgeable about the graphing part of schemaspy. But most Entity Relationship Diagram has symbols for "one to one", "one to many", "many to many" and "many to one".

[examples](https://www.smartdraw.com/entity-relationship-diagram/#ERDSymbols)

From your question it sounds like you want to create a ERD . Schemaspy is a reverse engineering tool. If you Google you'll find plenty of tools. Like draw.io or plantUML.

**Comment by pplll** [comment]
Thanks npetzall. I used Schemaspy to create the diagrams, but am not sure if I am reading the relationship symbols correctly. They kind of look like they use the crow's feet (information engineering) style symbols. Maybe I can try another application that uses a known style to see if I am reading them correctly.  Thanks for suggesting those ERD tools.

**Comment by npetzall** [comment]
They are more or less diagram tools, they won't reverse engeneer a diagram from a concrete database.

Hmm, when I get the time I'll have look at how it's done we use graphviz so there might be options either for graphviz or that the dot format has a style option.

**Comment by rafalkasa** [comment]
@pplll I close your issue because it it general question and doesn't has really impact on SchemaSpy
