### ISSUE TITLE
Informix Support: impossible to change DB_LOCALE in jdbc connection string

### ISSUE THREAD

**Issue by begooden-it** [schemaspy/schemaspy#137]
On Informix databases, it is sometimes necessary to insert some special parameters in the JDBC connection string. One of the applications of this requirement is when is necessary to specify the database codepage, which is done by passing "SERVER_LOCALE=en_US.57372" to the Informix connection String.

I did not see any way to pass this assignment to the CS at schemaSpy launch time.
Am I just missing something or is this possibility just missing ?

In that case, is it possible to add the possibility to insert special commands in the connection string ?

Impact: schemaSpy not usable with an informix DB that has a locale different from the standard en_US;XXX ones ( and changing the locale means unload/load of the whole DB....)

Example of such a connection string : 
jdbc:informix-sqli://10.6.1.9:1512/prod28:INFORMIXSERVER=hp17_jdevolo_tcp;DB_LOCALE=i w_il.8859-8;CLIENT_LOCALE=iw_il.8859-8

Thanks
Eric

**Comment by npetzall** [comment]
You should be able to use something like -connprops useSSL\=false

**Comment by begooden-it** [comment]
@npetzall: do you mean
-connprops SERVER_LOCALE=en_US.57372 ?

**Comment by begooden-it** [comment]
I tried to insert SERVER_LOCALE=en_US.57372 in the connprops file, and this does not insert the statement into the CS

**Comment by npetzall** [comment]
I use it on commandline and you might need to escape the = with \=

**Comment by npetzall** [comment]
@begooden-it did it work with `-connprops SERVER_LOCALE\=en_US.57372`

The `=` needs to be escaped.

**Comment by begooden-it** [comment]
@npetzall : Yes it did work, I found the typo ;-)
Thanks bunches

**Comment by npetzall** [comment]
Yeah, those nasty escape characters need to put I code block which isn't that natural on a cellphone.

If it's OK now could you close the issue?

**Comment by begooden-it** [comment]
Solution works!
Thank you
