### ISSUE TITLE
Informix Support: DATETIME data type reported as 'DATETIME' without FULL DataType description

### ISSUE THREAD

**Issue by begooden-it** [schemaspy/schemaspy#138]
Informix has a somewhat special implementation of the DATETIME data type ( since 1988, BTW).
If other vendors just used "DATETIME", Informix specifies the 'scope' of this datatype. This can be for example
- DATETIME YEAR TO SECOND,
- DATETIME YEAR TO MINUTE,
- DATETIME HOUR to FRACTION(5)
- etc .... many combinations possibles.

SchemaSpy just reports "DATETIME", clipping the right part of the scope, which is not correct in the sense that some columns seem to have the same datatype, and they don't.

I tried to use the 'length' field, but similar values of length can point to different datetime scopes, so this is not an acceptable workaround.

Is it possible to fix that issue for Informix, so that DATETIME columns be be correctly displayed in the tables and columns reports?

**Comment by npetzall** [comment]
After about 4 hrs of investigation.
I've found out that databasemetadata.getColumns() doesn't contain DATETIME largest_qualifier TO smallest_qualifier, but that ResultSet.getMetaData() does. Well this is true in JDBC driver 3.70.....

But in 4.10 this has been corrected both databasemetadata.getColumns()  and ResultSet.getMetaData() contain largest_qualifier TO smallest_qualifier.

![image](https://user-images.githubusercontent.com/4175123/33749230-e691adb6-dbcc-11e7-8309-4c9d54cb8c8c.png)

@begooden-it hurry up and get the 4.10 driver. (additional perks of the 4.10 version it's a single jar)

Fix Pack 4.10.JC7 Fix release date: 23 Jun 2016
http://www-01.ibm.com/support/docview.wss?uid=swg27048157
APAR: IT13093

**Comment by rafalkasa** [comment]
Yeah good investigation ! Any action plan or we can close the issue ?

**Comment by npetzall** [comment]
I was considering a wiki with know issues such as this. But you can search issues. So I just closed it issue in jdbc-driver that has been fixed. No change in schemaspy required.

**Comment by begooden-it** [comment]
Great, it works, just tested with almost last ifmx JDBC 4.10FC9 (FC10 should be available since 12.10 xC10 release a few weeks ago)

effectivement, I rarely update my CSDK,, although i stick pretty well to the servers versions...
I am more a Unix person but hey, what did you expect ;-)

thanks
you can close

**Comment by begooden-it** [comment]
Additional question, probably should be another thread though: any plan on supporting JSON datatype for Informix ?
I have not tested yet to run schemaSpy against tables containing JSON/NoSQL data types, but am curious about it

**Comment by npetzall** [comment]
We do use the information returned from the driver so as long as their jdbc-driver is solid it should work
