### ISSUE TITLE
Version strategy

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#139]
Since we have a snapshot, it should be called snapshot. Maven has a release plugin we should use it.

**Comment by npetzall** [comment]
Or we do continuous delivery and add buildNumber to version so 6.0.39

And just make sure that whenever we add new features we bump minor and any backwards breaking change bump major. Normal refactoring, bugfix will just bump the patch(buildnumber)

**Comment by rafalkasa** [comment]
@npetzall we can start thinking and consider something like each merge will generate the new version but I would like to have only released version and something that we can call snapshot or latest.

**Comment by npetzall** [comment]
I'm more or less fine either way we go. We just need to document it.

If we break it into modules, people don't want to use snapshots and they might not be interested in waiting months for a release with fixes.

So a release schedule might be nice, and release only if feature, fix or improvement to user experience. Aka refactoring doesn't qualify for release.
