### ISSUE TITLE
is it called schemaspy (a after m) or schemespy (e after m) ?

### ISSUE THREAD

**Issue by mapausch** [schemaspy/schemaspy#141]
this is more a "cosmetical" issue than a technical one.

- the domain is schem**a**spy.org
- the downloadable jar is named "schem**a**spy-<version>.jar"

- in the footer on the website it's "Copyright © schem**e**spy.org 2017
- in the footer of the generated HTML files it's "Generate by Schem**e**Spy 6.0.0-rc1"

---> what's the correct name of the successor of SchemaSpy?

**Comment by Riggs333** [comment]
Thanks for pointing out, @mapausch! :+1: 
This is a typo. The correct name is Schem**a**Spy. :-)

We'll fix this soon.

**Comment by mapausch** [comment]
Just noticed that downloading schemaspy@latest gives a more current version than downloading RC1.
In schemaspy@latest the typo in the footer of the generated HTML files is already corrected :-)
So it's just the website that still shows schem**e**spy

**Comment by rafalkasa** [comment]
fixed in https://github.com/schemaspy/schemaspy.github.io/pull/3
