### ISSUE TITLE
SchemaSpy ERD (relationship tab) is not showing lines between tables

### ISSUE THREAD

**Issue by KhemrajShankarappa** [schemaspy/schemaspy#1426]
## Expected Behavior

We are expecting tool to show lines between to tables if there is relationships. 
## Current Behavior

We have created Primary Key and Foreign Keys for the tables. Sometimes these lines show up but most of the time it doesn't. 
## Steps to Reproduce (for bugs)

1. Create ERDs as per doc (java -jar \schemaspy-6.2.4.jar -configFile \config.file)
2. Once completed open the report
3. In Relationship tab you will find lines are missing
4.

## Context

* Database type (e.g. MySQL): Oracle
* Database driver version (is you use a special one): ojdbc8-19.14.0.0
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy: (java -jar \schemaspy-6.2.4.jar -configFile \config.file

## Your Environment

* Version used: 6.2
* Environment name and version (e.g. Chrome 39): Chrome 123.0.6312.59 
* Operating System and version (e.g. Windows 10):
* Java version: 8
![SchemaSpyERD](https://github.com/schemaspy/schemaspy/assets/159749356/636d48b1-b94e-420c-a752-edea735670e0)

**Comment by npetzall** [comment]
This seems to be the same issue as #1306 where it's a reported bug with GraphViz.

That is if your using GraphViz 9.0.0 on Windows and not using the `vizjs` option.

**Comment by KhemrajShankarappa** [comment]
You are right, I am using "windows_10_cmake_Release_graphviz-install-9.0.0-win64" . 
Can you please help me to know how to use vizjs option.

**Comment by npetzall** [comment]
On command line add `-vizjs` or I configFile add `schemaspy.vizjs`

**Comment by KhemrajShankarappa** [comment]
I used graphviz 8 version and that helped. now i am getting proper lines. thanks for your help
