### ISSUE TITLE
no "datatables" directory in subdirectory bower/admin-lte/plugins of SchemaSpy-output

### ISSUE THREAD

**Issue by mapausch** [schemaspy/schemaspy#147]
during investigations for https://github.com/schemaspy/schemaspy/issues/144
I found another HTTP 404 (File not found):

![grafik](https://user-images.githubusercontent.com/18686836/30693772-539563dc-9ed1-11e7-8b37-0fc763270ef2.png)

`
[13:34:20][root@schemaspy:/srv/www/vhosts/schemaspy/schemas/database_qa_schemaspy6/bower/admin-lte/plugins]#pwd
/srv/www/vhosts/schemaspy/schemas/database_qa_schemaspy6/bower/admin-lte/plugins

[13:34:22][root@schemaspy:/srv/www/vhosts/schemaspy/schemas/database_qa_schemaspy6/bower/admin-lte/plugins]#ls -la
total 24
drwxr-xr-x 6 root root 4096 Sep 21 09:14 .
drwxr-xr-x 5 root root 4096 Sep 21 09:14 ..
drwxr-xr-x 2 root root 4096 Sep 21 09:14 fastclick
drwxr-xr-x 2 root root 4096 Sep 21 13:19 jQuery
drwxr-xr-x 2 root root 4096 Sep 21 09:14 jQueryUI
drwxr-xr-x 2 root root 4096 Sep 21 09:14 slimScroll
`
There are some "datatables.net*" directories in subdirectory bower, but no "datatables" directory in the subdirectory bower/admin-lte/plugins

**Comment by rafalkasa** [comment]
This issue was fixed in commit 244307c. Thank you for reporting the bug
