### ISSUE TITLE
Live website?

### ISSUE THREAD

**Issue by aminroosta** [schemaspy/schemaspy#1488]
Hey SchemaSpy developers,

I'm considering building a live website that runs SchemaSpy under the hood and provides users with a graphical interface to quickly iterate their database designs. Here is what I've come up with so far in a Figma design. Please let me know what you think of it (before I commit to the implementation). Is it useful at all? would you ever use it? and if so, what other features would you want it to support?

![LandingPage](https://github.com/schemaspy/schemaspy/assets/2920178/03121724-b47c-4091-9804-654605cf3f90)

**Comment by npetzall** [comment]
Hi

It's an interesting and cool idea. The Figma looks nice.

I'm not a DBA so I can't provide any useful insight's to the usability, last time I designed anything related to persistence I choose something different than a relationship database. Some are stuck with RDBMS, others are using the new wave of NoSQL. With that I want to emphasise that it's a big market, and we will probably always have RDBMS.

The bigger question is rather what the design process would look like. 

Would you want to begin with DDL-SQL or do you want to begin with the diagram.

From a technical perspective, SchemaSpy has no way of processing DDL, the service could recreate the database and SchemaSpy read the newly/recreated database. Until you get all DDL statements needed to produce a complete database.

I personally think it's easier to start with drawing diagrams and model things that way. If that diagram could be translated to the target DBMS DDL I would be satisfied. I as a developer of SchemaSpy would probably run SchemaSpy to validate the Diagram to SQL translation.

**Comment by aminroosta** [comment]
I have an MVP running on my local machine; I plan to host it on a hetzner k8s cluster next.
Right now it's effectively a web interface over the schemaspy.jar file, nothing more.

> Would you want to begin with DDL-SQL or do you want to begin with the diagram

I think the DDL-SQL is faster to iterate, programmers rarely use visual tools to write code.
Also, it's a massive project to do the reverse, since I can't leverage an existing tool like schemaspy.

![quickschemadb](https://github.com/user-attachments/assets/71918fdb-3bca-4162-b991-7ea22e0651e1)

**Comment by npetzall** [comment]
Yeah, going from diagram to SQL is a massive undertaking.

But does it work something like. Enter SQL to create tables, it creates a temporary database + tables etc, and then creates a report of the temporary database. Then it's a bit like db-fiddle or in the ball park of the fiddlers (js, php, react etc etc). Which serves a great purpose in learning and visualising what you're doing.

As for the whole iterate thing, I'm inclined to accept the argument from a startup perspective, and you can drive that argument hard. When it's a system that has been in production for sometime. There's a lot of data that might need to be migrated, refactoring database isn't trivial. But that could be a next step in the evolution of you tool/service. 

Talking from the startup perspective. You try to model the domain and having quick feedback like this is essential. Might be doing it UML or some other free form diagram. You move on to writing SQL statement, you get the feedback and when the report matches your diagram you know your on the right path.

**Comment by aminroosta** [comment]
My pet project is live: https://quickdbschema.com/ 🎉
