### ISSUE TITLE
mariadb - if using Oracle packages, the output only includes either the definition or the package body - not both.

### ISSUE THREAD

**Issue by vk4ypb** [schemaspy/schemaspy#1530]
## Expected Behavior
I expect both the package definition and the package body to be generated.

## Current Behavior
Only either the definition or the body is produced.
From what I can see, the name is used as the file name for the output, This is NOT unique, so the filename should include the "routine type" as well.

## Possible Solution
Include both in output, will require filename change to include routine type.

## Steps to Reproduce (for bugs)
Run against mariadb with oracle packages defined.

## Context
* Database type : mariadb (11)
* Database driver version (is you use a special one): mariadb-java-client-3.5.1.jar
* 
* Full command including arguments how you run SchemaSpy: 

## Your Environment

* Version used: latest - including 7.0 snapshot
* Environment name and version (e.g. Chrome 39): firefox
* Operating System and version (e.g. Windows 10): ubuntu 24.04
* Java version: OpenJDK Runtime Environment (build 21.0.5+11-Ubuntu-1ubuntu124.04)
* Database : mariadb 11.6.1

**Comment by npetzall** [comment]
Hi, this probably has to do with how we query the information from mariadb, which currently inherits from MySQL since it was a drop in replacement way back when.

If you can produce a tiny example I might have the time to look into it.

I think this has been solved for other databases by adding the package name to the routine (as we call it), or adding the arguments, when overloading is allowed.

**Comment by vk4ypb** [comment]
Please find attached a tar file that as an SQL script to create a test database with a test package. Also the output from the latest 7.0 build

[sspy_test.zip](https://github.com/user-attachments/files/18103208/sspy_test.zip)

**Comment by vk4ypb** [comment]
OK. well I worked out a solution.

Modify the mariadb.properties file in the resources/org/schemaspy/types directory - add the following will create separate entities with the package specification and the package body.

# select any stored procedures and functions
selectRoutinesSql=select if(routine_type LIKE 'PACKAGE%',concat(routine_name,'_',replace(lower(routine_type),' ','_')),routine_name) as routine_name, routine_type, dtd_identifier, routine_body, routine_definition, is_deterministic LIKE 'Yes' as is_deterministic, sql_data_access, security_type, sql_mode, routine_comment from information_schema.routines where routine_schema=:schema
