### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by leoherbie** [schemaspy/schemaspy#157]
Please release to maven central.

**Comment by npetzall** [comment]
Just to check. Schemaspy isn't really a library but an application so putting it on maven doesn't really add any benefits. Url to download from Maven vs url to download from github.

Unless you want to use it as a library if that is the intention, then we should probably refactor the code and make it in to a cpl of libraries and an application.

**Comment by rafalkasa** [comment]
@npetzall many users use SchemaSpy as Maven tool to lunch after the build generation process of database documentation.

Maven is not only used as library dependencies, this is how I understand @leoherbie proposition.

**Comment by npetzall** [comment]
I only ask since there might be areas we can improve to support some usecase better. Like using it in build process to generate up-to-date database documentation. It might be good to have it as a maven plugin that can publish to maven site.

**Comment by rafalkasa** [comment]
Good point! I would like to do with SchemaSpy something similar to the flyway https://flywaydb.org/getstarted/firststeps/maven

They have core library, API, command line tool and maven plugin.
I agree with you that it should be planed. Thank you for your opinion and suggestion.

**Comment by leoherbie** [comment]
I'm glad this issue caused a bit of discussion.  For us, we embed the classic schemaspy in our application as a library.  Then on startup we generate the schemaspy metadata and provide links to the generated artifacts from an admin section of our application.  One consideration is the old schemaspy did not have any third party dependencies so it worked great as a dependency.  I see the new schemaspy is a spring boot app.  This may make it a bit harder to include.

I could also see someone using it during a build phase as well even though this is not our usecase

**Comment by leoherbie** [comment]
BTW.  A minor consideration for schemaspy as a lib usecase I just thought of.  The old progress bar sysout output is not very friendly for applications that use a logging framework.  We thought about fixing this in our schemaspy 5 fork but never did.  You just get this constant ........ output continually printing.  Not really related to maven but is related to making it library friendly.

**Comment by npetzall** [comment]
Progress bar is somewhat reported in #119.

The "core" library and it's dependencies is going to be a bit trickier.

@leoherbie So for a person wanting to run your application they need graphviz installed?

**Comment by leoherbie** [comment]
Yes.  They do indeed need graphviz installed although as I recall it can still work partially without it.

**Comment by npetzall** [comment]
I propose starting by separating "functions" into packages.

Example 
org.schemaspy.db: anything related to extracting data from db
org.schemaspy.output: anything generated by schemaspy
org.schemaspy.cli: anything related to running it as an application from cmd

Then we could add:
org.schemaspy.maven
org.schemaspy.gradle

Later this will all become separate modules and separate artifacts in maven and one can pick and choose which ones they want.
In this case we can limit jcommander, spring etc to cli

**Comment by sin-bin** [comment]
@npetzall @rafalkasa Can you please release the current version of jar on Maven Central while you restructure the code?

There is a real usecase where projects are using SchemaSpy to generate part of their site documentation. I'm providing an example of how I use SchemaSpy for my projects. The real **pain** is having to install this jar manually to each build machine every time. The current jar can easily be used by the maven-dependency and exec-maven plugin combination.

```
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <executions>
            <execution>
              <id>copy-schemaspy-jars</id>
              <phase>pre-site</phase>
              <goals>
                <goal>copy</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <artifactItems>
              <artifactItem>
                <groupId>org.schemaspy</groupId>
                <artifactId>schemaspy</artifactId>
                <version>6.1.0</version>
                <type>jar</type>
                <overWrite>false</overWrite>
                <outputDirectory>${project.build.directory}/schemaspy</outputDirectory>
                <destFileName>schemaspy.jar</destFileName>
              </artifactItem>
              <artifactItem>
                <groupId>org.mariadb.jdbc</groupId>
                <artifactId>mariadb-java-client</artifactId>
                <version>${mariadb.version}</version>
                <type>jar</type>
                <overWrite>false</overWrite>
                <outputDirectory>${project.build.directory}/schemaspy</outputDirectory>
                <destFileName>mariadb-java-client.jar</destFileName>
              </artifactItem>
            </artifactItems>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>${exec-maven-plugin}</version>
          <executions>
            <execution>
              <id>site-schemaspy</id>
              <phase>pre-site</phase>
              <goals>
                <goal>exec</goal>
              </goals>
              <configuration>
                <executable>java</executable>
                <arguments>
                  <argument>-jar</argument>
                  <argument>${project.build.directory}/schemaspy/schemaspy.jar</argument>
                  <argument>-configFile</argument>
                  <argument>${project.basedir}/schemaspy.properties</argument>
                </arguments>
              </configuration>
            </execution>
          </executions>
        </plugin>
```

**Comment by cloudyster** [comment]
I would appreciate deploying the jar to mavencentral, as we would like to generate a db-report in our CI environment in a maven-based project.

In addition to @sin-bin getting schemaspy from mavencentral would allow local proxies (Nexus) to  cache the jar.

**Comment by npetzall** [comment]
@cloudyster a simple workaround would be to use jitpack.io

**Comment by cloudyster** [comment]
@npetzall thank you for the suggestion, jitpack.io looks good but due to regulatory restrictions we are tied to maven central.
As a workaround we have uploaded the artifact to our local Nexus-server but we would have to do this manually for each new release.

**Comment by npetzall** [comment]
I had a feeling that the restriction would be brought up at some point.

**Comment by zhurs** [comment]
+1
It would be great if you upload the jar to maven-central.

**Comment by rafalkasa** [comment]
Hi @marcelstoer we are working on that...  publishing SchemaSpy to Maven Central is finally in progress 😊

**Comment by npetzall** [comment]
I've received access and SNAPSHOTS are now uploaded to OSSRH.

Everything is prepared and next release (hopefully tomorrow will go to maven central)

**Comment by npetzall** [comment]
So first release to maven central version 6.2.2

If you don't specify the classifier `app` you will get a non-fat jar and dependencies need to be pulled in.
Using the classifier `app` you'll get the springboot application

**Comment by marcelstoer** [comment]
Fantastic, we're getting there!

- Not on Central yet: https://search.maven.org/search?q=g:org.schemaspy%20AND%20a:schemaspy. Maybe still being processed by OSSRH?
- Not on GitHub at https://github.com/schemaspy/schemaspy/releases.
- README still says 6.2.1 at https://github.com/schemaspy/schemaspy#installation.

**Comment by npetzall** [comment]
I wonder, if there is different indexing, or what they actually mean with new look.
![image](https://user-images.githubusercontent.com/4175123/227747972-71cf48ba-617c-4583-add3-8ce19b9cedd8.png)

https://central.sonatype.com/search?smo=true&q=schemaspy&namespace=org.schemaspy

Yeah I forgot, nice catch, readme and github release are still manual steps. I'm on it.
