### ISSUE TITLE
show columns page by page and not all at once

### ISSUE THREAD

**Issue by mapausch** [schemaspy/schemaspy#162]
in the tables overview there's a control to scroll tables page by page:
![grafik](https://user-images.githubusercontent.com/18686836/32052917-e731f788-ba59-11e7-9e3c-ddd4406755d6.png)

We have database schemas that have about 12k columns across about 850 tables and views.
The columns.html hast just about 3mb in size but rendering of all columns in the schema in the browser at once takes some time.

So a control like that in the tables overview maybe could prevent the browser to render everything at once and make a click on the COLUMNS module more responsive.

**Comment by npetzall** [comment]
@mapausch @rafalkasa @danwatt Is this finished? Everybody happy?

**Comment by npetzall** [comment]
Closing, if this is not ok. Feel free to re-open.

**Comment by mapausch** [comment]
The initial processing of columns.html still is very slow.
Browsing the pages is fast.

If we could have both would be perfect :-)

But don't know if it's even possible to implement that on initial load only the first "page" is rendered :-/

**Comment by npetzall** [comment]
We could have a look att using a browser database or similar. We could fake it by only adding first page in html and when rendering completed lazy load rest of the content. Only important thing would be to have the same sorting in html and Java.

**Comment by npetzall** [comment]
I'm gonna re-open this.
http://madebyknight.com/optimizing-datatables-performance/

Load json instead of dom and possibly the deferred render could make the load time much better.

**Comment by npetzall** [comment]
@mapausch I've tested adding a json object instead of directly in the dom, I turned on deferedRender and I went from 17.83 seconds down to 1.79 for 6661 columns/rows.

It's late right now and I know that things can be done. So I'm gonna polish the solution in the next days and also see if the current implementation isn't just too ugly.
