### ISSUE TITLE
Document how to set up docker for Unit Testing

### ISSUE THREAD

**Issue by danwatt** [schemaspy/schemaspy#167]
Getting docker running for certain tests (ex: MysqlXMLIT.java) needs to be documented

**Comment by npetzall** [comment]
Was it more then install docker?

I.e requirement? 
On Windows, osx or Linux?

**Comment by danwatt** [comment]
OSX - I already had Docker installed, but I hand't authenticated with dockerhub, and I had to define the environment variable inside of IntelliJ when running the tests (`DOCKER_CONFIG=~/.docker`)

**Comment by npetzall** [comment]
Hmm, Auth with dockerhub. That shouldn't be needed. Strange.

Just to cover bases. Recent docker I.e. Docker4mac or the older docker toolbox?

**Comment by danwatt** [comment]
Docker4mac, Version 17.09.0-ce-mac35 (19611) 

The auth might not have been necessary. It was the first thing I tried when I got the "invalid config file" error, which was solved by adding the environment variable

**Comment by npetzall** [comment]
Where did you put environment variable?
I've launched my work computer OSX Sierra and same version of Docker4Mac (IntelliJ 2017.1.3 Ultimate)
And it works launching from cmd `./mvnw verify` and from inside IntelliJ and I cant remember that I've done anything special.

**Comment by danwatt** [comment]
Ill try doing this again on a different (cleaner) machine. Let me get back to you.

**Comment by danwatt** [comment]
Weird... Other Mac (2017 MBP, High Sierra) that I havent done much development on, running Docker version 17.09.0-ce, build afdb6d4, worked fine in IJ, `mvn clean verify` and `./mvnw verify`
