### ISSUE TITLE
Codemirror attempts to attach to columns named `code`

### ISSUE THREAD

**Issue by danwatt** [schemaspy/schemaspy#176]
I have a table that has a column named `code`. The span for the column name has `code` as the ID, which causes the codemirror code to attempt to attach to that `span`.

Should we change how column span IDs are generated (ex: `<span id="col-{name}">`), or have CodeMirror look for a different ID (one that doesn't clash with column names)? Hopefully nobody has a column named `schemaspy-sql-source-codemirror`

```
<td class='primaryKey' title='Primary Key'><i class='icon ion-key iconkey' style='padding-left: 5px;'></i><span id="code">code</span></td>
```
![image](https://user-images.githubusercontent.com/655895/32575597-166699d8-c49a-11e7-84c5-6ce73f79de75.png)

**Comment by rafalkasa** [comment]
@danwatt I think that the easiest way will be change the ID for CodeMirror to eg. sql-script-codemirror.
This will resolve the issue. If you want you can create such PR.
