### ISSUE TITLE
Prepare documentation for routines support for SQLServer 

### ISSUE THREAD

**Issue by rafalkasa** [schemaspy/schemaspy#188]
This task is for prepare documentation about routines in SchemaSpy is related to the @danwatt PR #187

**Comment by npetzall** [comment]
@rafalkasa Is this just to add a note in read the docs about routines support?
Like a feature?

**Comment by npetzall** [comment]
I'll see what I can come up with.

**Comment by npetzall** [comment]
Closed by #349
