### ISSUE TITLE
Root comment in Schemaspy.meta doesn't update the schema comment

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#199]
It updates the config.setDescription() which is the same placeholder for Database.getDescription() which is used in HtmlMainIndexPage.

Schema.comment is used in the multi-output. So currently schema.comment can't be replaced with schemaMeta.

config.Description is possible to override with `-desc`, but that in turn can be overridden with schemaMeta/comment.

**Comment by npetzall** [comment]
We should document how we model a database. And take into account a couple of examples.

I have a hard time reasoning about this.
In some cases schema contains tables, others database contains schemas. Stackoverflow says don't go by how things are done in mysql since some doesn't consider it a proper database as sqlserver or Oracle.

**Comment by npetzall** [comment]
I mainly raise this issue with modeling since we have database model database contains tables, schema and catalog. Since I winder if the root comment in meta should set the schema comment or database comment. And in extension,  we say that schema meta by name is meta data for a schema and not a database.

**Comment by rafalkasa** [comment]
I'm afraid that from database to database we can meet different modeling schema, and is not so easy to agreed one common pattern. In general for the most of popular database engines have database -> schema -> tables, views, procedures, functions. In my opinion we should consider only the most common and popular database models.

**Comment by npetzall** [comment]
Postgress: Database -> Schema -> Tables and such
Mysql: Database/Schema -> Tables and such
Oracle: User/Schema -> Tables and such
SqlServer: Schema -> Tables and such

While SchemaSpy has Database -> Schema, Catalog, Tables
In some sense SchemaSpy treats Database as Schema, but to then have Schema as an entity of Database makes it a bit hard to grasp. Mainly the issue arrises from doing singel or multi schema analysis.

**Comment by npetzall** [comment]
Should we consider `-desc` a report description and treat schema comment as just schema comment?

If that is what we say, we can start working on correcting current behavior.

**Comment by npetzall** [comment]
Added fix for null comment so that it's ignored.
Schema.comments can't be cleared only overwritten.
Setting description is only possible from commandline.

Fixed by #282
