### ISSUE TITLE
Bug on row count with schema EXEC

### ISSUE THREAD

**Issue by trialsin** [schemaspy/schemaspy#217]
My database SQL have one schema with name EXEC. Then I got a error menssage when getting the row count of tables in that schema: See logs:

Analyzing EXEC
INFO  - Starting schema analysis
INFO  - Using database properties:
INFO  -   [E:\exe\Desenvolvimento\SchemaSpy\schemaSpy-6.jar]/org/schemaspy/types/mssql05-jtds.properties
INFO  - Connected to Microsoft SQL Server - 10.50.1600
INFO  - Gathering schema details
Gathering schema details...WARN  - Failed to determine auto increment status: java.sql.SQLException: Incorrect syntax near the keyword 'EXEC'.
**WARN  - SQL: select * from EXEC."tbEntidadePromotora" where 0 = 1
WARN  - Unable to extract the number of rows for table tbEntidadePromotora, using '-1'
WARN  - java.sql.SQLException: Incorrect syntax near the keyword 'EXEC'.**
.WARN  - Failed to determine auto increment status: java.sql.SQLException: Incorrect syntax near the keyword 'EXEC'.
WARN  - SQL: select * from EXEC."tbParticipanteFacilitador" where 0 = 1
WARN  - Unable to extract the number of rows for table tbParticipanteFacilitador, using '-1'
WARN  - java.sql.SQLException: Incorrect syntax near the keyword 'EXEC'.
.WARN  - Failed to determine auto increment status: java.sql.SQLException: Incorrect syntax near the keyword 'EXEC'.

In sql server I can write queries like **select * from [EXEC].[tbEntidadePromotora]**
Maybe if you put quotes in schema solve the problem like **select * from "EXEC"."tbEntidadePromotora"**

**Comment by npetzall** [comment]
Have you tried with snapshot. 
Since it should force quotes if it fails without quotes. 

Even if the identifier isn't identified as a keyword.

**Comment by npetzall** [comment]
I don't think we have a schemaSpy-6.jar so I'm unsure about the version you are using.
(normally printed 4 rows above "INFO - Starting schema analysis" unless you have a old build)

Could you try the [latest snapshot](https://github.com/schemaspy/schemaspy#latest-build)

I've tested in master and it works with a schema named EXEC.

**Comment by npetzall** [comment]
@trialsin Have you tried with the snapshot?

**Comment by rafalkasa** [comment]
@trialsin did you tried with the snapshot version of SchemaSpy? Can I close the issue ?

**Comment by trialsin** [comment]
I'm sorry for my slowly feedback...

About version 6, I've got it here: http://schemaspy.org/ (snap: http://bit.ly/2BYfP1h)

About snapshot, I've got a error when trying to build it: http://bit.ly/2C19m5t

**Comment by npetzall** [comment]
@trialsin use the link I have in my comment we always post latest build of master.

**Comment by trialsin** [comment]
Everything working in lastest build

Thank you very much!
