### ISSUE TITLE
DatabaseName changes between pages

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#233]
## Expected Behavior
DatabaseName should be consistent.

## Current Behavior
Index/Table:  
![image](https://user-images.githubusercontent.com/4175123/35200868-906cb7ac-ff15-11e7-9ea1-c47021db96b4.png)
Column:  
![image](https://user-images.githubusercontent.com/4175123/35200876-a7e4dc7a-ff15-11e7-9ba9-fe162ded56ad.png)

## Possible Solution
Use same single method to getDatabaseName possible in super class.

**Comment by uppalabharath** [comment]
Hi @npetzall, 

I have gone through the code base to figure out where the change is needed.
I suspect you might be referring to following classes: 

* org.schemaspy.view.HtmlTablePage
* org.schemaspy.view.HtmlColumnsPage

Few Observations: 
1. Both the classes use `org.schemaspy.view.MustacheWriter` for generating the HTML. 
2. Both classes use Database#getName() to get the database name. 

Please let me know if I am in right path regarding the issue.

**Comment by npetzall** [comment]
They behave the same and doesn't cause the difference. Take a gander in HtmlMainIndexPage.java

**Comment by uppalabharath** [comment]
Hi @npetzall, 

Is this issue newly introduced. 
The sample output available at http://schemaspy.org/sample/index.html is proper and consistent with the Database names. 

One more help I would need is, how can we test whether our changes are correct. I mean did you setup a database and test else we have some simulation that tests the output. 
-- 
Thanks,
Bharath

**Comment by npetzall** [comment]
How old I would need to investigate.

For testing we use docker and a library called testcontainers. 

If you have docker there is a test MysqlFullHtml that will produce html report in target. You should see the issue there.

**Comment by npetzall** [comment]
MysqlFullHtml is just a record and compare doesn't say if something is wrong or right only if things have changed.

**Comment by npetzall** [comment]
I would guesstimate the inconsistency has been around for sometime but due to changes 10 months ago. Schema and catalog became required fields. As such the getDatabaseName in HtmlMainIndexPage started to produce output that differed.

**Comment by uppalabharath** [comment]
Actually, in HtmlMainIndexPage.java line 71 
the databaseName is expicitly obtained from method getDatabaseName
`String databaseName = getDatabaseName(database);`

This is set into scope of Mustache engine in line 101 
`scopes.put("databaseName", databaseName);`

Need to try setting the databaseName directly as database.getName();

**Comment by npetzall** [comment]
What happens if you just remove it from the scope in HtmlMainIndexPage?

**Comment by uppalabharath** [comment]
Hi @npetzall , 

The variable databaseName is referenced in main.html in line 7 
`<h4>SchemaSpy Analysis of {{databaseName}}</h4>`

Moreover in the sample db that is Chinook Database info, the database name is consistent across the header but in index.html in the Tables section, the info is shown as 
> SchemaSpy Analysis of Chinook.dbo (Chinook is the schema and dbo is the catalog as per the getDatabaseName method implementation in HtmlMainIndexPage.java) 

In src/test/resources/integrationTesting/expecting/mysqlhtml/index.html, which is used as part of integration testing, in line 49 
`<a href="index.html" class="navbar-brand"><b>test.test</b> Database</a>` , the database name is specified as test.test. Is the integration test successful with the name as test.test

Thanks, 
Bharath

**Comment by npetzall** [comment]
In #eede778 the database description and databaseName was separated into two different scope variables.

Chinook database is generated 7th of April 2017 with rc1. It's pretty old.

The mysqlhtml test is just a recording of how the html was generated in a point of time. I added it before I did some refactoring of the class that writes the html.
This means that mysqlhtml doesn't say anything about what's right or wrong only if things change and if they do, you inspect and if everything is good, you update the expectation.

**Comment by rafalkasa** [comment]
@uppalabharath and @npetzall 

If you would like to change the current Database Name to be more consistent please check your solution that is working also with multiple schemas on one database.

**Comment by uppalabharath** [comment]
Hi, 

I shall setup the testing environment and verify the changes. 
Does the docker image contains all the needed things to setup test bed. 

Thanks, 
Bharath

**Comment by npetzall** [comment]
The images is plain mysql in the test a script is referenced. Mor or less all you have to do is have docker.

**Comment by uppalabharath** [comment]
Hi @npetzall / @rafalkasa , 
 
I had setup mysql DB in my local system and ran schemaspy to generate the reports. 
I am able to replicate the issue. 

I am trying to move the getDataBaseName() to a super class to make the behavior consistent across pages. 

Thanks, 
Bharath

**Comment by npetzall** [comment]
@uppalabharath superclass is not necessary, only that they all use same method.

**Comment by uppalabharath** [comment]
Yes I didn't create a super class but all the files like HtmlTablePage (which generate the html pages) extends  HTMLFormatter. So I moved the getDatabaseName() method to this HtmlFormatter class and used it across pages while creating an instance of Mustache writer.

**Comment by uppalabharath** [comment]
Hi @npetzall, 

Output after the changes.  

![columns](https://user-images.githubusercontent.com/16371262/36498954-e2a7cf44-1765-11e8-8038-6d5d48cf6578.png)
![table](https://user-images.githubusercontent.com/16371262/36498955-e2ef8410-1765-11e8-91ff-bef6cd4e0e3c.png)

I have verified the output for multiple schemas as well.

**Comment by npetzall** [comment]
Wouldn't a simpler solution been moving the method to the mustaschwriter class and remove the databaseName override in HtmlMainIndexPage. Since mustaschwriter will now always set databaseName but it will be overwritten by every caller?

**Comment by uppalabharath** [comment]
Yes that can be done but the changes would also need to be made for the constructor of MustacheWriter as the present implementation expects a String parameter which would be replaced by Database Object.

**Comment by npetzall** [comment]
You are right. I thought it took a database in the constructor.

**Comment by npetzall** [comment]
I did a quick search of {databaseName} usage in templates.

I think I've found a couple of issues we need to solve later.

![image](https://user-images.githubusercontent.com/4175123/36499702-673f5480-1742-11e8-9fc8-b3fb11008f59.png)

Both Analysis are fine.
The xml href is not dependable. Might get more dependable now, but not sure.
The code to produce databaseName and the code that produces the xml-file name aren't the same.
The title mysq.test1 or test.test as in my screenshots are weird when read with database at the end.
But that has more to do with what one considers a database to be. Since its database + schema and could probably be databaseName + Schema + Catalog Database.

**Comment by uppalabharath** [comment]
Hi @npetzall, 

Agree with you. 

Here 
Database name -- we refer to the service name / Service Identifier in the connection string. 
Schema name -- we use the schema name 
Catalog name -- I need to learn about catalogs in DB before commenting on this.

**Comment by npetzall** [comment]
Simplest would just be to remove the "Database" from the title.
Since some databases, SQLServer has Instance and it can have multiple databases which can have multiple schemas. Might be the same for Oracle, mysql is weird it more or less doesn't care about schemas, and says schemas and databases are the same. But in other places it says catalog and databases are the same and schemas doesn't exist.

**Comment by mdb3624** [comment]
This sounds very much like issue #165 that I had reported a while ago. I found that is I did not add the -s  option that the maps and links on the page would be different between pages.

**Comment by npetzall** [comment]
I know this is an old issue. I just got to testing this with mysql and it becomes really bad.
I think the issue is manly with mysql, but we probably have lots of mysql users.

Since it defaults to using -db and but database, catalog and schema are all the same thing in mysql

I becomes really messed up.

As an example
Have 3 database/catalog/schemas:
First, Second and Third

When connecting using -db First and -all
The mainIndex for multi has DB name First.
All the individual schemas get named like: First.First, First.Second, First.Third

I believe that we are using -db a bit too much.

**Comment by npetzall** [comment]
Further testing without the proposed fix using -all, shows that -db is mostly used, so schemas will have only -db as heading. Which makes it really weird.

You click routinesit schema and it says htmlit Database.
