### ISSUE TITLE
Outdated dockerhub documentation

### ISSUE THREAD

**Issue by plumSemPy** [schemaspy/schemaspy#239]
## Expected Behavior
In [dockerhub](https://hub.docker.com/r/schemaspy/schemaspy/) it is stated that to pull we must simple do: `docker pull schemaspy/schemaspy` -- that is what I expect to do.

## Current Behavior
We must `docker pull schempaspy/schemaspy:snapshot`, otherwise it will not be found.

## Possible Solution
`docker pull schemaspy/schemaspy` will look for the tag `latest` there is not `latest` tag [here](https://hub.docker.com/r/schemaspy/schemaspy/tags/)

## Steps to Reproduce (for bugs)
in  console:
```sh
docker pull schemaspy/schemaspy
```

**Comment by npetzall** [comment]
Sadly 
![image](https://user-images.githubusercontent.com/4175123/35598861-19b07fbe-0626-11e8-9969-6151e860f226.png)

Can not be customized. Currently we have no release. So there is no latest tag.
I've added some text to docker hub.

**Comment by npetzall** [comment]
@rafalkasa Should be ok as soon as 6.0.0 is released.

**Comment by npetzall** [comment]
Close after release of 6.0.0 if the deploy actually works. Since no release, no test has been done.
I'll track the issue.

**Comment by npetzall** [comment]
6.0.0 release and `docker pull schemaspy/schemaspy` now works
