### ISSUE TITLE
Document -imageformat parameter

### ISSUE THREAD

**Issue by pzo** [schemaspy/schemaspy#241]
Document the -imageformat parameter that allows svg output. 

See   v6.0.0-rc2 release (30-09-2017)
#63 Added -imageformat parameter (png, svg) default format is png
    This issue is in reference to the others issues extending SchemaSpy to have possibility of generate svg diagrams #41, #59, #60

**Comment by uppalabharath** [comment]
Hi @rafalkasa, 

I would like to contribute to SchemaSpy. I didn't find the instructions regarding the contribution guidelines in the repo. Could you please help me in this regard. 

Thanks in advance!!

**Comment by npetzall** [comment]
@uppalabharath there is a file but it's empty, fork, branch and pull request. You can also join us on gitter, click the badge in overview/Readme.md.
