### ISSUE TITLE
MySQL stored procedure `is_deterministic` = 'NO' suppresses stored procedure report

### ISSUE THREAD

**Issue by tsak** [schemaspy/schemaspy#244]
I tried running SchemaSpy on a MySQL database that included stored procedures. Apparently if a stored procedure is marked non-deterministic in MySQL's information schema, it keeps the stored procedure report from being generated.

## Expected Behavior
It should display analysis of stored procedures.

## Current Behavior
```
WARN  - Failed to retrieve stored procedure/function details: java.sql.SQLDataException: Cannot determine value type from string 'NO': select routine_name, routine_type, dtd_identifier, routine_body, routine_definition, is_deterministic, sql_data_access, security_type, sql_mode, routine_comment from information_schema.routines where routine_schema=:schema
```

Running...
```mysql
SELECT
  routine_name, routine_type, dtd_identifier, routine_body, routine_definition,
  is_deterministic, sql_data_access, security_type, sql_mode, routine_comment
FROM
  information_schema.routines
WHERE
  routine_schema='...'
```
...works. Presumably the value `NO` for the `is_deterministic` in the output stops the report on procedures/routines from working.

## Steps to Reproduce (for bugs)
```mysql
CREATE DATABASE test;
USE test;
CREATE FUNCTION hello (s CHAR(20))
RETURNS CHAR(50) NOT DETERMINISTIC
RETURN CONCAT('Hello, ',s,'!');
```

```bash
docker run -v "$PWD:/output" schemaspy/schemaspy:snapshot -t mysql -host localhost -u root -p root -db test -connprops useSSL\\=false -schemas "test"
```

## Context
* Database type (e.g. MySQL): MySQL 5.6
* Your DDL (sample how to reproduce the issue):
```mysql
CREATE DATABASE test;
USE test;
CREATE FUNCTION hello (s CHAR(20))
RETURNS CHAR(50) NOT DETERMINISTIC
RETURN CONCAT('Hello, ',s,'!');
```
* Full command including arguments how you run SchemaSpy:
```bash
docker run -v "$PWD:/output" schemaspy/schemaspy:snapshot -t mysql -host localhost -u root -p root -db test -connprops useSSL\\=false -schemas "test"
```

## Your Environment
* Version used: `6.0.0-rc2`
* Environment name and version (e.g. Chrome 39): Docker

**Comment by tsak** [comment]
P.S. I guess the error stems from the fact that the column is being read as `boolean` but is a `string` in MySQL (5.6)
https://github.com/schemaspy/schemaspy/blob/fd73355c21c5818abdc59b8f7916a9889dd48393/src/main/java/org/schemaspy/service/DatabaseService.java#L715

**Comment by npetzall** [comment]
Interesting need to check a cpl of versions and see if it differs and also if it can be solved with a cast  in the query.

**Comment by npetzall** [comment]
Cast didn't do the trick... like to the rescue.
This should be possible to "quick-fix"
Create file in $PWD called my-mysql.properties with content:
```
extends=mysql
selectRoutinesSql=select routine_name, routine_type, dtd_identifier, routine_body, routine_definition, is_deterministic LIKE 'Yes' as is_deterministic, sql_data_access, security_type, sql_mode, routine_comment from information_schema.routines where routine_schema=:schema
```

Now run with
`docker run -v "$PWD/my-mysql.properties:/my-mysql.properties" -v "$PWD:/output" schemaspy/schemaspy:snapshot -t /my-mysql -host localhost -u root -p root -db test -connprops useSSL\\=false -schemas "test"`

Haven't tried it but I think it should work else there's a pull request on the way.

**Comment by npetzall** [comment]
@tsak do another pull of the snapshot tag else it will use the one locally I think.

**Comment by tsak** [comment]
Pulled latest snapshot, ran on my db again, works like a charm.

Thank you very much for the fix!
