### ISSUE TITLE
[Question] How I designate only certain tables for processing?

### ISSUE THREAD

**Issue by hrstoyanov** [schemaspy/schemaspy#258]
My schema has a lot of stuff i want to avoid processing...

**Comment by npetzall** [comment]
This should be added to documentation:

-i "regex" for table inclusion
-I "regex" for table exclusion
-X "regex" for columns to exclude from relationships

-noviews
-norows

**Comment by hrstoyanov** [comment]
Thanks. Can I specif y a list of .. say 17 tables?

**Comment by npetzall** [comment]
it's regex so "(table1|table2|table3)" should work. Should since I haven't tried it.

**Comment by hrstoyanov** [comment]
thanks so tables with schemas should be like "(sch.table1|sch.table2)" or  "(sch\\.table1|sch\\.table2)" ?

**Comment by hrstoyanov** [comment]
you are correct, schema prefix is not needed. Thanks!

**Comment by npetzall** [comment]
Documentation added in pr #340

**Comment by MikePryadko** [comment]
In my DB  some tables are "partitioned" (PostgreSQL) so there is table `some_table` and dozens of `some_table_{number}` - I try to exclude them but unsuccessfully
I tried: `-I '_\d+$'`, `-I '_[0-9]+$'`
Does this feature works???
My version: `6.1.0`

**Comment by MikePryadko** [comment]
Even `-I '_3'` did not exclude tables like `code_movement_3` and `marking_code_3`

**Comment by npetzall** [comment]
You can test here -> https://www.freeformatter.com/java-regex-tester.html

Test Match and they you should have Results : .matches() method: true

Since it uses matches you need to add `.*` in the beginning.
So the first regex should be -I ".*_\d+$"

**Comment by MikePryadko** [comment]
by your link all works fine without `^.*`:
![Screenshot_2020-05-06_17-47-58](https://user-images.githubusercontent.com/31248040/81191606-e021e800-8fc1-11ea-9a7c-0aefeb9f5303.png)
Even simple case works fine:
![Screenshot_2020-05-06_17-49-33](https://user-images.githubusercontent.com/31248040/81191698-fdef4d00-8fc1-11ea-98cf-7680bb317024.png)

So, I've tested your advice (`-I '^.*_\d+$'`) and it works! Thanks!
I think your should add that moment to docs :smirk:

**Comment by npetzall** [comment]
![bild](https://user-images.githubusercontent.com/4175123/81193277-79013500-8fbb-11ea-9777-758e0ac35f53.png)

**Comment by atlterry** [comment]
The inline -I (Exclude file) works fine for a few tables; I have a need to exclude a lot of tables and was wondering how to use the I option with a file list.

Thanks in advance
