### ISSUE TITLE
Informix rights to parse correctly a DB

### ISSUE THREAD

**Issue by macdrai** [schemaspy/schemaspy#261]
Hi !

For production purpose I would like to create a special user that would parse regularly an Informix 12c database to extract the schema. I've looked in the manual but can't find my answer yet.

I'm not sure if that is the right place to ask but could someone provide me a full breakdown on the rights needed to perform all SchemaSpy operations on Vanilla Informix without breaking anything ? 
Thanks

**Comment by npetzall** [comment]
From the top of my head we use DatabaseMetadata, and we do queries in tables, like row count unless an alternate query to select count(*) from table. But currently we do pseudo select to get column info such as autoincremental.

I can do a deeper dive, but I'm guessing you need to read informix documentation for which privileges are needed for Database Metadata.

But currently no more than read access.

**Comment by npetzall** [comment]
@macdrai 
Please let me know if read access/select access is good enough of an answer.
I'm not a Informix guru, but I'm guessing that JDBC driver access system tables, so there might be more permissions required than select in the given schema unless, that permission gives access to metadata.

**Comment by brian-hughes** [comment]
Informix 12c isn't a real version, did you mean Oracle 12c or Informix 12.10?  For Informix at least, you just need connect permission to the datacase, the system catalog tables (and thus the metadata queries) are readable by any user by default that is connected.

**Comment by npetzall** [comment]
@brian-hughes Thanks for the information
