### ISSUE TITLE
Make getExportedKeys optional

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#267]
## Expected Behavior
Everything should finish quickly.

## Current Behavior
With 1000 tables it's not quick at all.

## Possible Solution
for mysql (this is probably implementation specific)
The getExportedKeys in TableService.connectTables is super slow.
Comment at the beginning of getExportedKeys
```
// also try to find all of the 'remote' tables in other schemas that
// point to our primary keys (not necessary in the normal case
// as we infer this from the opposite direction)
```

So it might be desirable to have it optional, and that you would need to enable it.

Silly me, three rows down the following comment exists
```
// get the foreign keys that reference our primary keys
// note that this can take an insane amount of time on Oracle (i.e. 30 secs per call)
```
Which probably explains #250 
3500 tables * 30 seconds per table estimated time would be about 29 hrs to complete.

## Steps to Reproduce (for bugs)

1. Create lots of tables Oracle or Mysql (both are oracle haha)
2. Try to analyze
3. Wait
4. Wait
5. Wait

## Context

* Database type (e.g. MySQL): MySQL
* Database driver version (is you use a special one): mysql-connector-j 6.0.6
* Your DDL (sample how to reproduce the issue): Just lots of tables, they don't even need to be connected.
* Full command including arguments how you run SchemaSpy: standard commandline for mysql, no frizzles

## Your Environment

* Version used: snapshot
* Environment name and version (e.g. Chrome 39): 
* Operating System and version (e.g. Windows 10): Ubuntu 16.04
* Java version: 1.8

**Comment by npetzall** [comment]
Comment in code:
```
// also try to find all of the 'remote' tables in other schemas that
// point to our primary keys (not necessary in the normal case
// as we infer this from the opposite direction)
// get the foreign keys that reference our primary keys
// note that this can take an insane amount of time on Oracle (i.e. 30 secs per call)
```
From JavaDoc DatabaseMetaData.getExportedKeys()
```
* Retrieves a description of the foreign key columns that reference the
* given table's primary key columns (the foreign keys exported by a
* table
```

getExportedKeys() get information about tables that have a FK pointing towards the specified table.
(this information is specified in another table than the requested)

getImportedKeys() get information about tables that the specified table has a FK towards.
(this information is specified in the table, that you are requesting)

So by default getImportedKeys should be much quicker. But I also assume that this information might be easier to extract with a custom query.

In either case when analyzing a single schema, and there are no cross schema references or you don't care about them. It add no benefit to getExportedKeys().

Analyzing a schema that has cross schema references this will/should show you the cross references.

**Comment by npetzall** [comment]
I just wonder if the getExportedKeys should be default ON or OFF. It's currently ON, and it might be hard to explain that when it's stupidly slow you need to turn it OFF.

**Comment by npetzall** [comment]
One thing would be to add an estimate logging and instruction on how to turn it off.
When first has finished, we print an estimated duration for the connectForeingKeys.
And inform that the estimate is due to searching for FKs defined in other tables for the current table.
It can be turned off with -noexporterkeys, and that this will not identify cross schema relationships where the remote schema is not analyzed.

**Comment by npetzall** [comment]
```
LOGGER.info("Estimated time remaining for connecting views is {}, most time might be spent in getExportedKeys, you can disable getExportedKeys with `-noexportedkeys`. The implication of this is that you won't get cross schema relationships where table in analysis is FK, and the remote schema isn't analyzed", DurationFormatter.formatMS(timeLeft));
```

Might want to have the estimated time always printed but only list the option about -noexportedkeys if exportedKeys is enabled.

**Comment by npetzall** [comment]
Closing #290 merged

**Comment by scanbix** [comment]
This switch 'getExportedKeys' is not defined anywhere in https://schemaspy.readthedocs.io/en/latest/index.html
