### ISSUE TITLE
Display enum values

### ISSUE THREAD

**Issue by alpha0010** [schemaspy/schemaspy#269]
It would be nice to see a list of allowed values for enum column types.  I am using v6.0.0-rc2 on a mysql database.

I see from `selectColumnTypesSql` in [mysql.properties](https://github.com/schemaspy/schemaspy/blob/v6.0.0-rc2/src/main/resources/org/schemaspy/types/mysql.properties) that the allowed values are being selected.  Is there then some config option I am missing to enable this?

**Comment by npetzall** [comment]
It doesn't have a feature flag, so it should be used.

It should update the TypeName and ShortType of a column it also seems that it's the same field bound in the table present in the column page.

If you run
```
select table_name, column_name, replace(column_type,"','","', '") as column_type, left(column_type, locate("(", column_type)-1) as short_column_type from information_schema.columns where table_schema=:schema and (column_type like 'enum(%' or column_type like 'set(%')
```

Replacing `:schema` what output do you get?
What version of mysql are you using and which version of the jdbc driver.

**Comment by alpha0010** [comment]
Thanks for the prompt reply.

I am using https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.45.zip .

```
mysql> select table_name, column_name, replace(column_type,"','","', '") as column_type, left(column_type, locate("(", column_type)-1) as short_column_type from information_schema.columns where table_schema='test_ml' and (column_type like 'enum(%' or column_type like 'set(%') LIMIT 2,1;
+------------+-------------+----------------+-------------------+
| table_name | column_name | column_type    | short_column_type |
+------------+-------------+----------------+-------------------+
| entity     | published   | enum('N', 'Y') | enum              |
+------------+-------------+----------------+-------------------+
1 row in set (0.01 sec)
```

![entity_schema](https://user-images.githubusercontent.com/4990928/36914819-8f3a4860-1e1c-11e8-9483-dba8e733a620.png)

**Comment by alpha0010** [comment]
And mysql version: 5.5.59-0ubuntu0.14.04.1 (Ubuntu).

**Comment by npetzall** [comment]
I'm gonna look into what is used in the table page.
Do you have the same issue if you choose the Columns link at the top of the page?

**Comment by alpha0010** [comment]
Thanks.

Yes, it shows there as well.
![columns_entity](https://user-images.githubusercontent.com/4990928/36915991-9c772df0-1e20-11e8-809c-e25a8a07253b.png)

**Comment by npetzall** [comment]
On the overview page we have a link to download a snapshot/latest build, could you test with the snapshot? https://github.com/schemaspy/schemaspy#latest-build

I did a quick test and i got

![screenshot from 2018-03-02 19-56-17](https://user-images.githubusercontent.com/4175123/36916339-eac80c80-1e53-11e8-86a8-2408558f5c04.png)

```
CREATE TABLE group_resources (
  gid INTEGER NOT NULL,
  rid INTEGER NOT NULL,
  access ENUM('n','r','rw') DEFAULT 'n',
  PRIMARY KEY (gid, rid),
  FOREIGN KEY groups_gid_fk(gid) REFERENCES groups(gid),
  FOREIGN KEY resource_rid_fk(rid) REFERENCES resources(rid)
) engine=InnoDB COMMENT 'Group access to resource';
```

**Comment by alpha0010** [comment]
Same problem as before.  Of note, when mine gives of type enum, it displays all caps `ENUM`.

If it helps, my script executes:
```
java -jar schemaspy.jar -dp mysql-connector-java.jar -t mysql -s production -host $DB_HOST -db $1 -u $DB_USER -p $DB_PASSWORD -meta $1_schema.xml -o schema/$1 || exit 1
```

**Comment by alpha0010** [comment]
If useful:
```
alpha@dev:~$ java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

```

**Comment by npetzall** [comment]
Just for the sake of covering bases. Could you run it without `-meta $1_schema.xml`.
Much faster than actually looking in the meta-files.

**Comment by alpha0010** [comment]
No change in output of types.  (We use the meta file for table/column comments.)

**Comment by npetzall** [comment]
I'm not sure your running the latest build sadly I'm not at a computer but I believe you need `-cat "%"` on commandline when using latest build.

**Comment by npetzall** [comment]
I've tested with the released version(from release page here on github) and with the same jdbc-driver.
I still get the correct enum representation.
Would you be able to supply create statement for the table? Or a simplified that you could test first and then send me.

Only difference right now is the mysql version, but since the SQL query works, it's shouldn't be a factor.

Do you have any warnings or errors when running?

**Comment by alpha0010** [comment]
No warnings nor errors.  The following still results in the lack of enum values.  (This is using the latest build you linked me to.)
```
CREATE DATABASE test_enum_schema;
USE test_enum_schema;
CREATE TABLE `entity` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `entityID` VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
  `published` enum('N','Y') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`),
  UNIQUE KEY `entity_entityid_unique` (`entityID`)
);



$ docs/build-schema.sh test_enum_schema

MD5:
5603ac00cb347b83845218a26bce7a07  schemaspy-6.0.0-rc2.jar

SHA256:
b8054f7087b1854544029a7f79eada8fda70f2244226bea1930b183d3c742dd2  schemaspy-6.0.0-rc2.jar

java -jar schemaspy-6.0.0-rc2.jar -dp mysql-connector-java.jar -t mysql -s production -host $DB_HOST -db $1 -u $DB_USER -p $DB_PASSWORD -o schema/$1
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0-rc2

SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on *** with PID 15138 (/***/docs/schemaspy-6.0.0-rc2.jar started by *** in /***/docs)
INFO  - The following profiles are active: default
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Resolving dbType: mysql ->
	schemaspy-6.0.0-rc2.jar!/BOOT-INF/classes!/org/schemaspy/types/mysql.properties
INFO  - Connected to MySQL - 5.5.59-0ubuntu0.14.04.1
INFO  - Gathering schema details
Gathering schema details....(0sec)
Connecting relationships....(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
.........(0sec)
Writing/diagramming detailsINFO  - Completed summary in 0 seconds
INFO  - Writing/diagramming details
.Table -> entity
(0sec)
Wrote relationship details of 1 tables/views to directory 'schema/test_enum_schema' in 2 seconds.
View the results by opening schema/test_enum_schema/index.html
INFO  - Wrote table details in 0 seconds
INFO  - Wrote relationship details of 1 tables/views to directory 'schema/test_enum_schema' in 2 seconds.
INFO  - View the results by opening schema/test_enum_schema/index.html
INFO  - Started Main in 3.59 seconds (JVM running for 4.157)
```

**Comment by npetzall** [comment]
Awesome I'll hopefully create a test for this later tonight.

**Comment by alpha0010** [comment]
Thank you.

**Comment by npetzall** [comment]
I'm gonna blame my cold, since I didn't see it earlier.

```
select table_name, column_name, replace(column_type,"','","', '") as column_type, left(column_type, locate("(", column_type)-1) as short_column_type from information_schema.columns where table_schema=:schema and (column_type like 'enum(%' or column_type like 'set(%')
```
The query I asked you to test with I said replace :schema with the schema.

The application will replace :schema with the supplied `-s option` in your case `production`.

I'm not gonna rant about catalog, schema and database in regards to mysql.

But for the last test you did if -s had been `test_enum_schema` instead of `production` it should have worked.

So changing you script to `-s $1` should solve your problem.

**Comment by alpha0010** [comment]
Good catch.  I shall give it a go on Monday.  Thanks for your time.

Looks like I got confused by too many arcane parameters (schema vs database... oops).
