### ISSUE TITLE
SchemaSpy requires Graphviz graphvizVersion 2.26 or versions greater ...

### ISSUE THREAD

**Issue by videni** [schemaspy/schemaspy#276]
```
Graphviz Needed!
SchemaSpy was unable to generate a diagram of table relationships.
SchemaSpy requires Graphviz graphvizVersion 2.26 or versions greater than 2.31 from www.graphviz.org.
```
grahviz existed
```
/usr/local/Cellar/graphviz/2.40.1/bin/  
```

**Comment by npetzall** [comment]
That looks like a really weird path for windows. If it's osx have a look at #132

**Comment by npetzall** [comment]
Might be that graphviz is not on the path

You could try `-gv /usr/local/Cellar/graphviz/2.40.1/bin/`

-gv is a commandline argument to specify the bin dir of graphviz.

**Comment by videni** [comment]
@npetzall  I added that option to config file , still the same problem

**Comment by npetzall** [comment]
Could you run with `-debug` it will enable debug logging and stacktrace.

**Comment by npetzall** [comment]
And if you use docker you could use the docker image we have, which has graphviz included.

**Comment by npetzall** [comment]
@videni Have you tried the `-debug` option?
I need more information so that I can either help you or fix if there is a problem with SchemaSpy.
If we don't get any response we will close the issue.

**Comment by videni** [comment]
@npetzall, thanks  I am using the docker image, it works now.
