### ISSUE TITLE
ClassNotFoundException: com.microsoft.jdbc.sqlserver.SQLServerDriver

### ISSUE THREAD

**Issue by greddyatpt** [schemaspy/schemaspy#279]
JDBC driver class not found - com.microsoft.jdbc.sqlserver.SQLServerDriver

## Expected Behavior
It should find the class and continue.

## Current Behavior
Gives the class not found error.

## Possible Solution
It appears Microsoft has changed the class's FQN from 
com.microsoft.jdbc.sqlserver.SQLServerDriver
to 
com.microsoft.sqlserver.jdbc.SQLServerDriver  (sqlserver and jdbc are swapped)

If one name is not found, look for the other.  This will make it more compatible.

## Steps to Reproduce (for bugs)

1. Install the latest MS SQL driver [](https://www.microsoft.com/en-us/download/details.aspx?id=55539)
2. Create a MS SQL database with some test tables.
3. Run schemaSpy with the driver jar's path in the -dp switch 
4. You'll see the stack trace

## Context
I'm just trying to document an existing MS SQL database and schemaSpy appeared to be the best tool for it. But it didn't work with the latest 

## Your Environment
* Version used: 6.0.0-rc2
* Environment name and version: Chrome 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version: Mac OS High Sierra 10.13.2
* Java version: 1.8.0_131-b11

**Comment by npetzall** [comment]
What is your -t argument?

mssql or mssql or mssql08

I'm assuming mssql, could you try with mssql05 or mssql08

**Comment by npetzall** [comment]
mssql05 and 08 uses com.microsoft.sqlserver.jdbc.SQLServerDriver

Really a shame they didn't put a delegator in there like oracle did with mysql driver.

**Comment by npetzall** [comment]
Sorry for the bad responses but I'm juggling a 1yr old at the same time

**Comment by greddyatpt** [comment]
Thanks for your responses.  It works when I specify "-t mssql05".  Please close this issue.
