### ISSUE TITLE
Connect to snowflake

### ISSUE THREAD

**Issue by HezhiWang** [schemaspy/schemaspy#286]
Hi, 

I am trying to user schemaspy to analyze tables in [Snowflake.](https://www.snowflake.net) But it seems like snowflake is not in the build-in database types. Any ideas about how can I do it? Any examples would be great.

Thanks in advance!

**Comment by npetzall** [comment]
Did you find the information. Basically it comes down to "is there a jdbc driver".

If you want help you can look me up on gitter.

**Comment by HezhiWang** [comment]
Thank you! I found the information had successfully connected to snowflake.

**Comment by npetzall** [comment]
Nice,  would you mind creating a pull request to add it to the project or sharing the properties and I or other member can add it
