### ISSUE TITLE
mssql driver-name and jdbc-url not working

### ISSUE THREAD

**Issue by ahoehma** [schemaspy/schemaspy#291]
I guess the driver-name and jdbc-url is wrong :)

When I call 

java -jar '/d/Dev/Tools/Schemaspy/schemaspy-6.0.0-rc2.jar' -t mssql -dp '/d/Dev/Tools/mssql-jdbc/sqljdbc_6.0/deu/jre8/sqljdbc42.jar' -db 'XXXX' -host 'YYYY' -port 6201 -u UUUU -p PPPP  -o target/schemaspy

I got an error of missing class.

org.schemaspy.model.ConnectionFailure: java.lang.ClassNotFoundException: com.microsoft.jdbc.sqlserver.SQLServerDriver

But the real mssql jdbc driver is com.microsoft.sqlserver.jdbc.SQLServerDriver

So you switched sqlserver and jdbc :)

I fixed this but then I got another connection error ... I removed the "microsoft" from
connectionSpec and then it works :)

So my proposal is

driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
connectionSpec=jdbc:sqlserver://<hostOptionalPort>;databaseName=<db>

**Comment by npetzall** [comment]
See issue #279 

`-t mysql05` or `-t mysql08`

**Comment by npetzall** [comment]
Mysql wrapped the driver when they moved it microsoft didn't.
We could allow a list and check for both. To avoid this issue.
What do you think @rafalkasa

**Comment by ahoehma** [comment]
@npetzall  ahh I got it :) Cool thanks mate.

**Comment by ahoehma** [comment]
But wait ... mysql05  or mysql08 not available in my package :)
I'm using schemaspy-6.0.0-rc2

**Comment by ahoehma** [comment]
INFO  - Starting schema analysis
java.util.MissingResourceException: Can't find bundle for base name org/schemaspy/types/mysql05, locale de_DE
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
        at org.schemaspy.Config.determineDbProperties(Config.java:1437)

**Comment by ahoehma** [comment]
I downloaded the latest mssql driver from the microsoft-webpage and inside I found this

![image](https://user-images.githubusercontent.com/548214/37822660-5b960780-2e87-11e8-846c-c2bad0694340.png)

**Comment by npetzall** [comment]
Im soo sorry.

Of course it shouldnt be mysql05 or mysql08 it should be mssql05 or mssql08.

**Comment by ahoehma** [comment]
Also not existing :)

INFO  - Starting schema analysis
java.util.MissingResourceException: Can't find bundle for base name org/schemaspy/types/mssql08, locale de_DE
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
        at org.schemaspy.Config.determineDbProperties(Config.java:1437)

**Comment by npetzall** [comment]
Then I'm doubly sorry.
We name or snapshot the same way as we name or latest release candidate.

https://github.com/schemaspy/schemaspy#latest-build
and the link 
https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc2.jar

To get the latest and hottest that contains mssql08

**Comment by ahoehma** [comment]
I downloaded my version from here: https://github.com/schemaspy/schemaspy/releases/download/v6.0.0-rc2/schemaspy-6.0.0-rc2.jar

**Comment by npetzall** [comment]
We have #139 so that we should be able to distinguish snapshot from RC. So this has been "solved" in master/snapshot. However it could be done better. The connection string is the same and we should be able to specify multiple drivers and we try to find one of them.
