### ISSUE TITLE
Changing License to LGPLv3 or later for the project

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#305]
Backstory can be read in issue #206 

Original project was under LGPL 2.1 as written on the webpage.
Source contains following text
```
 * SchemaSpy is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
```

Which makes it version 2.1 or later.

Due to incorrect licensing see issue #206 your contributions have probably implicitly been licensed under MIT.

According to https://www.dwheeler.com/essays/floss-license-slide.html

MIT and LGPLv2.1 or later can be combined under "LGPLv2.1 or later" or "LGPLv3 or later"

If you look again at https://www.dwheeler.com/essays/floss-license-slide.html. 
You also see that Apache 2.0 is not compatible with LGPLv2.1 or later.

The project has a dependency to at least one Apache 2.0 licensed library. 
So the project as a whole must be licensed under "LGPLv3" or "LGPLv3 or later.".

It would be more clear if all source code in the project was under the same license.

We ask that you grant the SchemaSpy project your contributions under LGPLv3 or later.
(we will add copyright and license information to source code-files)

You can grant us your contributions under LGPLv3 or later by commenting to this issue with the following text (replace "[name]" with your full legal name).

```
I, [name] hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project
under GNU Lesser General Public License as published by the Free Software Foundation; either
version 3 of the License, or any later version.
```

**Contributors:**

- [x] @rafalkasa
- [x] @npetzall
- [x] @danwatt
- [x] @Riggs333
- [x] @wkasa 
- [x] @ismailsimsek
- [x] @mapausch
- [ ] @ClintEstwood
- [x] @martenbohlin
- [x] @johanvdw
- [x] @jornh
- [x] @dhermanns
- [x] @uppalabharath
- [x] @alpha0010
- [x] @jholland-usgs
- [ ] @igor-suhorukov

If you don't approve of this change we will add MIT Notice to files that have be contributed by you.
And we will distribute it under LGPLv3 or later.

**Comment by johanvdw** [comment]
I, Johan Van de Wauw hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project under GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or any later version.
--
Note that my contributions up to today were extremely small, consider that one in the public domain, feel free to use whatever license.

**Comment by Riggs333** [comment]
I, Thomas Traude hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project under GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or any later version.

**Comment by danwatt** [comment]
I, Daniel Watt hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project
under GNU Lesser General Public License as published by the Free Software Foundation; either
version 3 of the License, or any later version.

**Comment by rafalkasa** [comment]
I, Rafal Kasa hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project under GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or any later version.

**Comment by ismailsimsek** [comment]
I, ismail simsek hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project
under GNU Lesser General Public License as published by the Free Software Foundation; either
version 3 of the License, or any later version.

**Comment by wkasa** [comment]
I, Wojciech Kasa hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project under GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or any later version.

**Comment by mapausch** [comment]
I, Manfred Pausch hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project
under GNU Lesser General Public License as published by the Free Software Foundation; either
version 3 of the License, or any later version.

**Comment by dhermanns** [comment]
I, Dirk Hermanns hereby grant the SchemaSpy project all of my
contributions, past and present, to the SchemaSpy project
under GNU Lesser General Public License as published by the Free Software
Foundation; either
version 3 of the License, or any later version.

**Comment by jornh** [comment]
I, Jørn Hansen hereby grant the SchemaSpy project all of my contributions, past and present, to the SchemaSpy project under GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or any later version.

**Comment by uppalabharath** [comment]
I, Bharath Kumar Uppala hereby grant the SchemaSpy project all of my
contributions, past and present, to the SchemaSpy project
under GNU Lesser General Public License as published by the Free Software
Foundation; either version 3 of the License, or any later version.

**Comment by npetzall** [comment]
Done, 
ClintEstwood non copyrightable. 
igor-suhorukov not i master. 

Github Terms of service stipulates that inbound license will adhear to outbound. 
There might be a case as the license changed after the pull request was created. But his pr will be on hold until license information is added.

**Comment by npetzall** [comment]
@chintanp I think there was supposed to be an attached image.

The switch was from MIT to LGPL 3 or later. LGPL 3 or later includes the following passage
> This version of the GNU Lesser General Public License incorporates
the terms and conditions of version 3 of the GNU General Public
License, supplemented by the additional permissions listed below.

So if a question about GPL and LGPL it's just that we have included both since LGPL builds upon the GPL and GitHub adds licensing information based on files it finds, which is guess work. We should probably re-add the icon and information we had in the readme before it was re-worked.
