### ISSUE TITLE
Check Constraints not showing for MS SQL Server

### ISSUE THREAD

**Issue by kfugate** [schemaspy/schemaspy#320]
## Expected Behavior
Table level check constraints in the MS SQL Server database should show up in the output pages.

## Current Behavior
No check constraints are listed.  Foreign Key constraints are listed.

## Possible Solution
With only changing the SchemaSpy Jar... schemaSpy_5.0.0.jar works in showing check constraints ... schemaspy-6.0.0-rc2 does not.  Of course I would like to use version 6x.

## Steps to Reproduce (for bugs)

1. With only changing the SchemaSpy Jar... schemaSpy_5.0.0.jar works in showing check constraints ... schemaspy-6.0.0-rc2 does not.

2.  I've tried various *.properties  for mssql you have posted.   both with the 5x schemaspy and with 6x. No change in behavior (accept when it can run the older mssql type vs. the newer mssql05)

## Context

I really want to use this for our QA environment to help us better work with our databases but without listing the check constraints I can use it.

* Database type (e.g. MySQL): mssql05-jtds
* Database driver version (is you use a special one): jtds-1.3.1.jar
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

-jar "C:\Users\kfugate\Downloads\SchemaSpy\schemaSpy_5.0.0.jar" -gv "C:\Program Files (x86)\Graphviz2.38" -dp "C:\Users\kfugate\Downloads
\SchemaSpy\jtds-1.3.1-dist\jtds-1.3.1.jar" -t mssql05-jtds -db Customer -s dbo -host MYHOST -port 1433 -u myusername -p mypassword -connprops "C:\Users\kfugate\Downloads
\SchemaSpy\properties\mssql-jtds.properties" -I "syncobj.*" -o "C:\TMP\SchemaSpy\18_03\customer" -lq

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):  Windows Server 2012r2
* Java version: 
JAVA_VERSION="1.8.0_161"
OS_NAME="Windows"
OS_VERSION="5.1"
OS_ARCH="i586"

**Comment by npetzall** [comment]
To help with this could you supply a simple ddl for this issue.

Create table and create check constraint.

**Comment by npetzall** [comment]
When you get the connection failure could you add `-debug` to commandline it should now print a stacktrace together with the connection failure which would be interest g to have a look at. The 08 version only has modifications in regards to routines(functions, procedures)

**Comment by npetzall** [comment]
I've verified it should be read from the database. (I'm on 2017 so there might be difference)

The check constraints are retrieved using this query, you could test it on your instance.
```
SELECT tbls.name AS table_name, \
cnstrs.name AS constraint_name, \
cmts.text AS text \
FROM sysobjects cnstrs \
INNER JOIN sysobjects tbls ON cnstrs.parent_obj = tbls.id \
INNER JOIN syscomments cmts ON cmts.id = cnstrs.id \
WHERE cnstrs.type = 'C'
```
Yeah I have issue with the query since it doesn't have narrowing details such as catalog, schema or table... Table might be overkill, but it should be encapsulated on schema and possibly catalog.

So the information is retrieved. I'm gonna continue to check the html-output.

**Comment by npetzall** [comment]
Verified, the information exists in the model it's not written to the HTML output.

**Comment by kfugate** [comment]
I'm going to pull a -debug trace for you but I've needed to setup a test server/database since our production schema is sensitive info.  I should have that tomorrow.  I'll use AdventureWorks.   I did run the -debug option and I was able to connect.  I also ran with the mssql08 settings and these are awesome (I can see the stored procs/functions..etc).   But no check constraints.

**Comment by npetzall** [comment]
`-debug` is only needed for the connection issue. I've fixed the Check Constraint, I'm just cleaning up some tests.

**Comment by kfugate** [comment]
I'm new to github, I'm looking for this latest version which has #320 or #321 I can pull down and try.  If you could help point me to it, I will run it in my test environment and let you know if it's working there.

**Comment by npetzall** [comment]
You'll have to build it, so just make sure you have java 8 jdk.
https://github.com/npetzall/schemaspy/tree/320_check_constraints_not_showing

There is a Clone or download button, easiest is to download.
Unpack and in a termnal at the root of the unpacked file.
**Windows** `mvnw.cmd package -DskipTests`
**Linux** `./mvnw package -DskipTests`
The resulting application can be found in target

I've added skipTest just to make it quicker.

**Comment by kfugate** [comment]
Is there any insight into when the "Latest" would be updated to pickup these issues #319-#320?  I don't have a build environment to create my own *.jar.  I didn't know if these were done weekly, monthly or ad-hoc.  

Thanks for working on the fix for this.

Ken.

**Comment by npetzall** [comment]
As soon as it's added to master branch the latest build will be updated.

So when @rafalkasa gets time to review and if he approves my changes they will be added to master.

**Comment by kfugate** [comment]
I was hoping the latest commits would have this change included.   Since I'm new to GitHub I suspect this hasn't yet been included.   I downloaded the latest with the 5/23 changes but the check constraints still are not showing.   Since I don't have an environment to pull down the source and build my own jar, I'm in a holding pattern until the latest is updated with this change.    Any insight into when this might get included in the next build?

I appreciate all the efforts on this version of SchemaSpy

**Comment by npetzall** [comment]
@kfugate do you have access to docker?

**Comment by npetzall** [comment]
@kfugate I found this neat little hack.

There is a service called jitpack.io which is normally used to get github projects as maven dependencies.

Well it checks out the project and builds it and then stores the artifact. So you can download the branch as a runnable jar.

[Branch npetzall/schemaspy#320_check_constraint_not_showing](https://jitpack.io/com/github/npetzall/schemaspy/320_check_constraints_not_showing-v6.0.0-rc1-g05c0dd1-379/schemaspy-320_check_constraints_not_showing-v6.0.0-rc1-g05c0dd1-379.jar)

**Comment by kfugate** [comment]
I see there have been several commits since this has had a local fix.   If a vote is needed to get this picked up in the "latest" then you can count me.  I would like to be on that branch so as to also pickup any of the other latest changes.
