### ISSUE TITLE
Can't find bundle for base name org/schemaspy/types/mssql08

### ISSUE THREAD

**Issue by felipedram** [schemaspy/schemaspy#345]
Hi!

I'm trying to connect to a SQL Server 12.0.4232. When I run
```
java -jar schemaspy-6.0.0-rc2.jar -t mssql08 -db dbname -host 1.1.1.1 -port 1433 -u uname -o schema
````
I get 
```
SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main v6.0.0-rc2 on DESKTOP-SUFU0SC with PID 8844 (C:\[...]\schemaspy-6.0.0-rc2.jar started by Dumb in C:\[...]\dumb-db)
INFO  - No active profile set, falling back to default profiles: default
INFO  - Configuration file not found
INFO  - Starting schema analysis
java.util.MissingResourceException: Can't find bundle for base name org/schemaspy/types/mssql08, locale pt_BR
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at org.schemaspy.Config.determineDbProperties(Config.java:1437)
        at org.schemaspy.service.SqlService.connect(SqlService.java:50)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:181)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:88)
        at org.schemaspy.Main.runAnalyzer(Main.java:79)
        at org.schemaspy.Main.run(Main.java:72)
[...]
[...]
```
I also tried to use a local driver
```
java -jar schemaspy-6.0.0-rc2.jar -t mssql08 -dp mssql-jdbc-6.4.0.jre8.jar -db dbname -host 1.1.1.1 -port 1433 -u uname -o schema
```
and/or the option -t mssql05, but the answer is the same.

## Environment
I'm running on a Windows 10, with 
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
The server can be reach and the database does exists.

I think this could be related to [#292](https://github.com/schemaspy/schemaspy/issues/292), but I'm not shure.

Thanks,
Felipe Ramalho

**Comment by npetzall** [comment]
Mssql08 is not included in latest rc but latest build there is a link in Readme for latest/snapshot build.

**Comment by npetzall** [comment]
If you run with just `-dbhelp` you'll get a list of available databaseType for the current build.

**Comment by npetzall** [comment]
@felipedram Did it work by downloading latest-build? If not I'll need to investigate.

**Comment by felipedram** [comment]
Hi, @npetzall !
Thanks for your reply and sorry for the delay. (Tests week at university)

I've just tried the snapshot version.
It works pretty well with the local driver, but the default one reach on an error which I could get with the debug parameter. The log goes attached.
[error_default_driver.log](https://github.com/schemaspy/schemaspy/files/2094194/error_default_driver.log)

Thanks a lot!

**Comment by npetzall** [comment]
We don't bundle any drivers.
The only thing that it does is points at a default location for a specific driver. Which I personally want to remove #184 since in 99% of the cases `-dp` is needed.

But you found another issue I need to correct.

**Comment by npetzall** [comment]
Also works pretty well, if there were any issue please do share.

**Comment by npetzall** [comment]
No drivers are bundled if you have any other issues please let us know
