### ISSUE TITLE
Error while generating HTML output due to  / in the table names and column names in Hive databases

### ISSUE THREAD

**Issue by vidyadharms** [schemaspy/schemaspy#360]
I have a Schema in Hive database which contains / in the table name and column name. While generating HTML output for SchemaSpy it fails giving below error:

_java.io.IOException: java.io.FileNotFoundException: /localhome/vsatyp/SchemaSpy/npetzall/hive-kerberos/vsatyp_schema/diagrams/orphans/emp/loyee/test.1degree.dot (No such file or directory)_

where 'emp/loyee/test' is one table name

## Expected Behavior

The SchemaSpy should generate the HTML output with Schema details and original table name should be changed to something else in the generated HTML output...The user should be able to view the table name with / if it is there...

## Current Behavior

It is not generating HTML output for the Schema which has / in the table name and column name

## Possible Solution

Report should have same tablename as in database only files written should have safenames.

## Steps to Reproduce (for bugs)

1. Create test table in Hive Schema as below:
_CREATE TABLE emp/loyee/test (Id INT, First/Name STRING, Last/Name STRING) clustered by (Id) into 2 buckets stored as orc tblproperties ('transactional'='true');_

2.  Then below command to create the HTML output:
_java -Dhive-kerberos-principal=vsatyp@GLOBAL.COM -Dhive-kerberos-keytab=/localhome/vsatyp/vsatyp.keytab -jar /localhome/vsatyp/SchemaSpy/npetzall/schemaspy-6.0.0-rc2.jar -schemas vsatyp_schema -o /localhome/vsatyp/SchemaSpy/npetzall/hive-kerberos -db ProdHiveDB -u hive -t /localhome/vsatyp/SchemaSpy/npetzall/hive-kerberos.properties -dp /localhome/vsatyp/SchemaSpy/npetzall/hive-kerberos-driverwrapper-0.0.3-hdp-all.jar --logging.level.org.schemaspy=DEBUG_

## Context

It is not generating HTML output for other Schema as well. I need to generate the HTML Schema representation for all Schema in Hive database.

* Database type (e.g. MySQL): Hive
* Database driver version (is you use a special one):
hive-kerberos-driverwrapper-0.0.3-hdp-all.jar 

* Your DDL (sample how to reproduce the issue):
_CREATE TABLE emp/loyee/test (Id INT, First/Name STRING, Last/Name STRING) clustered by (Id) into 2 buckets stored as orc tblproperties ('transactional'='true');_

* Full command including arguments how you run SchemaSpy:
_java -Dhive-kerberos-principal=vsatyp@GLOBAL.COM -Dhive-kerberos-keytab=/localhome/vsatyp/vsatyp.keytab -jar /localhome/vsatyp/SchemaSpy/npetzall/schemaspy-6.0.0-rc2.jar -schemas vsatyp_schema -o /localhome/vsatyp/SchemaSpy/npetzall/hive-kerberos -db ProdHiveDB -u hive -t /localhome/vsatyp/SchemaSpy/npetzall/hive-kerberos.properties -dp /localhome/vsatyp/SchemaSpy/npetzall/hive-kerberos-driverwrapper-0.0.3-hdp-all.jar --logging.level.org.schemaspy=DEBUG_

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39): Chrome Version 67.0.3396.79 (Official Build) (64-bit)
* Operating System and version (e.g. Windows 10): Red Hat Enterprise Linux Server 7.5 (Maipo)
* Java version: java version "1.8.0_131"

**Comment by npetzall** [comment]
Able to reproduce in mysql.

**Comment by npetzall** [comment]
@vidyadharms 
I think I've handled most cases but still have schema and catalog to handle. (need to sleep)
So If schema/catalog doesn't contain `/` you can try my fix branch.
[npetzall/schemaspy#360_invalid_filenames](https://jitpack.io/com/github/npetzall/schemaspy/360_invalid_filenames-v6.0.0-rc1-ga7e82d1-434/schemaspy-360_invalid_filenames-v6.0.0-rc1-ga7e82d1-434.jar)

**Comment by npetzall** [comment]
Just need to add handling for schema and catalog and then PR.

**Comment by npetzall** [comment]
I've realized that the current implementation is way to naive so I'm going to fix it later.

I'll admit that I think we have some wholes in SchemaSpy already not related to filesystem but to case.
Mysql and many others supports treating `Table` and `TABLE` differently but I believe that we just treat them as `TABLE` so tables might be merged when they should be separate tables.

As for the naive implementation it just replaces a list of chars with `_` which is naive in the sense that `Ta\ble` and `Ta/ble` will both be `Ta_ble` and there's a risk of overwriting.

So I'm thinking of a search for characters that doesn't match [a-zA-z0-9.-_] and replace them with some kinde of unique alphanumeric character. Simplest would probably be _0x(unicode)_ or similare.

**Comment by npetzall** [comment]
Waiting confirmation that some code can be used.
