### ISSUE TITLE
exceptDirect not working as expected

### ISSUE THREAD

**Issue by pgorod** [schemaspy/schemaspy#371]
## Actual behavior

I have a metadata file with a bunch of relationships. It's a _very_ big database. You can see the full metadata file here:

https://schema--suitedocs.netlify.com/schema/metacrm.xml

So, basically the `disableDiagramAssociations="exceptDirect"` attribute isn't working correctly, in my interpretation. But it might be that my interpretation is wrong :-)

You can see the brilliantly beautiful rendered SchemaSpy output here:
https://schema--suitedocs.netlify.com/schema/

Almost half of my 557 relationships are for `user` table, `id` column. So I'm trying to un-clutter my diagrams by making them show only on directly connected tables.

So here is an example of the `users` table showing when it should (scroll to the diagram at the bottom): 
https://schema--suitedocs.netlify.com/schema/tables/aok_knowledgebase.html
:+1:

And here is an example of it being correctly ommited:
https://schema--suitedocs.netlify.com/schema/tables/aos_quotes_aos_invoices_c.html
:+1:

But now, on this same link, click on the `2 Degrees` tab. 
:-1:
You will see that the `users` table will pop up, despite having `directOnly` both on my focused table, and on all the other related tables, adding 17 lines to the diagram. On larger diagrams with more tables, it gets worse.

## Expected behavior
I was hoping that relationships with `directOnly` would never be traversed, except on level 1 diagrams where that relationship appears. 

This attribute would be checked not just for the center, "focused" table, but also for other tables that get added to the diagram when you select 2 degrees separation.

I hope this makes sense...

## Context

* Full command including arguments how you run SchemaSpy: java -jar schemaspy-6.0.0-rc2.jar

**schemaspy.properties:**
```
schemaspy.t=mysql
schemaspy.dp= ./mysql-connector-java-8.0.11.jar
schemaspy.host=localhost
schemaspy.port=3306
schemaspy.u=root
schemaspy.p=******
schemaspy.connprops="serverTimezone\=Europe/Lisbon"

schemaspy.norows
schemaspy.noimplied
schemaspy.noviews

schemaspy.meta= metacrm.xml
schemaspy.db=suitecrm
schemaspy.s=suitecrm
schemaspy.o=/var/www/html/schemas/suitecrm
```

## Your Environment
* Version used: 6.0 RC2
* Operating System and version: Ubuntu 16.04 64-bit
* Java version: OpenJDK version "1.8.0_171"

Thanks for this brilliant software, I'm loving it! 🥇

**Comment by npetzall** [comment]
If you read the docs, that I've written. I think your right and it should only be present in 1 degrees and never in 2 degree. I haven't verified the configo but it should be except Direct on user table and column ID.

**Comment by npetzall** [comment]
I took a look at the metadata-xml now, and I think it might be incorrect.
I can't find anything that looks like 
```
<table name="aos_invoices">
  <column name="modified_user_id" type="INT">
    <foreignKey table="users" column="id" disableDiagramAssociations="exceptDirect"/>
  </column>
  <column name="created_by" type="INT">
    <foreignKey table="users" column="id" disableDiagramAssociations="exceptDirect"/>
  </column>
  <column name="assigned_user_id" type="INT">
    <foreignKey table="users" column="id" disableDiagramAssociations="exceptDirect"/>
  </column>
</table>
```

**Comment by npetzall** [comment]
As a longer explanation to whats wrong.
aos_invoices has foreign keys to users, you need to modify them to be included in 1st degree only.

What's done in the metadata xml i suspect is that you try to modify this on user table.
But user table is the FK it doesn't have a FK constraint, and it's the constraint you need to modify.

**Comment by pgorod** [comment]
Ok, so if I understand correctly, I basically have my relationships defined in the opposite direction of how they should be, is that it?

Thanks for your time helping me out.

**Comment by npetzall** [comment]
It seems like it. I haven't done any testing so if it doesn't work you should re-open.

**Comment by pgorod** [comment]
Is there any difference if the XML you give above is written like this instead?

```xml
<table name="aos_invoices">
  <column name="modified_user_id" type="INT">
    <foreignKey table="users" column="id" disableDiagramAssociations="exceptDirect"/>
  </column>
</table>
<table name="aos_invoices">
  <column name="created_by" type="INT">
    <foreignKey table="users" column="id" disableDiagramAssociations="exceptDirect"/>
  </column>
</table>
<table name="aos_invoices">
  <column name="assigned_user_id" type="INT">
    <foreignKey table="users" column="id" disableDiagramAssociations="exceptDirect"/>
  </column>
</table>
```
My XML is automatically generated from a script, and it's much easier for me to produce it like this, with a new `<table>` for each constraint. Will SchemaSpy be ok with that?

In my tests, I am not getting errors, and the relationships get recognized. But since I'm still not getting proper results for exceptDirect, I am asking.

**Comment by npetzall** [comment]
I don't think it should be a problem. I had a look in the xml within the schema you linked and I think I saw that user table had a lot of xml added FK which were table-individually defined.

If I get them time tonight I'm gonna construct a test just to be sure.

**Comment by pgorod** [comment]
I swapped my relationships around, which I believe is the right thing to do, but now I get this warning

`WARN  - Failed to validate metacrm.xml: org.xml.sax.SAXParseException; cvc-complex-type.3.2.2: Attribute 'disableDiagramAssociations' is not allowed to appear in element 'foreignKey'.`

And now exceptDirect is not working, not even for first-level... :-(

**Comment by npetzall** [comment]
I believe it will discard invalid xml and the error means its not a valid xml is the foreignkey tag at the wrong location?

**Comment by npetzall** [comment]
I'm so sorry http://schemaspy.readthedocs.io/en/latest/configuration.html#schemameta-disablediagramassociations

The disable attribute should be on column. 

It really helps to read the documentation you've written yourself

**Comment by pgorod** [comment]
> Might be as simple as just adding this to users and Id column

Ok, so this gives results which _I think_ are consistent.

But I don't think they cover what would be ideal in terms of diagram simplification. So I guess this is not a bug, but I'm about to ask for a new feature :-)
I just feel that every time the table `users` goes into a complex diagram, it ruins the diagram (too many lines, to every table).

So the `exceptDirect` is doing its work normally as documented, but I'm getting a bunch of lines I would like to be able to avoid...

![image](https://user-images.githubusercontent.com/15945027/41985430-2b9c1142-7a2b-11e8-9143-061f6e5c31da.png)

So "invoices" is the table I'm focusing on. The `users` table appears, correctly, because it is connected in 1st degree with `invoices`. So are a bunch of other tables (contacts, accounts, etc). 

But those red lines? I wish they weren't there. Everything connects to `users`, but I´m not focusing on those other tables, I am focusing on `invoices`. I wish I could tell SchemaSpy to omit those red lines and draw just the black ones.

So if I'm only interested in a table on 1st degree, I am also only interested on that table´s relationships in the 1st degree.

Does this make sense to you?

**Comment by npetzall** [comment]
Let's recap and see if I understand.

We are only taking about 1st degree diagram. 

When a 1st degree connects to another 1st degree you get red lines between them. 

I would say that would actually constitute a 2nd degree connection and it shouldn't be there.

**Comment by pgorod** [comment]
Yes I think you're seeing it correctly.

I have just refreshed the `metacrm.xml` at the link above, it's my most current with `exceptDirect` only on `users.id`.

I also refreshed the deployed SchemaSpy results. So if you want to take a look at how it is now, this might help. Thanks for your continued help.

**Comment by pgorod** [comment]
This is the diagram that corresponds to my manual "red lines" schematic diagram above

https://schema--suitedocs.netlify.com/schema/tables/aos_invoices.html

**Comment by npetzall** [comment]
I think a new issue should be created Bug/Feature so that we can get rafalkasas opinion.

But from the link above, the only connection for users should be the connections to aos_invoices and to no other table, because I see how it clutters and as I said before those connections could be deemed 2nd degree.

**Comment by pgorod** [comment]
Ok, thanks. I will be away for a few days, back on Monday. 

About the Issue, maybe it's easier to just reopen this one, and re-label it? All the information is here.

**Comment by npetzall** [comment]
I can create the new issue if you want. I'll reference this issue and I can start working on a test to get the result that you see.

**Comment by pgorod** [comment]
:+1:

**Comment by npetzall** [comment]
@pgorod what do you think of issue 374 linked above?

**Comment by pgorod** [comment]
Perfect!
