### ISSUE TITLE
Always show a diagram/visual representation of table

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#376]
## Expected Behavior

All table pages has a diagram/visual representation of the database.

## Current Behavior

Orphan tables doesn't have it, except if they have implied which is a bit awkward.

## Possible Solution

Remove the condition that eliminates orphan tables.
In the long run we could remove the orphans diagram and just link/reuse the table diagrams.

**Comment by vlehm** [comment]
I would also love to have a visual diagram off all tables at once, similar to the orphan tables section :)

**Comment by npetzall** [comment]
@vlehm this is only so that all table pages have a diagram even orphan tables.

But if you want a table with all tables but without relationships that's a new feature request.
If you decide to do a feature request please also specify if you would want some kind of ordering or sorting of the tables.

**Comment by AndreKR** [comment]
Orphan tables should just be included in the database diagram, maybe using a command line option (to not change the current behavior for those who actually want it). Personally, I don't see the point of a diagram that shows *only* the tables that have relationships. I believe the sorting is currently done by Graphviz, and we can just keep it that way.

**Comment by npetzall** [comment]
@AndreKR this is only so that all table pages has a visual representation anything other than that should be a new issue.

**Comment by xenomachina** [comment]
Are there plans to make a new release with this fix? It looks like the PR was merged almost a year ago, but the latest release on dockerhub (6.1.0) predates that merge by a couple of days.

**Comment by npetzall** [comment]
@xenomachina Sadly development has stalled due to lack of time and with that also releases. 
But the functionality is available in the snapshot on docker-hub since snapshot is built on each merge.

If snapshot seems too risky you could get a build from jitpack.io and build a custom image.

**Comment by xenomachina** [comment]
I'm sorry to hear that, but I understand. I really like the output of SchemaSpy.

**Comment by marcelstoer** [comment]
> Sadly development has stalled

So happy to see recent activity on the master branch again 😄 👍 

> Orphan tables should just be included in the database diagram

Fully support that. I was searching for an existing issue before raising a new one and this is closest I could find.

**Comment by marcelstoer** [comment]
@npetzall I just tested the current master (6.1.1-SNAPSHOT) as I wasn't quite sure what to expect based on the description above and in the #603 comments.

It appears I was wrong to assume I would see also the orphan tables in the relationship diagram?

**Comment by npetzall** [comment]
@marcelstoer 
https://github.com/schemaspy/schemaspy/issues/376#issuecomment-455622205
https://github.com/schemaspy/schemaspy/issues/634

So this is only so that a diagram/visual representation exist of the table in the table page. 
If there were no relationships (orphan table) there wasn't any diagram/visual representation in the table page.

As for a release it might be in the making. As mention in earlier comment if you orphans are requested in the relationships diagram a new issue should be created so that possible implementations can be discussed. Since a possibly better solution would be to create a totally new diagram that contains everything and not add more to the relationship diagrams. Probably should name things better and add a glossery.

**Comment by marcelstoer** [comment]
Thanks, got it -> #763
