### ISSUE TITLE
SSL error connecting to Postgres server

### ISSUE THREAD

**Issue by manishtomar** [schemaspy/schemaspy#379]
Getting error when connecting to a Postgres server over SSL:
```
WARN  - SQLException occurred while connecting to xxxhost:5432
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "xxxx", user "xxxx", database "db_name", SSL off
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:473)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:205)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
...
```
I am using following config file and running via `java -jar schemaspy-6.0.0-rc2.jar -configFile ~/dump/reposconn.ini`:
```
# type of database. Run with -dbhelp for details
schemaspy.t=pgsql
# optional path to alternative jdbc drivers.
schemaspy.dp=/Users/manish/Downloads/postgresql-42.2.2.jar
# database properties: host, port number, name user, password
schemaspy.host=xxx
schemaspy.port=5432
schemaspy.db=db_name
schemaspy.u=xxx
schemaspy.p=xxx
# output dir to save generated files
schemaspy.o=/Users/manish/dump
schemaspy.ssl=true
```

## Expected Behavior
It should be able to connect via SSL. 

## Current Behavior
The DB server is enforcing SSL and it looks like schemaspy is having trouble with that.

## Possible Solution
SSL support should be there out of the box. Most likely I am not giving the right configuration. I apologize in advance for not being able to find it and will appreciate if someone can point me to it.

## Your Environment
OS: OSX 10.13.5
Java: 
```
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
SchemaSpy v6.0.0-rc2

**Comment by npetzall** [comment]
You need to add connection props

https://jdbc.postgresql.org/documentation/head/connect.html

And use `-connprops` i advice you to use a file. 
http://schemaspy.readthedocs.io/en/latest/configuration.html#connecting

Schemaspy.ssl is not an option.

**Comment by npetzall** [comment]
https://jdbc.postgresql.org/documentation/head/ssl-client.html

So depending on your setup it might be as simple as a file `connprops.properties` with following content
```
ssl=true
```

And added to commandline `-connprops connprops.properties`

If you have custom cert in server, according to docs you can either add ca and intermediate to Java keystor or you can skip validation by adding `sslfactory=org.postgresql.ssl.NonValidatingFactory` to `connprops.properties`

**Comment by manishtomar** [comment]
@npetzall Thank you so much for the help. It is giving `unable to find valid certification path to requested target` error which it shouldn't because cert is signed by genuine CA which should be there in the system. I've temporarily disabled verification by giving the above `sslfactory` option you provided (thanks again!) and it is working now. 

I apologize I was not able to figure this out as I've not used JDBC before. I knew I had to provide SSL settings in `-connprops`. I was trying `-connprops=useSSL\=true` and `-connprops=ssl\=true` and neither of them worked. Thanks again. Do you think it might be useful to add PG SSL settings in http://schemaspy.readthedocs.io/en/latest/started.html#advanced-usage?

**Comment by npetzall** [comment]
I'm not sure but the path problem is possibly a missing intermediate cert.

CA root -> company cert -> db cert.

CA root is available but the company intermediate cert is not. 

You also have connprops explained at http://schemaspy.readthedocs.io/en/latest/configuration.html#connecting

And now if people search they will find this issue.

**Comment by manishtomar** [comment]
Yeah. Sorry I missed that configuration part. Feel free to close this issue. OTOH it is getting stuck when generating diagrams:
```
manish:~/Downloads$ java -jar schemaspy-6.0.0-rc2.jar -configFile ~/dump/reposconn.ini -connprops ~/dump/connprops.properties
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/



SchemaSpy generates an HTML representation of a database schema's relationships.

INFO  - Starting Main on Dockers-MacBook-Pro-4.local with PID 4328 (/Users/manish/Downloads/schemaspy-6.0.0-rc2.jar started by manish in /Users/manish/Downloads)
INFO  - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/Users/manish/Downloads/schemaspy-6.0.0-rc2.jar!/BOOT-INF/lib/spring-core-4.3.11.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  - Found configuration file: /Users/manish/dump/reposconn.ini
INFO  - Starting schema analysis
INFO  - Failed to validate png renderer ':cairo'.  Reverting to default renderer for png.
INFO  - Using database properties:
INFO  -   [schemaspy-6.0.0-rc2.jar]/org/schemaspy/types/pgsql.properties
INFO  - Connected to PostgreSQL - 9.3.18
INFO  - Gathering schema details
Gathering schema details...........................................^Cmanish:~/Downloads$
```
Is there a way to debug why this is happening? Sorry from a quick glance I couldn't find any option to enable debugging info. We can continue this conversation in another thread if required. LMK.

**Comment by npetzall** [comment]
The reflective warning is Java 9 and related to a library we might drop, its not actively maintained.

As for debugging you have `-debug` it will log lots and lots of information. We have an open issue/enhancement to switch to a progressbar since in most cases we actually know how much work is to be done.

There might be I've seen issues with other databases when `-s schemaName` hasn't been used. It thinks everything is remote and a lot of additional processing is done.

If you turn debugging on and send the last few lines. I can have a look at it. 

We can switch to gitter. The is a badge in the readme and it uses github login.

**Comment by npetzall** [comment]
@manishtomar If you still have problem that it gets stuck (we have an issue for a progressbar, I've started on one, but the code doesn't let me add it quickly) open a new issue. But depending on the size of the database it can take minutes to analyze.

**Comment by manishtomar** [comment]
Hey @npetzall Thanks for all the help. Sorry I lost track of this one. Fortunately the need to generate schema didn't exist anymore. So I am not sure what was the problem.

**Comment by npetzall** [comment]
We'll drop it for now. But I'm guessing it was just slow. And it can multiple times slower when `-s` and `-cat` are not used.

We have progressbar in the pipeline and also a refactor for 7.0.0 that hopefully will change how and if `-s` and `-cat` are needed.

**Comment by jflambert** [comment]
>The reflective warning is Java 9 and related to a library we might drop, its not actively maintained.

Hi! Any progress on this? Is there a dedicated issue for this warning? 

Is there anything I can install on Ubuntu 18.04 to have this warning go away? I saw something about graphviz but it might be unrelated.

**Comment by npetzall** [comment]
@jflambert for the warning no issue has been created. I can't remember what exactly the warning was about since I wrote not maintained if it's spring it's maintained.

However it's just a warning might be an issue in Java 11 if it's denied. At test would be to use our snapshot build. Since much have been done there. 

Graphviz is not related to the reflection thing. 

If you create a new issue with your output I'll have a look at it.
