### ISSUE TITLE
markdown support in database description

### ISSUE THREAD

**Issue by atsaloli** [schemaspy/schemaspy#408]
It would be nice if we could use markdown in the database description, so we could link to additional documentation for that database/application.  :)

I tried shoving some markdown there (with `-desc` on the command line) just to see if that was supported, but it just passes through, I see raw Markdown in the HTML report.

**Comment by atsaloli** [comment]
I tried shoving some HTML in there also, but that didn't work.  :)

**Comment by npetzall** [comment]
Both options are possible, for MD we need to run it thru the processor, pretty easy.
To allow HTML is even easier since we just need to inform mustache to not escape html.

@rafalkasa Which solution might be best? The main index page is written last so any links to referenced page should work, i think if going the markdown path. Just having triple `{}` solves the HTML use-case.

**Comment by atsaloli** [comment]
Lovely, thank you, @npetzall .  Continue.  :)   

I am falling in love with SchemaSpy...

**Comment by npetzall** [comment]
@atsaloli what you you prefere markdown or not escaping html?

**Comment by rafalkasa** [comment]
@npetzall I would prefer to stay with Markdown as the additional description content syntax

**Comment by npetzall** [comment]
Actually when I saw reply from @atsaloli I thought the same thing and it might be easier to supply on command line or if we were to add it in the schema meta.

**Comment by rafalkasa** [comment]
@atsaloli for now SchemaSpy is supporting Markdown syntax for tables and columns descriptions look here http://schemaspy.org/sample/tables/Invoice.html. Do you want to have Markdown syntax also for database description, are you ?

**Comment by rafalkasa** [comment]
In addition to Markdown syntax is also possible to add links to the tables and columns using [Table] or [Table.Column] in comments.

**Comment by npetzall** [comment]
@rafalkasa as he is using `-desc` I assume that is the case, but now I'm a bit confused aren't we setting the description in html title?

**Comment by rafalkasa** [comment]
Ok I don't remember but for -desc option only HTML is available :-)

**Comment by atsaloli** [comment]
Okay.  I tried putting links inside -desc but it didn't work.  (Using 6.0.1-SNAPSHOT).  That's okay, it's not a must-have.  :)  We're fine with what we have.  Thanks a million.

**Comment by atsaloli** [comment]
I was trying to do something like 

```
-desc "<a href=www.example.com>Example</a>"
```

**Comment by npetzall** [comment]
PR #429 will allow markdown in `-desc` both [Table] and [Table.Column] links but also external.

Your example would be `-desc "[Example]](www.example.com)"

**Comment by npetzall** [comment]
It's in master PR #429

**Comment by atsaloli** [comment]
Phenomenal!
