### ISSUE TITLE
generate SVG instead of PNG images

### ISSUE THREAD

**Issue by khera** [schemaspy/schemaspy#41]
All modern browsers will render SVG, and the images will be scalable and zoomable, and have pretty lines and arrows instead of the choppy ones rendered into the PNG images. I would request you consider rendering the images as SVG to take advantage of this. The only issue will be to make reference to the FK/PK images relative to the output directory so it works on a web browser.

**Comment by rafalkasa** [comment]
Hi @khera I would like to share with you that @wkasa have done change in SchemaSpy to generate svg images instead of png. Please check new functionality and let us know what do you think about it?
