### ISSUE TITLE
`-all` flag causes schemaspy to always exit non-zero code

### ISSUE THREAD

**Issue by kjvalencik** [schemaspy/schemaspy#42]
`class Main` looks for a non-`null` return value to determine exit code.

```java
rc = analyzer.analyze(new Config(argv)) == null ? 1 : 0;
```
https://github.com/schemaspy/schemaspy/blob/aff3fb5e87731e6189cbf050b2f9470bf907d57c/src/main/java/org/schemaspy/Main.java#L52

However, when using the `-all` flag to analyze multiple schemas, `null` is *always* returned regardless of success.

https://github.com/schemaspy/schemaspy/blob/aff3fb5e87731e6189cbf050b2f9470bf907d57c/src/main/java/org/schemaspy/SchemaAnalyzer.java#L135
https://github.com/schemaspy/schemaspy/blob/aff3fb5e87731e6189cbf050b2f9470bf907d57c/src/main/java/org/schemaspy/SchemaAnalyzer.java#L186

This makes it difficult determine if schema generation was successful within CI.

**Comment by rafalkasa** [comment]
In my opinion after the @wkasa PR merged to the master SchemaSpy should work correctly.
Please check and let me know, if working as it should close the issue.

**Comment by kjvalencik** [comment]
This did not resolve the issue. The code that I linked causes the exit code to always be `1` when supplying the `-all` flag.

**Comment by wkasa** [comment]
@kjvalencik You are right, my previous commit fixed different bug, which i founded trying to resolve this one. ok then, let me look on this one more time.

**Comment by rafalkasa** [comment]
@wkasa thank you for your contribution as we discussed your previous PR according to other issue. @kjvalencik this small change should right now resolve your problem.

**Comment by kjvalencik** [comment]
Validated fixed.
