### ISSUE TITLE
when reading properties files, the values should have "trim()" performed.

### ISSUE THREAD

**Issue by windbender** [schemaspy/schemaspy#421]
I had a few extra spaces at the end of a line in a properties file.  These spaces made it into the String used for the database name.  So of course the database didn't connected.

## Expected Behavior

before values in the properties file are used they should have "trim()" run on them to ensure that extra trailing spaces are removed.

## Current Behavior

spaces at the end of a line are carried through into the code and cause unexpected behavior

**Comment by npetzall** [comment]
It's in master #423
