### ISSUE TITLE
Oracle: selectRowCountSql does not work

### ISSUE THREAD

**Issue by karlkauc** [schemaspy/schemaspy#431]
I am working on a Oracle Database. 
But I get a lot of erros "ORA-00942: table or view does not exist". 

In the ora.properties file the selectRowCountSql is:
`selectRowCountSql=select table_rows row_count from information_schema.tables where table_name=:table `

Unfortunaly Oracle DB does not provide a Information Schema. 
See: [Wikipedia](https://en.wikipedia.org/wiki/Information_schema)

> RDBMSs which do not support information_schema include:
> 
> - Oracle Database
> - IBM DB2
> - SQLite
> - Sybase ASE

For Oracle this should work:
`selectRowCountSql=SELECT NUM_ROWS as row_count FROM ALL_TABLES WHERE TABLE_NAME = :table AND owner = :owner `

**Comment by npetzall** [comment]
For now you can do a workaround by creating your own databaseType https://schemaspy.readthedocs.io/en/latest/started.html#create-your-own-db-type
So you can override the sql I'll have closer look when I get the time.

**Comment by npetzall** [comment]
@karlkauc Just to check which version of SchemaSpy are you using?

We should fix this, but you shouldn't see any exception if your running 6.0.0 or 6.0.1-SNAPSHOT

**Comment by karlkauc** [comment]
Thank you. 
I always run apps with -debug to see the log output. :smiley:

**Comment by npetzall** [comment]
Always is a strong word. But then again you found something to improve.

**Comment by npetzall** [comment]
Thanks for the PR.
