### ISSUE TITLE
schemaspy 6.0.0 with -all parameter in informix

### ISSUE THREAD

**Issue by war1832** [schemaspy/schemaspy#436]
When he launched the schemaspy program with the -all parameter he does not perform the analysis.

## Expected Behavior

Generate analysis for all owners 

## Current Behavior

always throws the same exception 
## Steps to Reproduce (for bugs)

java -jar .\schemaspy-6.0.0.jar -t informix -host IP -port PORT -db DATABASENAE -server SERVER -u USER -p PASS -all -o .\DB_Documentation\ -dp .\libs\driver\ifxjdbc.jar -gv .\libs\graphviz\

## Output

  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESA011 with PID 18924 (C:\schemaspy\schemaspy-6.0.0.jar started by eechevar in C:\schemaspy)
INFO  - The following profiles are active: default
INFO  - Started Main in 5.195 seconds (JVM running for 7.434)
INFO  - Configuration file not found
INFO  - Analyzing schemas that match regular expression '.*'. (use -schemaSpec on command line or in .properties to exclude other schemas)
INFO  - Analyzing schemas: 
owner1
owner2
owner3
owner4
owner5
INFO  - Analyzing owner1
INFO  - Starting schema analysis

Missing required connection parameters for 'informix':
INFO  - InformixSQL
INFO  -    -host   		host of database, may contain port
INFO  -    -port   		optional port if not default
INFO  -    -db   		database name
INFO  -    -server   		database server

You can use your own database types by specifying the filespec of a .properties file with -t.
Grab one out of /C:/schemaspy/schemaspy-6.0.0.jar and modify it to suit your needs.

Sample usage using the default database type (implied -t ora):
 java -jar schemaSpy.jar -db mydb -s myschema -u devuser -p password -o output
 
## Context

* Database type (e.g. MySQL): Informix 11.70.FC8
* Database driver version (is you use a special one): JDBC.3.70.JC8.tar

## Your Environment

* Version used: 6.0.0
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10): Windows 10
* Java version: 1.8.0_181

**Comment by war1832** [comment]
### OUTPUT

  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESA011 with PID 20096 (C:\schemaspy\schemaspy-6.0.0.jar started by eechevar in C:\schemaspy)
INFO  - The following profiles are active: default
INFO  - Started Main in 5.735 seconds (JVM running for 7.822)
DEBUG - Debug enabled
INFO  - Configuration file not found
DEBUG - Resolving dbType: informix ->
	/C:/schemaspy/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/informix.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'SERVER:PORT' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'DATABASENAME' description: 'database name'
DEBUG - DbSpecificOption name: 'server' value: 'SERVER' description: 'database server'
INFO  - Analyzing schemas that match regular expression '.*'. (use -schemaSpec on command line or in .properties to exclude other schemas)
DEBUG - Including schema owner1: matches + ".*" and contains tables
DEBUG - Including schema owner2: matches + ".*" and contains tables
DEBUG - Including schema owner3: matches + ".*" and contains tables
DEBUG - Including schema owner4: matches + ".*" and contains tables
DEBUG - Including schema owner5: matches + ".*" and contains tables
INFO  - Analyzing schemas: 
owner1
owner2
owner3
owner4
owner5
INFO  - Analyzing owner1
INFO  - Starting schema analysis
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'IP:PORT' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'DATABASENAME' description: 'database name'

Missing required connection parameters for 'informix':
INFO  - InformixSQL
INFO  -    -host   		host of database, may contain port
INFO  -    -port   		optional port if not default
INFO  -    -db   		database name
INFO  -    -server   		database server

You can use your own database types by specifying the filespec of a .properties file with -t.
Grab one out of /C:/schemaspy/schemaspy-6.0.0.jar and modify it to suit your needs.

Sample usage using the default database type (implied -t ora):
 java -jar schemaSpy.jar -db mydb -s myschema -u devuser -p password -o output

**Comment by npetzall** [comment]
That was a huge let down, was expecting a stacktrace. I'll look into this right now.

**Comment by npetzall** [comment]
I think I've found the problem.

**Comment by war1832** [comment]
Great, thank you very much for the quick response!
Do you plan to include in the next version?

**Comment by npetzall** [comment]
Yeah, I hope to get it in tonight.
So you'll be able to download SchemaSpy-6.0.1-SNAPSHOT and use that.
There's a link in the readme.

But I just need to test that I don't break anything else =)

**Comment by npetzall** [comment]
Thought it would be in by now, but Travis-ci is having trouble with oracle-java-installation.

**Comment by npetzall** [comment]
You should be able to use the snapshot at [Snapshot](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.1-SNAPSHOT.jar)
