### ISSUE TITLE
Possibility to infer the foreign key based on primary key and column names

### ISSUE THREAD

**Issue by Niradnik** [schemaspy/schemaspy#443]
Hello all,

Thanks for your app, after reading a bit the documentations and the issues I didn't found mention of the possibility to infer the foreign key based on the primary key and column names.
Like if in table1 I have the id_table1 as PK and in table 2 and 3 I have a column named id_table1. If the column name id_table1 is always referencing the PK of the table 1, then the id_table1 of other tables are always the FK. 

So is it possible ?

I think that would be useful as the views on Postgresql can have PK but no FK so it would be cool at least for this case to have this ability.
Plus sometimes FK are slowing process and so we would prefer to don't set them.

Have a great day !

[Edit] 
I read too fast Postgresql seems to doesn't support constraint at all in the view.

**Comment by npetzall** [comment]
Hi, we have what we call implied relationships. Unsure if they only show in the graphs. The sample doesn't seem to have them so need to run one of the test for it.

I'll have to double check I don't think we check implied on views.

There's also an open issue related to implied. That if the PK exist in two tables the implied relationship will be skipped.

**Comment by npetzall** [comment]
It will show implied as parents and children in table page.
It doesn't seem to exclude views when computing implied relationship.
So try it out and if you have an issue. Create a sample database that shows the problem and post it here and I'll investigate the issue.

**Comment by Niradnik** [comment]
Hello, thanks for the fast answer !!
I saw the other issue related and was hopping it was what I was looking for but wasn't sure..
Thanks for clarifying it !

**Comment by npetzall** [comment]
@Niradnik Have you had the time to try schemaspy out? Are there any outstanding issues? Can this be closed?

Yeah, I think composite keys aren't (yet?) implemented when it comes to implied/inferred relationships.

**Comment by npetzall** [comment]
@Niradnik ok to close?
