### ISSUE TITLE
Routines documentation for Postgres 10.2

### ISSUE THREAD

**Issue by petrheckoHims** [schemaspy/schemaspy#444]
## Expected Behavior

As per the [sample output](http://schemaspy.org/sample/index.html), I see the routines output is visible. I was hoping to see routines when using SchemaSpy on our Postgres 10.2 DB as well. I could not find any specific flag I should add in order to get the routines displayed. Am I missing anything or are routines not supported yet for Postgres?

## Current Behavior

When running SchemaSpy on our Postgres DB, all works fine except the routines - routines shows 0, however we have hundreds of them in place.

## Context

* Database type (e.g. MySQL): `Postgres 10.2`
* Database driver version (is you use a special one): `postgresql-42.2.5.jar`
* Full command including arguments how you run SchemaSpy: `java -jar schemaspy-6.0.0.jar -all`

## Your Environment

* Version used: `6.0.0`
* Environment name and version (e.g. Chrome 39): `Chrome Version 69.0.3497.100 (Official Build)`
* Operating System and version (e.g. Windows 10): OSx High Sierra
* Java version: `1.8.0_181`
* `schemaspy.properties` file:
```
# type of database. Run with -dbhelp for details
schemaspy.t=pgsql
# optional path to alternative jdbc drivers.
schemaspy.dp=./postgresql-42.2.5.jar
# database properties: host, port number, name user, password
schemaspy.host=localhost.aptible.in
schemaspy.port=${PORT}
schemaspy.db=db
schemaspy.u=${UNAME}
schemaspy.p=${PWD}
# output dir to save generated files
schemaspy.o=./output
# db scheme for which generate diagrams
#schemaspy.s=dbo
```

**Comment by npetzall** [comment]
This has been added after 6.0.0 was release there is a latest/snapshot link in the readme.md try that. If still doesn't work let me know.

We are talking about releasing 6.0.1 next weekend.

**Comment by npetzall** [comment]
Possible duplicate #395

**Comment by petrheckoHims** [comment]
Thanks a lot @npetzall . I tried with the snapshot of `6.0.1` and worked great! Thanks again.
