### ISSUE TITLE
Fields that contain characters like ">" cause errors in dot

### ISSUE THREAD

**Issue by flann** [schemaspy/schemaspy#447]
I have some views with field names that contain ">" (e.g. "> 180"). This causes some errors in dot:

[schemaspy_output.log](https://github.com/schemaspy/schemaspy/files/2529968/schemaspy_output.log)

Sample output in relationships.implied.large.dot that causes the error:

<TR><TD PORT="> 180" COLSPAN="3" ALIGN="LEFT"><TABLE BORDER="0" CELLSPACING="0" ALIGN="LEFT"><TR ALIGN="LEFT"><TD ALIGN="LEFT" FIXEDSIZE="TRUE" WIDTH="15" HEIGHT="16"></TD><TD ALIGN="LEFT" FIXEDSIZE="TRUE" WIDTH="104" HEIGHT="16">> 180</TD></TR></TABLE></TD></TR>

## Expected Behavior

Special characters should be escaped (e.g. with ampersand codes?) so that it doesn't cause errors in dot.

## Current Behavior

dot throws errors similar to the one above.

## Possible Solution

Escape special characters with ampersand codes? Not sure if dot would handle those better.

## Steps to Reproduce (for bugs)

1. Create a postgresql view with a field that contains a ">" (or probably "<" - haven't tried that)
2. Run schemaspy against the database
3. Observe errors like those above.
4.

## Context

I'm able to open the relationship diagrams, but they appear to be incomplete.

* Database type (e.g. MySQL): PostgreSQL 9.5
* Database driver version (is you use a special one): postgresql-9.4.1208.jar
* Your DDL (sample how to reproduce the issue): 

-- Not exactly what I have, but this should be all it takes to reproduce the issue:

CREATE OR REPLACE VIEW public.my_view AS
    SELECT some_number AS "> 180"
    FROM my_table
    WHERE some_number > 180;

* Full command including arguments how you run SchemaSpy:

%JAVA% -jar "C:\SchemaSpy\schemaspy-6.0.0.jar" -dp "C:\SchemaSpy\postgresql-9.4.1208.jar" -t pgsql -host 127.0.0.1 -port 5432 -db my_database -s public -u my_user -pfp -noads -nologo -o %siteDir%

## Your Environment

* Version used: 6.0.0 and 6.0.1-SNAPSHOT (downloaded 10/30/2018)
* Environment name and version (e.g. Chrome 39): Chrome 70.0.3538.77 (Official Build) (64-bit) (NOTE: issue occurs before opening in Chrome)
* Operating System and version (e.g. Windows 10): 64-bit Windows 10 Version 1703 (OS Build 15063.1324)
* Java version: JRE 1.8.0_191 (64-bit)

**Comment by npetzall** [comment]
I'll test this tonight might be a quoting issue.

**Comment by flann** [comment]
Sorry the sample output should've been from a file.  It doesn't look right above.
Here it is:

[relationships.implied.large - excerpt.dot.log](https://github.com/schemaspy/schemaspy/files/2530136/relationships.implied.large.-.excerpt.dot.log)

**Comment by flann** [comment]
Hi, Nils, does the attachment I just posted give you what you need?

**Comment by npetzall** [comment]
Nice thanks, I think that it should be html encoded, need to check the dot-Lang docs. I'll try to fix it tonight.

**Comment by flann** [comment]
Cool! Thanks!

**Comment by npetzall** [comment]
This is bow available in snapshot/latest that can be downloaded from the readme.md

**Comment by flann** [comment]
Confirmed no more issues with my postgres database. Thanks for your amazingly quick fix, Nils!
