### ISSUE TITLE
ERROR - null with no stack trace

### ISSUE THREAD

**Issue by AndreKR** [schemaspy/schemaspy#457]
This can be reproduced in the `openjdk:8-alpine` Docker container using these commands:

```shell
docker run -it openjdk:8-alpine
```

```shell
# Set up a local mysql (skip if you have a MySQL reachable somewhere)
apk update
apk add mysql mysql-client graphviz
mysql_install_db --user=mysql
mysqld_safe --nowatch

# Install SchemaSpy
wget https://github.com/schemaspy/schemaspy/releases/download/v6.0.0/schemaspy-6.0.0.jar
wget https://cdn.mysql.com//Downloads/Connector-J/mysql-connector-java-8.0.13.tar.gz
mv mysql-connector-java-8.0.13/mysql-connector-java-8.0.13.jar .
tar xzf mysql-connector-java-8.0.13.tar.gz

# Run SchemaSpy
java -jar schemaspy-6.0.0.jar -t mysql -dp mysql-connector-java-8.0.13.jar -db mysql -s mysql -host localhost -port 3306 -u root -o output
```

Output:
```text
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on cae05b0ae8a1 with PID 731 (/schemaspy-6.0.0.jar started by root in /)
INFO  - The following profiles are active: default
INFO  - Started Main in 4.72 seconds (JVM running for 6.202)
INFO  - Configuration file not found
INFO  - Starting schema analysis
INFO  - Connected to MySQL - 5.5.5-10.2.15-MariaDB-log
INFO  - Gathering schema details
Gathering schema details.................................(1sec)
Connecting relationships.................................(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
..ERROR - null
```

Same thing happens with a PostgreSQL database, so it's probably not related to the database connection.

There *are* files in the output directory afterwards.

**Comment by npetzall** [comment]
You can add `-debug` to commandline to get stacktrace. Also we have a baked docker image.

**Comment by AndreKR** [comment]
Ah, thanks. With the stacktrace I quickly found out that this issue was related to the `fontconfig` package missing.

**Comment by npetzall** [comment]
I suspected something with font, but we've had issue with changes I java updates that's why our docker is pinned to a specific Java update.

**Comment by npetzall** [comment]
I've been thinking of adding a flag, if any exception has been thrown, before exiting it can print. 

"There were exceptions during execution of SchemaSpy. To print stacktrace append `-debug` to command line"

I've only seen fontconfig as an issue on Alpine and I'm pretty sure there's a limited amount of users that has either alpine or busybox as their operating system, so I believe it would be really specific code which will just be a maintenance cost. I might still be very wrong.

As for building a docker image, are we missing anything in our docker image. It's published on docker-hub we have both snapshot which is most recent green build of master. Latest which points to 6.0.0 and also a 6.0.0 tagged image.

**Comment by AndreKR** [comment]
> I've been thinking of adding a flag, if any exception has been thrown, before exiting it can print.
> 
> "There were exceptions during execution of SchemaSpy. To print stacktrace append `-debug` to command line"

That's a very good idea, much better than catching only this particular case. (If you don't want to *always* show the stacktrace in case of an error, which I think would also be acceptable.)

> As for building a docker image, are we missing anything in our docker image.

No, nothing missed, I copied my missing font stuff from your Dockerfile and it was super helpful.

I'm running this on CI. I'm using a Docker image that already contains the database and I just download SchemaSpy onto it and run it.

If I wanted to use your Docker image instead, I would need a way to get my database onto it and I'm not sure how to go about that.

**Comment by npetzall** [comment]
It shouldn't be a problem. Just have your database container running, start the schemaspy container use the db container name as host. I believe that linking has been removed from docker and that containers on the same network (unsure if this is actually true for bridge) can resolve each other using the container name.

Just make sure to mount the output dir or use docker copy to get the report out of the container.
