### ISSUE TITLE
Links from Columns page back to appropriate table page

### ISSUE THREAD

**Issue by bwbecker** [schemaspy/schemaspy#464]
## Expected Behavior

Just upgraded from SchemaSpy 5.0.0 to 6.0.0.  Thanks for the many improvements!

One issue is that the columns page doesn't contain navigation links back to the page for the table.  V5.0.0 had that; I miss it.  Confirmed that it's not in the sample documentation, either, so I don't think it's my set-up.

## Steps to Reproduce (for bugs)

1. Generate data for a schema.
2. Go to the <schema>/columns.html page
3. Find a relevant column name.  Look for a convenient way to navigate to the table containing that column.

## Context

* Database type (e.g. MySQL):  postgresql
* Database driver version (is you use a special one):  
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

```
java -jar schemaspy-6.0.0.jar -t pgsql-matviews -vizjs \
	-gv /usr/local/Cellar/graphviz/2.40.1/ \
    -db $db -u $userid -o ~/temp/schemaspy/ \
    -host $host \
    -connprops "ssl\=true;sslfactory\=org.postgresql.ssl.NonValidatingFactory" \
    -p $password \
    -nopages \
    -schemas "_quest_raw,_oat" #-I ".*history" \
```

```
description=PostgreSQL
connectionSpec=jdbc:postgresql://<hostOptionalPort>/<db>
host=host where database resides with optional port
port=port database is listening on
db=database name

driver=org.postgresql.Driver
driverPath=xxxxxxx/org.postgresql/postgresql/bundles/postgresql-42.2.2.jar

# return text that represents a specific :view / :schema
selectViewSql=select definition as view_definition from pg_views where viewname = :table UNION select definition as view_definition from pg_matviews where matviewname = :table

selectSchemasSql=SELECT nspname AS schema_name, pg_catalog.obj_description(oid, 'pg_namespace') AS schema_comment FROM pg_catalog.pg_namespace where nspname = :schema
selectCatalogsSql=SELECT datname AS catalog_name, pg_catalog.obj_description(datlastsysoid, 'pg_database') AS catalog_comment FROM pg_catalog.pg_database WHERE datname = :catalog ;
# selectTablesSql=select table_schema as table_catalog, null as table_schema, table_name, table_comment, table_rows from information_schema.tables where table_schema=:schema and table_type='BASE TABLE'

viewTypes=VIEW,MATERIALIZED VIEW
```

## Your Environment

* Version used:  SchemaSpa 6.0.0
* Environment name and version (e.g. Chrome 39):  
* Operating System and version (e.g. Windows 10):  MacOS Mojave
* Java version:  java version "1.8.0_121"

**Comment by npetzall** [comment]
This is a must have, I'll get right on it.

**Comment by npetzall** [comment]
Added so first column is a link. Please re-open if not good enough.
You can tries this out by downloading and using the snapshot build that will be finished in about 10 mins. You can find the link in the readme.md

**Comment by bwbecker** [comment]
Perfect!  Thanks so much for the super-quick response!
