### ISSUE TITLE
Usar Autenticação do Windows no Schemaspy

### ISSUE THREAD

**Issue by ddorneles** [schemaspy/schemaspy#472]
Boa tarde,

Estou querendo usar o método de autenticação do windows com o Schemaspy, porem sem sucesso.
Os códigos que estou usando são:
**Assim da certo sem problemas, informando usuário e senha do banco:** 
java -jar C:\schemaspy\schemaspy.jar -t mssql08 -host sv43051 -port 1433 -db meubanco -u sa -p senha -o c:\temp\sv43051 -dp C:\schemaspy\sqljdbc_6.0\enu\jre8\sqljdbc42.jar

Porem não queremos usar o usuário e senha do banco e sim usar a Autenticação do Windows para o mesmo, abaixo segue linhas de comando que já tentamos executar porem sem sucesso.

**Código que tentamos executar:**
java -Djava.library.path=C:\schemaspy\Diogo\sqljdbc_6.0\enu\auth\x86\sqljdbc_auth.dll -jar C:\schemaspy\schemaspy.jar -t mssql08 -host sv43051 -port 1433 -db meubanco -sso -o c:\temp\sv43051 -dp C:\schemaspy\sqljdbc_6.0\enu\jre8\sqljdbc42.jar

Porem não conecta de jeito nenhum, como devemos ajustar o código para que funcione.

Ficamos no aguardo.
![capturar](https://user-images.githubusercontent.com/45398503/49096631-16e2c300-f252-11e8-9069-e8d654e5f6f6.JPG)

**Comment by npetzall** [comment]
Hi could you add `-debug` and supply output.

**Comment by ddorneles** [comment]
> Oi você poderia adicionar `-debug`e fornecer saída.

Good Morning "NPETZALL",

I do not understand your placement because what I want to do is to use windows authentication for schemaspy.

I'm waiting.

**Comment by ddorneles** [comment]
Good Morning,

Follow screen ...
![debug](https://user-images.githubusercontent.com/45398503/49153052-bdcf6980-f2fb-11e8-8f42-de64db3f5b56.JPG)

Thank you

**Comment by npetzall** [comment]
`java -Djava.library.path=C:\schemaspy\Diogo\sqljdbc_6.0\enu\auth\x86\sqljdbc_auth.dll -jar C:\schemaspy\schemaspy.jar -t mssql08 -host sv43051 -port 1433 -db meubanco -sso -o c:\temp\sv43051 -dp C:\schemaspy\sqljdbc_6.0\enu\jre8\sqljdbc42.jar -connprops integratedSecurity\\=true`

It would probably be good to include schema `-s dbo` and catalog `-cat "%"`

**Comment by ddorneles** [comment]
> `java -Djava.library.path=C:\schemaspy\Diogo\sqljdbc_6.0\enu\auth\x86\sqljdbc_auth.dll -jar C:\schemaspy\schemaspy.jar -t mssql08 -host sv43051 -port 1433 -db meubanco -sso -o c:\temp\sv43051 -dp C:\schemaspy\sqljdbc_6.0\enu\jre8\sqljdbc42.jar -connprops integratedSecurity\\=true`
> 
> It would probably be good to include schema `-s dbo` and catalog `-cat "%"`

Thank you very much.
It worked, it did.
Thanks again.

**Comment by npetzall** [comment]
@rafalkasa What do you think about extending the SSO support.

Add property to databaseType like
`sso.connprop.integratedSecurity=true`

And when `-sso` is used it will fetch all sso.connprop.* use the last part as prop key and value as well value.

It feels somewhat better than adding mssql-sso, mssql05-sso, mssql08-sso, mssql-instance-sso, mssql05-instance-sso, mssql08-instance-sso and we already have the `-sso` argument.

I wonder if this is just because the `-connprops key\\=value` is akward and hard to explain.

The mssql-instance-sso could be replaced with `-connprops instance\\=[instance];integratedSecurity\\=true`

**Comment by ddorneles** [comment]
> @rafalkasa What do you think about extending the SSO support.
> 
> Add property to databaseType like
> `sso.connprop.integratedSecurity=true`
> 
> And when `-sso` is used it will fetch all sso.connprop.* use the last part as prop key and value as well value.
> 
> It feels somewhat better than adding mssql-sso, mssql05-sso, mssql08-sso, mssql-instance-sso, mssql05-instance-sso, mssql08-instance-sso and we already have the `-sso` argument.
> 
> I wonder if this is just because the `-connprops key\\=value` is akward and hard to explain.
> 
> The mssql-instance-sso could be replaced with `-connprops instance\\=[instance];integratedSecurity\\=true`

Good Morning
I did not understand much what you wanted to tell me.
Awaiting.

**Comment by npetzall** [comment]
@ddorneles it was a question to rafalkasa if we should implement better support for `-sso`

**Comment by rafalkasa** [comment]
@npetzall maybe before changes in code will be better to prepare documentation and try to describe how use SchemaSpy with -sso  and IntegratedSecurity. I also had some issue in the past when I try to do the same :smile:
