### ISSUE TITLE
Orphan Tables

### ISSUE THREAD

**Issue by alasdairdc** [schemaspy/schemaspy#48]
Tested using `schemaspy-6.0.0-beta.3.jar`

- Textual inconsistency
    - Navigation menus refers to it as `Orphan Tables`
    - Page heading refers to it as `Orphans Tables`
- ~Views~
    - ~Should this really be listing the views? (MySQL, not tested on other DB engines).~ Mentioned in #39 

Great job so far guys, glad somethings being done.

**Comment by rafalkasa** [comment]
@alasdairdc Textual inconsistency will be fixed. All Views will be excluded from Orphan Tables page.
