### ISSUE TITLE
Hide row count when "-norows" is specified

### ISSUE THREAD

**Issue by zam6ak** [schemaspy/schemaspy#486]
When using `-norows` option:

1) in Tables view, column Rows shows either `-1` or `0`
2) in Table detail view, following shows below paginator label
```
Showing 1 to 10 of 13 entries
Table contained -1 rows
```

It would probably be best to omit/remove this entry all thogether when -norows is specified.
for 1, just show empty space since 0 rows is not same as "-norows was specified" 
for 2, remove the label "Table contained -1 rows" (IMHO, it may be be better UX to put row count next to table name in header rather than at the bottom of column list but...)

---
Tested using:

* DB:        PostgreSQL v11
* Driver:    [PostgreSQL JDBC 4.2 Driver, 42.2.5](https://jdbc.postgresql.org/download/postgresql-42.2.5.jar)
* Schemaspy: [schemaspy-6.1.0-SNAPSHOT](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.1.0-SNAPSHOT.jar)
* Sample DB: [DVD Rental](http://www.postgresqltutorial.com/postgresql-sample-database/)
* Java ver:  1.8

**Comment by npetzall** [comment]
1, I removed the column.

2, @zam6ak  What do you think about 
![image](https://user-images.githubusercontent.com/4175123/51573315-0f821380-1ea9-11e9-8507-6ad5e1465ecb.png)

Rows immediately under the table name when shown. The one under the table with column is removed.
And I'll just have to make it conditional and update like a million tests. I need to fix this end to end tests thing it's horrible.

**Comment by zam6ak** [comment]
Looks good @npetzall  !!!
