### ISSUE TITLE
-dbhlep should provide information for database-type

### ISSUE THREAD

**Issue by mh182** [schemaspy/schemaspy#494]
I tried to call SchemaSpy against a PostgreSQL database and got stuck in the first few minutes. The "Get Started" section in the documentation starts with the configuration example for `mssql` with the hint to call `-dbehlp` for details. But calling SchemaSpy with the option does not provide the option needed for the `-database-type` (this is already mentioned in issue #415).

It toke me a half hour to find an example somewhere to see how PostgreSQL is called.

## Expected Behavior
Show the value needed for option `-t`:
```
java -jar schemaspy-6.0.0.jar -dbhelp
...
INFO  - Built-in database types and their required connection parameters:
INFO  - IBM DB2 with the 'App' Driver
INFO  -    -db                  database name
...
INFO  - PostgreSQL
INFO  -    -database-type      'psql' 
INFO  -    -host                host of database, may contain port
INFO  -    -port                optional port if not default
INFO  -    -db                  database name
```

## Current Behavior
```
java -jar schemaspy-6.0.0.jar -dbhelp
...
INFO  - Built-in database types and their required connection parameters:
INFO  - IBM DB2 with the 'App' Driver
INFO  -    -db                  database name
...
INFO  - PostgreSQL
INFO  -    -host                host of database, may contain port
INFO  -    -port                optional port if not default
INFO  -    -db                  database name
```

**Comment by npetzall** [comment]
This has been fixed in #469 and #477

You'll get more or less expected behavior in 6.1.0-SNAPSHOT which can be downloaded  from readme.

**Comment by mh182** [comment]
OK, sorry I could'nt find the issue mentioned above.

**Comment by npetzall** [comment]
Sorry for that I think I forgot to link issues in the pull requests. It was only mentioned in two issues that weren't specifically for the dbhelp output.
