### ISSUE TITLE
Invalid query on upper case table names

### ISSUE THREAD

**Issue by afonso360** [schemaspy/schemaspy#495]
Schema spy tries to execute some invalid queries when using PostgreSQL and Upper case names

This is not a fatal issue, we still get the exported database documentation. The row count on the first page seems to be correct.

PostgreSQL log:
```
ERROR:  relation "dbo.contact" does not exist at character 22
STATEMENT:  select count(*) from dbo.Contact
ERROR:  relation "dbo.group" does not exist at character 15
STATEMENT:  select * from dbo.Group where 0 = 1
```
The correct query should be something like: `select count(*) from dbo."Contact"`
possibly even quoting the schema name.

Docker hub image 6.1.0-SNAPSHOT
PostgreSQL 9.6.11

**Comment by npetzall** [comment]
Hi

Need to double check it mig be a ok error and then it shouldn't be logged or include information. That we will retry a cpl of times with quotation and also count(*) and count(1) might also exist override in dbtype for the count. So I'll have a look at it.

**Comment by npetzall** [comment]
Now I see. It's errors in PostgreSQL and not in SchemaSpy.

Which corresponds to the code I'm looking at
1, First it will try to use JDBCMetaData, if that doesn't contain row_count.
2, It will then check for a custom sql (not defined for pgsql) and use it
3a, select count(*) everything un-quoted unless quotation is needed.
3b, select count(*) everything quoted
4a, select count(1) everything un-quoted unless quotation is needed.
4b, select count(1) everything quoted

If everything failes you'll get 2-3 warning depending on custom query.
If you get no errors/warnings in schemaspy one of the above methods has worked.
