### ISSUE TITLE
WARN  - Failed to query Graphviz graphvizVersion information

### ISSUE THREAD

**Issue by sunilsql** [schemaspy/schemaspy#498]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Database type (e.g. MySQL):
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):
* Java version:

**Comment by npetzall** [comment]
With this minimal information.

1, Graphviz might not be installed, install it
2, Graphviz is not in your path, use `-gv` argument to set path to graphviz or add graphviz to your os path

To get java stacktrace information on the problem. You can add `-debug` to command-line.

**Comment by sunilsql** [comment]
Hello,

I am using the following command, please check

Command: java -jar schemaspy-6.0.0.jar -t mssql05-jtds -host
DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -u test -p test -s
dbo -o E:\ -gv E:\Graphviz2.38

Result: I didn't get full database info in HTML, got some tables and
columns.

Using MSSQL 2017

Error:

E:\>java -jar schemaspy-6.0.0.jar -t mssql05-jtds -host DESKTOP-SM37531
-port 1433 -db AdventureWorks2016CTP3 -u test -p test -s dbo -o E:\ -gv
E:\Graphviz2.38
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's
relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of
LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESKTOP-SM37531 with PID 10604
(E:\schemaspy-6.0.0.jar started by sunil in E:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.67 seconds (JVM running for 2.235)
INFO  - Configuration file not found
INFO  - Starting schema analysis

WARN  - Failed to query Graphviz graphvizVersion information
WARN  -   with: E:\Graphviz2.38\bin\dot -V
WARN  -   {}
INFO  - Graphviz query failure details:
INFO  - Connected to Microsoft SQL Server - 13.00.4224
INFO  - Gathering schema details
Gathering schema details......(0sec)
Connecting relationships......(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
.INFO  - Using external StyleSheet file: schemaSpy.css
.
Warning: Failed to run dot.
   Download dot graphvizVersion 2.26 or versions greater than 2.31
   from www.graphviz.org and make sure that dot is either in your path
   or point to where you installed Graphviz with the -gv option.
   Generated pages will not contain a diagramtic view of table
relationships.
......(1sec)
Writing/diagramming detailsINFO  - Completed summary in 1 seconds
INFO  - Writing/diagramming details
...(0sec)
Wrote relationship details of 3 tables/views to directory 'E:\' in 2
seconds.
View the results by opening E:\index.html
INFO  - Wrote table details in 0 seconds
INFO  - Wrote relationship details of 3 tables/views to directory 'E:\' in
2 seconds.
INFO  - View the results by opening E:\index.html

**Comment by npetzall** [comment]
Does a dot.exe exist in `E:\Graphviz2.38\bin`?

**Comment by sunilsql** [comment]
Nw I provided the exact path in command. Sorry about that.

But still, I Couldn't get full DB in HTML.

Command:

java -jar schemaspy-6.0.0.jar -t mssql05-jtds -host DESKTOP-SM37531 -port
1433 -db AdventureWorks2016CTP3 -u test -p test -s dbo -o E:\ -gv
"C:\Program Files (x86)\Graphviz2.38" -debug

Error:


SchemaSpy generates an HTML representation of a database schema's
relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of
LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESKTOP-SM37531 with PID 10840
(E:\schemaspy-6.0.0.jar started by sunil in E:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.727 seconds (JVM running for 2.302)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mssql05-jtds ->

/E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05-jtds.properties
->

/E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql-jtds.properties
->

/E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value:
'DESKTOP-SM37531:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'AdventureWorks2016CTP3'
description: 'database name  '
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: true
DEBUG - Catalog not provided, queried jdbc driver and got
'AdventureWorks2016CTP3'
INFO  - Connected to Microsoft SQL Server - 13.00.4224
INFO  - Gathering schema details
Gathering schema details...DEBUG - Including table AWBuildVersion: matches
inclusion pattern '.*'
DEBUG - Creating Table AdventureWorks2016CTP3.dbo.AWBuildVersion
DEBUG - Querying primary keys for AdventureWorks2016CTP3.dbo.AWBuildVersion
.DEBUG - Retrieved details of AdventureWorks2016CTP3.dbo.AWBuildVersion
DEBUG - Including table DatabaseLog: matches inclusion pattern '.*'
DEBUG - Creating Table AdventureWorks2016CTP3.dbo.DatabaseLog
DEBUG - Querying primary keys for AdventureWorks2016CTP3.dbo.DatabaseLog
.DEBUG - Retrieved details of AdventureWorks2016CTP3.dbo.DatabaseLog
DEBUG - Including table ErrorLog: matches inclusion pattern '.*'
DEBUG - Creating Table AdventureWorks2016CTP3.dbo.ErrorLog
DEBUG - Querying primary keys for AdventureWorks2016CTP3.dbo.ErrorLog
.DEBUG - Retrieved details of AdventureWorks2016CTP3.dbo.ErrorLog
DEBUG - SELECT tbls.name AS table_name, cnstrs.name AS constraint_name,
cmts.text AS text FROM sysobjects cnstrs INNER JOIN sysobjects tbls ON
cnstrs.parent_obj = tbls.id INNER JOIN syscomments cmts ON cmts.id =
cnstrs.id WHERE cnstrs.type = 'C' []
DEBUG - SELECT OBJECT_NAME(t.object_id) AS TABLE_NAME, ex.value AS comments
FROM sys.tables t LEFT OUTER JOIN sys.extended_properties ex ON ex.major_id
= t.object_id AND ex.name = 'MS_Description' AND minor_id = 0 JOIN
sys.schemas s ON t.schema_id = s.schema_id AND s.name = ? WHERE
OBJECTPROPERTY(t.object_id, 'IsMsShipped')=0 ORDER BY
OBJECT_NAME(t.object_id) [dbo]
DEBUG - SELECT OBJECT_NAME(c.object_id) AS TABLE_NAME, c.name AS
COLUMN_NAME, ex.value AS comments FROM sys.columns c LEFT OUTER JOIN
sys.extended_properties ex ON ex.major_id = c.object_id AND ex.minor_id =
c.column_id AND ex.name = 'MS_Description' JOIN sys.tables t ON t.object_id
= c.object_id JOIN sys.schemas s ON t.schema_id = s.schema_id AND s.name =
? WHERE OBJECTPROPERTY(c.object_id, 'IsMsShipped')=0 ORDER BY
OBJECT_NAME(c.object_id), c.column_id  [dbo]
(0sec)
Connecting relationships......(0sec)
Writing/graphing summary.INFO  - Gathered schema details in 0 seconds
INFO  - Writing/graphing summary
.INFO  - Using external StyleSheet file: schemaSpy.css
...DEBUG - C:\Program Files (x86)\Graphviz2.38\bin\dot -Tpng:cairo
E:\diagrams\orphans\AWBuildVersion.1degree.dot
-oE:\diagrams\orphans\AWBuildVersion.1degree.png -Tcmapx
DEBUG - C:\Program Files (x86)\Graphviz2.38\bin\dot -Tpng:cairo
E:\diagrams\orphans\DatabaseLog.1degree.dot
-oE:\diagrams\orphans\DatabaseLog.1degree.png -Tcmapx
DEBUG - C:\Program Files (x86)\Graphviz2.38\bin\dot -Tpng:cairo
E:\diagrams\orphans\ErrorLog.1degree.dot
-oE:\diagrams\orphans\ErrorLog.1degree.png -Tcmapx
.....(2sec)
Writing/diagramming detailsINFO  - Completed summary in 2 seconds
INFO  - Writing/diagramming details
.DEBUG - Writing details for ErrorLog
.DEBUG - Writing details for AWBuildVersion
.DEBUG - Writing details for DatabaseLog
(0sec)
Wrote relationship details of 3 tables/views to directory 'E:\' in 3
seconds.
View the results by opening E:\index.html
INFO  - Wrote table details in 0 seconds
INFO  - Wrote relationship details of 3 tables/views to directory 'E:\' in
3 seconds.
INFO  - View the results by opening E:\index.html

**Comment by npetzall** [comment]
I'm closing this since full database is discussed in the other issue. This is related to graphviz and closed.
