### ISSUE TITLE
Deep linking anchors

### ISSUE THREAD

**Issue by jornh** [schemaspy/schemaspy#50]
Having anchors on the different sections on the pages generated for tables so you could make deep links to e.g. `#relationships` would be very neat :+1:  .... aaand useful too I think.

To not visually clutter up the *very* nice new page UI the anchors could just reveal themselves when you hovered over a section title, similar to the way it works with titles in Markdown text here on Github.

**Comment by rafalkasa** [comment]
Hi @jornh  as I understand your proposition is to have possiblity to create anchors links as below on this page https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#emphasis

Could you prepare some screen shot and explain which section should have such special anchors ?

**Comment by jornh** [comment]
Yes, @rafalkasa :smile: exactly as in https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#emphasis where it opens the page with the linked title scrolled into view.

What triggered the idea in the first place was a need to be able to easily point others to the Relationships section and make sure they see the diagram even for were big tables with a lot of lines in the Columns section. But I'd imagine it would be useful to generalize for all the sections. So this means: On any table page for all the **Description**, **Columns**, **Indexes** and **Relationships** sections.

Looking a bit more at it today there might also be value in being able to link directly to the "Degrees of separation" tabs under . As you can see in the screenshot below there is already a `#oneDegreeImg-chart` and `#twoDegreeImg-chart` fragment used to navigate across the tabs. It's just that it only works for javascript navigation within the page I guess. As you can see a link to http://schemaspy.org/sample/tables/Album.html#twodegreesDegreeImg-chart does not switch to the tab one could expect. But I'll make it up to you if that's worth implementing, hence the question mark on the screen shot below. 

![chinook database - mozilla firefox](https://cloud.githubusercontent.com/assets/766423/24553413/7bb07666-162a-11e7-8b2d-ba880109f1f5.jpg)

**Comment by jornh** [comment]
Just took a quick peek at the sources. (Sorry, couldn't help it)

It turns out `id` attributes to link to for [Columns](https://github.com/schemaspy/schemaspy/blob/v6.0.0-beta.3/src/main/resources/layout/tables/table.html#L28) and [Indexes](https://github.com/schemaspy/schemaspy/blob/v6.0.0-beta.3/src/main/resources/layout/tables/table.html#L100) are already there, so these links built by hand already works:

- http://schemaspy.org/sample/tables/Album.html#Columns 
- http://schemaspy.org/sample/tables/Album.html#Indexes

It's just that they are not consistently applied to all of the `<h3/>` entities, but PR #51 contains a bit of work towards fixing that.

Then with the modification of e.g. https://github.com/schemaspy/schemaspy/blob/v6.0.0-beta.3/src/main/resources/layout/tables/table.html#L100 into 

```
<h3 id="Indexes" class="box-title"><a href="#Indexes">Indexes</a></h3>
```
there is a functional, but admitted ugly, step towards what I'm asking for. Sorry I'm not very good with the CSS or JS to get to the nice link hover effect in https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#emphasis

**Comment by rafalkasa** [comment]
@jornh I would like thank you very much for your very detailed explanation what you understand by "Deep linking anchors". 

I have made some investigation about AnchorJS and this is what we need to have for linking anchors in SchemeSpy. Your help and propositions are very appreciated. I have plan to finish this "Deep linking anchors" feature during the weekend.

**Comment by rafalkasa** [comment]
Haha it was simpler than I thought so it's ready. Enjoy !

**Comment by jornh** [comment]
@rafalkasa thank you *very* much :tada: for a super quick implementation of this. It's already put in to good use on a re-run on the first database here.

**Comment by rafalkasa** [comment]
It's good to know that such small enhancement make you happy :-) Your future ideas are very appreciated
