### ISSUE TITLE
unable to retrieve User schemas

### ISSUE THREAD

**Issue by sunilsql** [schemaspy/schemaspy#500]
Command: java -jar schemaspy-6.0.0.jar -t mssql08-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -u test -p test -all -o E:\adv -gv "C:\Program Files (x86)\Graphviz2.38"

Here I am using all but I got the result of system schemas - Information_schema,  dbo, sys. I am unable to see other schemas.

Someone, please help me for getting user schemas and to exclude system schemas

**Comment by npetzall** [comment]
`-schemaSpec=(?!^information_schema$|sys$).*` mean anything that doesnt match information_schema or sys.

As for missing schemas, can you create a report on them without the `-all` like:
`java -jar schemaspy-6.0.0.jar -t mssql08-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -u test -p test -s HumanResources -o E:\adv -gv "C:\Program Files (x86)\Graphviz2.38"

**Comment by sunilsql** [comment]
Able to create a report for One schema but not for all

**Comment by npetzall** [comment]
I'll try to find a copy of the sample db and have a go at it.

**Comment by sunilsql** [comment]
and also for -Schemaspec this is what I got:

E:\>java -jar schemaspy-6.0.0.jar -t mssql08-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -u test -p test -schemaSpec=(?!^information_schema$|sys$).* -o E:\adv -gv "C:\Program Files (x86)\Graphviz2.38" -debug
'sys$).*' is not recognized as an internal or external command,
operable program or batch file.

**Comment by npetzall** [comment]
That's related to your terminal or commandline interpreter. On windows I guess put it in quotes.

So ` -schemaSpec="(?!^information_schema$|sys$).*"`

**Comment by sunilsql** [comment]
I used with in quotes and I got this:

E:\>java -jar schemaspy-6.0.0.jar -t mssql08-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -u test -p test -schemaSpec="(?!^information_schema$|sys$).*" -o E:\adv -gv "C:\Program Files (x86)\Graphviz2.38" -debug
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESKTOP-SM37531 with PID 2820 (E:\schemaspy-6.0.0.jar started by sunil in E:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.747 seconds (JVM running for 2.348)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mssql08-jtds ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08-jtds.properties ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05-jtds.properties ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql-jtds.properties ->
        /E:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'DESKTOP-SM37531:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'AdventureWorks2016CTP3' description: 'database name  '
DEBUG - supportsSchemasInTableDefinitions: true
DEBUG - supportsCatalogsInTableDefinitions: true
DEBUG - Catalog not provided, queried jdbc driver and got 'AdventureWorks2016CTP3'
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.AbstractMethodError: net.sourceforge.jtds.jdbc.ConnectionJDBC3.getSchema()Ljava/lang/String;
        at org.schemaspy.db.SchemaResolver.resolveSchema(SchemaResolver.java:44)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:194)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        ... 8 more

**Comment by npetzall** [comment]
That's because you still need the `-all` or `-s` or `-schemas`.

We need to surround that code with a try catch and output a message about schema information missing.

**Comment by sunilsql** [comment]
Okay, I used -all, now I got just dbo. I do have Information_schema, sys, dbo. as I excluded 2 schema's I got the dbo. But I didn't get other user created schema's 

Here -schemaspec is working fine. But not -all (as It couldn't created report on User Schema's) 
right ?

**Comment by npetzall** [comment]
Something seems funky with `-all` the only thing I really can think of is permissions. But there might be a bug creeping around HERE. So I'll give it ago after kids have gone to sleep. I'll probably use sa account. But if you could expert the test user to an sql script so that I can add it exactly as you, I should get the same problem.

**Comment by sunilsql** [comment]
I think there is also something wrong with sso, this shows even when I tried with a single schema

E:\>java -Djava.library.path="E:\jtds-1.2-dist\SSO\ntlmauth.dll" -jar schemaspy-6.0.0.jar -sso -t mssql08-jtds -host DESKTOP-SM37531 -port 1433 -db AdventureWorks2016CTP3 -all -o E:\all -gv "C:\Program Files (x86)\Graphviz2.38"
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on DESKTOP-SM37531 with PID 15888 (E:\schemaspy-6.0.0.jar started by sunil in E:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.641 seconds (JVM running for 2.206)
INFO  - Configuration file not found
WARN  - Connection Failure

**Comment by npetzall** [comment]
Open new issue and add output when using `-debug`

**Comment by sunilsql** [comment]
Opened other ticket for-sso, and please let me know once you get a solution for -all. Thank you

**Comment by npetzall** [comment]
I've now imported the AdventureWork table and tested it using the SA account.

I got an error when using 6.0.0 and microsoft driver and realized that I've fixed it in 6.1.0-SNAPSHOT. #397 and PR #398 

I switched to jtds driver version 1.3.1 and it all works.

So either newer driver or have a look at the rights for test user. If you can export the test user and supply me with that. I can test with test user and see if we use any restricted table and if it can be avoided.

**Comment by sunilsql** [comment]
Can you please share the link of SchemaSpy (I am not able to find it), I can test with that and will let you know

**Comment by npetzall** [comment]
If you want to try 6.1.0-SNAPSHOT -> https://github.com/schemaspy/schemaspy/blob/master/README.md#latest-build

1.3.1 jtds drivers google it. I downloaded it from maven central. However sourceforge mirror might be up again.

I ran 1.3.1 jtds and schemaspy 6.0.0 and -all on adventureworks on sqlserver 2017 without a problem.

**Comment by npetzall** [comment]
Also said it was with the Microsoft driver.

**Comment by rafalkasa** [comment]
It's look like that @npetzall provide you detailed explanation and issue was solved.
Thank you for report the problem.
