### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by jflambert** [schemaspy/schemaspy#506]
## Expected Behavior
Shouldn't see this WARNING or at least there should be a workaround (apt install XXX)

## Current Behavior
WARNING appears all the time. Output makes it look like there is an error.

## Steps to Reproduce (for bugs)
1. Run schemaspy (as per Context and Environment below)
2. Almost instantly see the three WARNING messages in a row

10:42:34 INFO  - Starting Main v6.0.0 on XXX with PID 9656 (schemaspy-6.0.0.jar started by XXX in YYY)
10:42:34 INFO  - The following profiles are active: default
10:42:35 WARNING: An illegal reflective access operation has occurred
10:42:35 WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:schemaspy-6.0.0.jar!/BOOT-INF/lib/spring-core-4.3.13.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
10:42:35 WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
10:42:35 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
10:42:35 WARNING: All illegal access operations will be denied in a future release
10:42:37 INFO  - Started Main in 5.659 seconds (JVM running for 8.357)
10:42:37 INFO  - Configuration file not found
10:42:37 INFO  - Starting schema analysis
10:42:38 INFO  - Connected to PostgreSQL - 10.6 (Ubuntu 10.6-1.pgdg18.04+1)
10:42:38 INFO  - Gathering schema details

## Context
* Database type (e.g. MySQL): PostgreSQL
* Database driver version (is you use a special one): 10.6
* Your DDL (sample how to reproduce the issue): N/A
* Full command including arguments how you run SchemaSpy:
java -jar schemaspy-6.0.0.jar -o schemaspy -t pgsql -dp postgresql-42.2.2.jar -host localhost -db XXX -s public -u YYY -p ZZZ

## Your Environment
* Version used: 6.0.0
* Operating System and version (e.g. Windows 10): Ubuntu 18.04
* Java version:
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

**Comment by npetzall** [comment]
The issue is with Spring. It seem that this might be solved in Spring framework 5.1.RC1 there is currently a 5.1.4. Spring framwork is a transient dependency to spring boot. So bumping spring boot might fix the issue.

So any takers on bumping spring boot and verifying this.

Keep in mind that this is a warning and not an error.
