### ISSUE TITLE
cannot connect to server

### ISSUE THREAD

**Issue by sunilsql** [schemaspy/schemaspy#509]
Caused by: java.sql.SQLException: Network error IOException: Connection refused: connect

using 
schemaspy6.0
graphviz2.38
jtds1.2
sql server 2008

Comamnd: java -jar SchemaSpy-6.0.0.jar -t mssql08-jtds -host Servername -port 1433 -db databasename
 -u username -p password -s schema -o outputpath -gv "graphviz path with filename"  -debug

Tried by enabling TCP and also Windows firewall

Still I didn't get any solution.

Can someone help with this ?

**Comment by MarkThielen** [comment]
I had similar problems running it with the docker image. While it might have been a different issue the "-debug" option did the trick for me, gives much more details.

**Comment by npetzall** [comment]
`Network error IOException: Connection refused: connect` is not an issue with schemaspy.
Either incorrect parameter host/port or the server/network is incorrectly setup.
