### ISSUE TITLE
vizjs ignored

### ISSUE THREAD

**Issue by hgpit** [schemaspy/schemaspy#510]
Running on CentOS 7.

According to the documentation, adding -vizjs should cause SchemeSpy to use an embedded Graphviz? Or am I misunderstanding?

`[root@g000003 schemaspy]# java -jar /opt/hgl/schemaspy/schemaspy-6.0.0.jar -vizjs -t mysql -host localhost -db sdata -u sdatareader -p tgdfgf -desc "SData Schema Report" -hq -dp /opt/hgl/schemaspy/mysql-connector-java-5.1.31-bin.jar -o "/var/www/sdata.hg.local/maintenance/schemaspy" -s sdata
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on g000003 with PID 24377 (/opt/hgl/schemaspy/schemaspy-6.0.0.jar started by root in /opt/hgl/schemaspy)
INFO  - The following profiles are active: default
INFO  - Configuration file not found
INFO  - Starting schema analysis

WARN  - Failed to query Graphviz graphvizVersion information
WARN  -   with: dot -V
WARN  -   {}`

Why does it ignore the command line parameter?

Thank you

**Comment by npetzall** [comment]
It's new in 6.1.0-SNAPSHOT, but it's a good point latest should be 6.0.0 and have new docs called snapshot.

So if you wanna use viz.js you need to get 6.1.0-SNAPSHOT from the readme

**Comment by hgpit** [comment]
Okay thanks, I will give it a shot :)

**Comment by npetzall** [comment]
Well couldn't change the name or even add a version of doc called snapshot. So latest is master and a future release. So using version 6.0.0 you need to use the 6.0.0 version of docs it doesn't contain any mention of vizjs.

Just keep in mind we have 2 vizjs issues.
For the smoothest usage I suggest using the docker image.

**Comment by hgpit** [comment]
I got hold of the 6.1.0-SNAPSHOT and appears to work fine.

A million thank yous :)
