### ISSUE TITLE
Docker image documentation should have an explanation how to mount the config file

### ISSUE THREAD

**Issue by josemaia** [schemaspy/schemaspy#517]
## Expected Behavior
When attempting to run the docker image, it should be clear to users what steps are required to use the _schemaspy.properties_ file.

## Current Behavior
Docker image [documentation](https://hub.docker.com/r/schemaspy/schemaspy/) indicates the /config volume is created if users want to mount _schemaspy.properties_, but does not indicate the necessity of also setting _-configFile /config/schemaspy.properties_ so that it is searched for.

## Possible Solution
1) Update documentation to add this detail
2) Change the configuration of the docker image to automatically search in that path.

## Steps to Reproduce (for bugs)

1. Pull the schemaspy/schemaspy docker image
2. Create a settings file with your configurations in a folder such as /home/myuser/configs, i.e. /home/myuser/configs/schemaspy.properties
3. Run a single-line docker run command mounting the aforementioned folder, i.e.
```docker run -v "/home/myuser/schemaspy/:/output" -v "/home/myuser/configs/:/config/" schemaspy/schemaspy```
4. Verify the application fails to run with an error
```ERROR - The following option is required: [-u | --user | user | schemaspy.u | schemaspy.user]```
5. Add ``` -configFile /config/schemaspy.properties``` and see it runs correctly.

## Context
* Database type (e.g. MySQL): Postgresql

## Your Environment
* Version used: Latest docker image at the time of this post, which is tagged 6.0.0
* Environment name and version (e.g. Chrome 39): n/a
* Operating System and version (e.g. Windows 10): Ubuntu 16.04
* Java version: n/a

**Comment by npetzall** [comment]
Yeah that was half done. I wonder would it be better to remove the /config volume and actually just mount the file into root with the correct name. Since it will look in / for schemaspy.properties.

Skipping the -config file option.

Ending up with something like
`docker run -v "/home/myuser/schemaspy/:/output" -v "/home/myuser/configs/schemaspy.properties:/schemaspy.properties" schemaspy/schemaspy`

**Comment by npetzall** [comment]
@josemaia I've created a PR to remove the config volume from the image.
I've updated the instructions on docker-hub. Could you have a look and if it looks OK you can close this. If not I want feedback so that I can improve it even more.

**Comment by josemaia** [comment]
This looks great, thanks for the quick turnaround!
