### ISSUE TITLE
ERROR - Bad config: org.schemaspy.view.StyleSheet$MissingCssPropertyException: Required property 'background' was not found for the definition of '.diagram'

### ISSUE THREAD

**Issue by vancouverdeveloper** [schemaspy/schemaspy#538]
So I tried it the first time and I was all excited but in the end, it gave me the 

`org.schemaspy.view.StyleSheet$MissingCssPropertyException: Required property 'background' was not found for the definition of '.diagram' `  error

I ran:

java -jar schemaspy-6.1.0-SNAPSHOT.jar -t mysql -dp C:\SchemaSpyApp\V981603-01\mysql-connector-java-commercial-8.0.15\mysql-connector-java-commercial-8.0.15.jar -db ourdatabase -s ourdatabase -hq -host ourserver.site.com -port 3306 -u me -p myPassword-o C:\SchemaSpyApp\testoutput -debug

where is this stylesheet they are talking about?

thanks

**Comment by npetzall** [comment]
When loading CSS stylesheet it looks first in the working dir. The folder you are in when executing Java.

There might be a small gap of error now that I look at it. Either a file schemaspy.css is located in the workingdir or a folder with the same name.

**Comment by npetzall** [comment]
If that is the case you should in the output of schemaspy have a line that it's using external stylesheet.

**Comment by vancouverdeveloper** [comment]
os I would now just add -css Schemaspy,css to the command line line and ensure that file is in?

**Comment by vancouverdeveloper** [comment]
java -jar schemaspy-6.1.0-SNAPSHOT.jar -t mysql -dp C:\SchemaSpyApp\V981603-01\mysql-connector-java-commercial-8.0.15\mysql-connector-java-commercial-8.0.15.jar -db ourdatabase -s ourdatabase -css schemaSpy.css -hq  -host ourserver.site.com -port 3306 -u me -p hello -o C:\SchemaSpyApp\ecltw5 -debug

**Comment by npetzall** [comment]
In the future we migh change how this is done. I might be appear as black magic that it uses a file in workdir just because it exist or even stupid as it is now a folder.

If you have a file or folder in workdir move them or rename them. Their is a working schemaspy.css included and should only be change if one wants css changes and in that case one need to add all required css config.

**Comment by vancouverdeveloper** [comment]
Yes! its creating the files now! sooo excited! thank you

**Comment by vancouverdeveloper** [comment]
I thought I was in the clear but now it shows in the pages

"No diagrams were produced please see application output for any errors"

**Comment by npetzall** [comment]
Might be that you don't have graphviz installed. But with 6.1.0-SNAPSHOT you can use the experimental `-vizjs` and use a Javascript solution.

If graphviz isn't installed you should probably get an error or your database doesn't have foreign keys.

**Comment by vancouverdeveloper** [comment]
it is installed... maybe I will just use the regular .jar file

**Comment by npetzall** [comment]
Without any type of output from the application I can't do much.

For graphviz if installed you must be able to run dot from the same folder as you launch Java and schemaspy. If there are errors with dot they should be printed.

As for dependencies and getting the most things working the docker image has seldom had problem.

**Comment by vancouverdeveloper** [comment]
c:\SchemaSpyApp>dot -V
dot - graphviz version 2.38.0 (20140413.2041)

so it's there... let me try the non snapshot version and see what happens... perhaps it;s because I add the "gui" version files in there

**Comment by vancouverdeveloper** [comment]
now.. it rendered it correctly ...but no diagrams or images shown nor relationships

...
Wrote relationship details of 579 tables/views to directory 'C:\SchemaSpyApp\testoutput' in 686 seconds.
View the results by opening C:\SchemaSpyApp\testoutput\index.html
INFO  - Wrote table details in 9 seconds
INFO  - Wrote relationship details of 579 tables/views to directory 'C:\SchemaSpyApp\testoutput' in 686 seconds.
INFO  - View the results by opening C:\SchemaSpyApp\testoutput\index.html


but now I when i click on relationships it shows

Missed Relationships!
No relationships were detected in the schema.

weird... there should be as I tested it using DBSchema which shows it

there are no diagrams as well

it should look like this for a moodle lms database

https://moodleschema.zoola.io/index.html

**Comment by vancouverdeveloper** [comment]
do i have to a meta .xml file to show the relationships?

**Comment by npetzall** [comment]
Only use meta if you want to add relationships that are not stored in database.

**Comment by vancouverdeveloper** [comment]
weird why it's not showing any diagrams or relationships though

**Comment by npetzall** [comment]
Output about dot and or graphviz should be before the logging you supplied. A friend of mine stumbled over a bug earlier today. Which was caused by a locale dependent operation this messed up the diagrams and the code can be avoided by using `-norows`

**Comment by npetzall** [comment]
If you look at a table in the output does it list any parents or children?

**Comment by vancouverdeveloper** [comment]
what do you mean by output about dot and graphviz before my logging? You mean what I saw as it scrolled?
now will redo it with -norows

**Comment by npetzall** [comment]
Any errors or warnings about dot would be before the line `Wrote relationship details of 579 tables`

**Comment by vancouverdeveloper** [comment]
gotcha.. waiting for it to complete ... and will let you know

**Comment by vancouverdeveloper** [comment]
[MYdebug.txt](https://github.com/schemaspy/schemaspy/files/2989826/MYdebug.txt)

Here you go...

**Comment by vancouverdeveloper** [comment]
The images are there in the folder and I can see them but not on the html page ..

**Comment by npetzall** [comment]
That output says you should have a bunch of tables in Orphans page.

If you look in ouput/diagrams/summary does it contain any files?

**Comment by vancouverdeveloper** [comment]
just one ...relationships.real.compact.dot

**Comment by vancouverdeveloper** [comment]
correct in the orphans page... but they should not be... strange

**Comment by npetzall** [comment]
We know one thing now. Schemaspy can't find the relationships.

Dbschema was it run with the same user? Is it mysql or mariadb?

**Comment by vancouverdeveloper** [comment]
yes it was ... mysql 5.7.24

**Comment by vancouverdeveloper** [comment]
I'll do a bit more digging.. will let you know

**Comment by npetzall** [comment]
I'm gonna suggest using 6.x version of the driver. Later when I get the time I can try running our tests with 8.x driver. We test against mysql 5 and not 8.

**Comment by vancouverdeveloper** [comment]
I am using the version6  i think " schemaspy-6.0.0.jar"

**Comment by npetzall** [comment]
I was talking about mysql connector.

We had some issues before but can't remember if it was connector 6.0.6 with mysql 8 or connector 8 with mysql 5.7.

Schemaspy 06.1.0-SNAPSHOT is development version latest and greatest but un-released 6.0.0 is latest release and pretty old by now I think.

**Comment by vancouverdeveloper** [comment]
I am using connector 8 with 5.7

**Comment by vancouverdeveloper** [comment]
My dot

C:\$> dot -v
dot - graphviz version 2.38.0 (20140413.2041)
libdir = "C:\Program Files (x86)\Graphviz2.38\bin"
Activated plugin library: gvplugin_dot_layout.dll
Using layout: dot:dot_layout
Activated plugin library: gvplugin_core.dll
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        C:\Program Files (x86)\Graphviz2.38\bin\config6
                was successfully loaded.
    render      :  cairo dot fig gd gdiplus map pic pov ps svg tk vml vrml xdot
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  bmp canon cmap cmapx cmapx_np dot emf emfplus eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg metafile pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4
    loadimage   :  (lib) bmp eps gd gd2 gif jpe jpeg jpg png ps svg

**Comment by npetzall** [comment]
Dot is working, everything seems fine except that schemaspy is unable to get relationships.
I've run our tests with mysql 5.7 and mysql connector 8.0.15 all tests pass.

Btw, output/diagrams/summary/relationships.real.compact.dot was i empty?

Do you have any output between: 
INFO  - Writing/graphing summary
and
INFO  - Completed summary

**Comment by vancouverdeveloper** [comment]
INFO  - Wrote relationship details of 468 tables/views to directory 'C:\SchemaSpyApp\testoutput' in 365 seconds.

**Comment by vancouverdeveloper** [comment]
Let me try it with a default database from the vendor.. perhaps there were none and the relationships were built in another way through their xml file

**Comment by vancouverdeveloper** [comment]
So I downloaded a stock moodle install fresh with basic tables  and it's the same... no relationships shown :-( .. all tables seen as orphans

**Comment by npetzall** [comment]
moodle like in moodle.org?
If you havent added any secrete data or put a secrete pass word could you export the database and I can import it and have a look?

**Comment by vancouverdeveloper** [comment]
sure ... how do you want me to send it to you?

**Comment by vancouverdeveloper** [comment]
just over 1 GB and yes moodle.org

**Comment by npetzall** [comment]
wait, what...
As long as we do the same thing, we should get the same results.

I've setup a moodle system using docker images: https://hub.docker.com/r/jhardison/moodle

I'm about to run it though schemaspy

**Comment by vancouverdeveloper** [comment]
good luck lol

**Comment by npetzall** [comment]
Yepp, I get the same as you. Only orphans.

**Comment by vancouverdeveloper** [comment]
oh "good".. strange right?

**Comment by npetzall** [comment]
I've looked at the database and I cant find a single FK

**Comment by vancouverdeveloper** [comment]
yes.. me as well./ ... obviously the application works but its not in the xml files I guess

**Comment by npetzall** [comment]
https://tracker.moodle.org/browse/MDL-30799

**Comment by npetzall** [comment]
There was a custom css-file with missing attributes.
The database used doesn't have or use FKs.

**Comment by vancouverdeveloper** [comment]
I think I may have found a way but will confirm first and let you know that is moodle db specific
