### ISSUE TITLE
Remove built in swing UI?

### ISSUE THREAD

**Issue by Riggs333** [schemaspy/schemaspy#54]
Hi Rafal,

first of all: Great work! Thanks for keeping up and enhancing this project and putting up so much time and effort in it! :+1: :-)

Peeking into the source I noticed there is a **small built in Swing GUI** that can be started by using the `-gui` command line parameter (see https://github.com/schemaspy/schemaspy/blob/master/src/main/java/org/schemaspy/Main.java#L42).
I'm wondering if this feature is still needed.

There exists an advanced GUI using any Schemaspy JAR: http://schemaspygui.sourceforge.net/
(I tested it briefly with 6.0.0-rc1 - works fine.)

If we remove this built in GUI and delete the classes of the ui package https://github.com/schemaspy/schemaspy/tree/master/src/main/java/org/schemaspy/ui
we could focus more on the core functionality of Schemaspy.
In my opinion this would **slim down** the project.

Maybe you already have something like that in mind? I see there is a separate project https://github.com/schemaspy/schemaspygui

**Comment by Riggs333** [comment]
Oh, well I should read the docs first. ;-)
https://schemaspy.readthedocs.io/en/latest/home.html#schemaspy-gui
So you are already aware of the SchemaSpyGUI project.

Shall we remove the built in GUI then?

**Comment by Riggs333** [comment]
As I'm looking at the codebase again to do some refactoring, fix sonar issues and writing tests I'm stumbling upon a significant amount of code that is bound to this built in GUI.

 What's your opinion on removing this feature in favor of cleaning up the codebase?

**Comment by rafalkasa** [comment]
@Riggs333 I believe that we should remove this from SchemaSpy core project.
I would like in the feature create another project with configuration GUI.
So if you want, you have me green light to remove it from project :-)
