### ISSUE TITLE
No columns listed in report

### ISSUE THREAD

**Issue by hgpit** [schemaspy/schemaspy#540]
Hi,
When we browse to our SchemaSpy report and click 'Tables' along the top menu, there are no results.

## Expected Behavior
We are expecting the main page section titled 'Columns' to populate with a list of all the columns in the DB.

As you can see, this is quite a large DB with many columns:
![image](https://user-images.githubusercontent.com/16598973/55147476-5b1d9b80-513e-11e9-9893-8d55ed4e97ab.png)

## Current Behavior
The section is blank
![image](https://user-images.githubusercontent.com/16598973/55147323-18f45a00-513e-11e9-8983-9dc3fce39cbd.png)

## Possible Solution
I have tried upgrading to the latest SchemaSpy snapshot but no fix.

## Steps to Reproduce (for bugs)
Whether we use a newer snapshot (of SchemaSpy) or just rebuild the data, this problem persists.

## Context
This has been a problem ever since we started using SchemaSpy 6 (any version, any snapshot). In the previous version of SchemaSpy it was fine.
The problem manifests in every version of Chrome we have tried and Firefox.

* Database type (e.g. MySQL): MariaDB 10.2.22

This is how we build it:
java -jar /opt/hgl/schemaspy/schemaspy-6.1.0-SNAPSHOT.jar -vizjs -t mysql -host localhost -db DBNAME -u USER -p PASSWORD -s masdata -desc "DBNAME Schema Report" EXCLUDETABLES -hq -dp /opt/hgl/schemaspy/mysql-connector-java-5.1.31-bin.jar -o /output/folder

## Your Environment
This is hosted on a Google Cloud instance running CentOS 7
We have tried using Java MySQL connectors mysql-connector-java-5.1.31-bin.jar and mysql-connector-java-8.0.15.jar

Thank you for your consideration.

**Comment by npetzall** [comment]
@hgpit Could you open the developer consol in either Firefox or Chrome and see if you have any errors. For performance reasons we have columns-data in a separate file and not embedded in the html of the columns page. So it needs to load and parse that data and if anythong failes I think you should get an error in the console.

**Comment by hgpit** [comment]
Sure thing :)

Here's the console output in Chrome:

![image](https://user-images.githubusercontent.com/16598973/55239792-508eff00-522f-11e9-9a2a-2954689266ba.png)

And Firefox:

![image](https://user-images.githubusercontent.com/16598973/55239999-bf6c5800-522f-11e9-8a4d-c884b69c0d7f.png)

**Comment by npetzall** [comment]
Could you have a look around line 3680 in columns.html

The data for columns are included in the html but as json objects, and it seems there is something wrong with the format. I was wrong in my previouse statement about separate file.

But anywho, there is an issue around line 3680, and the bug is that it's not escaped when written to json.

If possible could you provide me with the field that seems incorrect and I can create test and fix.
If you can't provide the field, just let me know what character seems to be creating the issue.

I'll start and check that `"`, `'` and `,` work as expected.

**Comment by hgpit** [comment]
Okay, here are my findings:

Line 3680 of columns.html contains:
![image](https://user-images.githubusercontent.com/16598973/55242498-44a63b80-5235-11e9-989d-1234b738b734.png)

If I check the actual comment against the table via my SQL client, I can see the actual comment is:

![image](https://user-images.githubusercontent.com/16598973/55242560-6bfd0880-5235-11e9-8219-972a2f66efce.png)

So I guess it's the square brackets upsetting things? :)

**Comment by npetzall** [comment]
Could you add `\` before the `"` that surrounds the `./null` and see if it helps.

**Comment by hgpit** [comment]
Hi @npetzall ,

Yes, escaping the `"` appears to do the trick! :)

![image](https://user-images.githubusercontent.com/16598973/55244117-74a30e00-5238-11e9-90b6-4e77b1232e7d.png)

**Comment by hgpit** [comment]
Can I ask if this is acknowledged as a bug then, which will (hopefully) be fixed in a future snapshot?

At the moment I am having to edit the HTML file multiple times a day to manually fix it for my users.

Thanks :)

**Comment by npetzall** [comment]
Yepp, it's a bug.

I'll hopefully get time tonight to fix it.
