### ISSUE TITLE
Random failure during "Writing/diagramming details"

### ISSUE THREAD

**Issue by jflambert** [schemaspy/schemaspy#541]
We run schemaspy every 30 minutes and maybe 1/100 times we get the following failure. I can't say for certain that it has to do with a specific table, I'll have to gather more failures. But I figured I'd get the ball rolling.

## Expected Behavior
SchemaSpy shouldn't just randomly fail during diagram step, especially since it works most of the time.

## Current Behavior
Rarely, we get a failure while writing diagram details. I've just recently enabled debug mode so I don't have much info on previous failures.

## Steps to Reproduce (for bugs)
1. Run schemaspy every 30 minutes
2. Normally works no problem
3. Once in a blue moon, the following exception occurs:

```
.DEBUG - Writing details for alarmsubconfigurations
DEBUG - dot -Tpng:cairo schemaspy/diagrams/alarmsubconfigurations.1degree.dot -oschemaspy/diagrams/alarmsubconfigurations.1degree.png -Tcmapx
DEBUG - dot -Tpng:cairo schemaspy/diagrams/alarmsubconfigurations.2degrees.dot -oschemaspy/diagrams/alarmsubconfigurations.2degrees.png -Tcmapx
ERROR - null
java.lang.NullPointerException: null
	at java.base/java.io.File.<init>(File.java:359)
	at org.schemaspy.view.MustacheWriter.write(MustacheWriter.java:104)
	at org.schemaspy.view.HtmlTablePage.write(HtmlTablePage.java:93)
	at org.schemaspy.SchemaAnalyzer.generateTables(SchemaAnalyzer.java:430)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:395)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:226)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
	at org.schemaspy.Main.main(Main.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
+ exit 1
```

The only thing special about table `alarmSubConfigurations` is that it contains an HSTORE field. We have many other tables with an HSTORE column and they don't fail. Next time I have a failure (could be days, could be weeks) I will update the defect with the debug output. Here's the DDL of this one table:

```
-- alarm sub configurations
CREATE TABLE alarmSubConfigurations (
  asc_id SERIAL PRIMARY KEY,
  asc_asd_code TEXT NOT NULL,
  asc_ac_id INTEGER,          -- global subConfiguration when NULL
  asc_enabled BOOLEAN,        -- won't raise if FALSE
  asc_archived BOOLEAN,       -- won't show or raise if TRUE
  asc_details HSTORE,         -- extra configuration
  CONSTRAINT asc_ac_id_fkey FOREIGN KEY (asc_ac_id)
    REFERENCES alarmConfigurations (ac_id) ON DELETE CASCADE,
  CONSTRAINT asc_asd_code_fkey FOREIGN KEY (asc_asd_code)
    REFERENCES alarmSubDefinitions (asd_code)
    ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX asc_index_ac_id ON alarmSubConfigurations(asc_ac_id);
```

## Context
* Database type (e.g. MySQL): PostgreSQL 11.2
* Database driver version (is you use a special one): postgresql-42.2.2.jar
* Full command including arguments how you run SchemaSpy:
java -jar schemaspy-6.0.0.jar --debug -o schemaspy -t pgsql -dp postgresql-42.2.2.jar -host localhost -db xxx -s public -u xxx -p xxx

## Your Environment
* Version used: 6.0.0
* Operating System and version: Ubuntu 18.04
* Java version: java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

**Comment by npetzall** [comment]
`at java.base/java.io.File.<init>(File.java:359)` Child in constructor is null.
`at org.schemaspy.view.MustacheWriter.write(MustacheWriter.java:104)` Destination is null
`mw.write("tables/table.html", Markdown.pagePath(table.getName()), "table.js")` `Markdown.pagePath(table.getName())` returns null

Which means path hasn't been registered or was registered with null.

Since it's registered like
```
String tablePath = "tables/" + table.getName() + ".html";
Markdown.registryPage(table.getName(), tablePath);
```

Registring with null is sort out of the question. So probably not registered.
Things have changed in 6.1.0-SNAPSHOT.
But a known problem/limitation is that you can't have tables only defined in schemameta-xml.

And there shouldn't be any concurrency issues. Have you had any issues like this with 6.1.0-SNAPSHOT?

**Comment by jflambert** [comment]
I haven't given 6.1.0 snapshot a fair shake since I had a few immediate issues with PostgreSQL 11.2 out of the box. Since this is used in a production environment I would normally prefer using 6.0.0 and as I said, the random failure occurs once a week or month even. I've been seeing it since 6.0.0 came out but only bothered to enable DEBUG last week.

Actually I have two main jobs, release and debug, so maybe I could start using 6.1.0 on my debug job. I'll let you know if anything comes up.

**Comment by npetzall** [comment]
Sounds good, I'm gonna spend som hrs tonight on issues, it's easier to add debug code to 6.1.0-SNAPSHOT than to 6.0.0 but it's possible.

**Comment by jflambert** [comment]
It's been 2 weeks and I haven't seen a single failure from ~18 runs per day on a (very) large postgresql schema using 6.1.0 snapshot. I'll let you know but for now I think you can close it.

**Comment by jflambert** [comment]
It happened again today with 6.0.0. Still no failure with 6.1.0 though. Leaving this one for debugging purposes.

`08:02:42 DEBUG - dot -Tpng:cairo /xxx/schemaspy/diagrams/alarmdefinitions.implied2degrees.dot -o/sss/schemaspy/diagrams/alarmdefinitions.implied2degrees.png -Tcmapx
08:02:42 ERROR - null
08:02:42 java.lang.NullPointerException: null
08:02:42 	at java.base/java.io.File.<init>(File.java:359)
08:02:42 	at org.schemaspy.view.MustacheWriter.write(MustacheWriter.java:104)
08:02:42 	at org.schemaspy.view.HtmlTablePage.write(HtmlTablePage.java:93)
08:02:42 	at org.schemaspy.SchemaAnalyzer.generateTables(SchemaAnalyzer.java:430)
08:02:42 	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:395)
08:02:42 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:226)
08:02:42 	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
08:02:42 	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
08:02:42 	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
08:02:42 	at org.schemaspy.Main.main(Main.java:48)
08:02:42 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:02:42 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:02:42 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:02:42 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
08:02:42 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
08:02:42 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
08:02:42 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
08:02:42 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)`
