### ISSUE TITLE
Graphviz with svg output have broken link

### ISSUE THREAD

**Issue by chunlinyao** [schemaspy/schemaspy#547]
SVGs generated by graphviz, have the image and a link related to work directory of output dir.
When opened in browser primaryKeys.png not found and click on svg image can not navigate to correct table info html page.

These sed command can workaround it .
```
find . -name *.svg -exec sed -i bk -e 's/\(image xlink:href="\).*\(images[^"]*\)/\1..\/..\/\2/g' {} \;
find . -name *.svg -exec sed -i bk -e 's/\(a xlink:href="\)\(tables\/\)\{0,1\}\([^"]*\)/\1..\/..\/tables\/\3/g' {} \;
```

Maybe we can replace the generated svg file contents in Java code.

**Comment by npetzall** [comment]
Which version of schemaspy? 
Is this with or without `-vizjs`?

**Comment by npetzall** [comment]
Is this when opening the svg directly or when viewing the svg in the corresponding html page?

**Comment by chunlinyao** [comment]
without -vizjs, vizjs generate correct svg, but vizjs is slow, using 6.1.0-snapshot with graphviz. When viewing the svg in the corresponding html page and opening directly have same result.

dot - graphviz version 2.40.1 (20161225.0304)
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
macOS mojave 10.14.4

**Comment by npetzall** [comment]
So your using the `-imageformat svg`, I'll have a look at it, we did somethings to get the images and links working with `-vizjs` might need to do the same with graphviz and imageformat svg.
