### ISSUE TITLE
Document how to run in Docker with SchemaMeta

### ISSUE THREAD

**Issue by DanRoestorf** [schemaspy/schemaspy#551]
When running SchemaSpy in Docker, the docs here explain clearly how to pass in a properties file. It would be handy if it also included how to pass a SchemaMeta file in. I'm currently trying to do this and unable to find any information.

https://hub.docker.com/r/schemaspy/schemaspy/

**Comment by npetzall** [comment]
I've added hope it helps, else let me know

**Comment by DanRoestorf** [comment]
@npetzall I really appreciate the quick response, works like a charm!

Thanks so much.
