### ISSUE TITLE
Fix incorrect error about diagrams in table page

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#553]
Orphan tables has an incorrect warning about failed diagrams.

**Comment by npetzall** [comment]
I'm in favor of just adding the diagram with just the single table and no relationships as mentioned by myself in #376

**Comment by dmoore247** [comment]
I'd vote for "I'm in favor of just adding the diagram with just the single table and no relationships as mentioned by myself in #376"

**Comment by npetzall** [comment]
Will do #376
