### ISSUE TITLE
Add option only using CSS from localhost

### ISSUE THREAD

**Issue by desarrollo2M** [schemaspy/schemaspy#56]
If im using SchemaSpy from a pc without Internet, i would need an option to use only those CSS who are in localhost, not online.

**Comment by rafalkasa** [comment]
@desarrollo2M thank you for create the issue and use SchemaSpy. Exactly, good point a lot of css and JavaScript libraries are not available without access to the internet.

**Comment by rafalkasa** [comment]
Your issue is also related to the #7 and duplicate it.

**Comment by desarrollo2M** [comment]
Even you havent Access to Internet, the application is still working. However, it goes so slow, because it probably is trying to obtain CSS from Internet and it can´t.

So, it would be so helpful if it exists an option to only use CSS from localhost.

Thank you very much for your amazing work!

**Comment by cheoAlejo** [comment]
+1

**Comment by npetzall** [comment]
I would say that local CSS is the only option.
