### ISSUE TITLE
Unable to configure custom driver

### ISSUE THREAD

**Issue by jefersonchaves** [schemaspy/schemaspy#570]
## Expected Behavior
I'm trying to run the a jdbc driver to extract info from salesforce available at this [repo](https://github.com/claimvantage/force-metadata-jdbc-driver). This is related to claimvantage/force-metadata-jdbc-driver/issues/5 reported there.

## Current Behavior
Schemaspy 6.0.0 outputs that is unable to resolve databaseType: force.

## Possible Solution
Possible assistance on how to configure it properly.

## Steps to Reproduce (for bugs)
Simply run the following:
```
java -jar schemaspy-6.0.0.jar \
     -dp force-metadata-jdbc-driver-2.3.jar \
     -t force -u MySalesforceUsername \
     -p MySalesforcePasswordAndSecurityToken \
     -o doc \
     -db MyOrgName \
     -cat % \
     -s force
```

## Context
* Database type (e.g. MySQL): Salesforce (custom driver)
* Database driver version (is you use a special one): 2.3?

## Your Environment
* Version used: 6.0.0
* Operating System and version (e.g. Windows 10): Mac OS Mojave 10.14.5
* Java version: openjdk 11.0.3 2019-04-16 LTS (Zulu from Azul Systems).

**Comment by npetzall** [comment]
There is no databaseType `-t force` included with schemaspy so you need to create your own.

https://schemaspy.readthedocs.io/en/latest/configuration/databaseType.html#databasetype

If the driver and database is based of supported/included databaseType you can extend it.

I'll have a quick look at the repo and issue you mentioned.

**Comment by npetzall** [comment]
This might be related to how schemaspy 6.0.0 and later resolves the databaseType.

Since the repo and probably the jar will contain `force.properties`

For now you can just copy the file to the same dir as the schemaspy-jar file.

**Comment by npetzall** [comment]
https://raw.githubusercontent.com/claimvantage/force-metadata-jdbc-driver/master/force.properties

I can add it to schemaspy so that it's included in snapshot and next release.

**Comment by jefersonchaves** [comment]
Thanks @npetzall 🥇 🎉  
I will add the info into the documentation. The project was started from a co-worker and I was trying to assist.

**Comment by npetzall** [comment]
I added it so using 6.1.0-SNAPSHOT the file won't need copying.

Added experimental bonus is `-vizjs`which will remove the requirement for graphviz.
