### ISSUE TITLE
Is schemaspy.org offline?

### ISSUE THREAD

**Issue by renannprado** [schemaspy/schemaspy#572]

**Comment by npetzall** [comment]
It shouldn't be unless there is an issue with github or dns.
I don't maintain dns so @rafalkasa needs to check it.
As for github the site repo hasn't changed. 

I'm on a pretty bad cellphone connection and I get connection refused but not only to schemaspy.org

**Comment by renannprado** [comment]
I've just tried to access again and I'm on cable connection. I even tried to through VPN, it doesn't seem to work.

**Comment by rafalkasa** [comment]
This is madnes I'm fighting with dns operator nazwa.pl wchich block this domain becouse stupid polish law today I should resolve the issue. I'm alter dozen emails and phones to operator.

**Comment by rafalkasa** [comment]
schemaspy.org is back sorry for that :-)
