### ISSUE TITLE
6.1.0 Release ETA

### ISSUE THREAD

**Issue by abitrolly** [schemaspy/schemaspy#579]
Looks like all planned issues for 6.1.0 are closed. Are there any plans for release?

https://github.com/schemaspy/schemaspy/milestone/6

## Expected Behavior

* https://github.com/schemaspy/schemaspy/pull/469

**Comment by npetzall** [comment]
@rafalkasa Should we do a once over the open issues and see if something is must fix? I think the draft has been up since... Nov, 2018

**Comment by abitrolly** [comment]
I am pretty fine with `snapshot` release, but it is not convenient for version tracking. Maybe releasing 6.1.0 and then fixing issues as they arrive in 6.1.1 etc will be a better approach?

**Comment by proxy-m** [comment]
Create 6.1.0 Release Candidate, please.

**Comment by npetzall** [comment]
I'm gonna sound a bit lazy right now. But if you want to pin to a commit that's possible with jitpack.io

Since that is all a rc release would do.

**Comment by proxy-m** [comment]
So, https://jitpack.io/#schemaspy/schemaspy/810222eae0
may be 6.1.0rc1 .

**Comment by npetzall** [comment]
@proxy-m You could say that. We don't have any major features targeted for 6.1, but you won't get any fixes unless you update the commit hash.

**Comment by abitrolly** [comment]
Should major features be targeted to 7.0.0?

**Comment by npetzall** [comment]
@abitrolly depends, we try to follow semVer to the best of our ability.

So if we break backwards compatability it should be 7.0 else it's gonna be 6.2.

And now we haven't discussed what a major feature is. Since we have only had one I think and it was the vizjs.

**Comment by proxy-m** [comment]
@npetzall , jitpack service not work anymore. Can you create release of 6.1.0, please?

This version has major changes in case: it suports render via vizjs (spring boot + java run js engine + vizjs dot) without requirement of standalone graphviz dot installation.

It hard to identify version, when there is not official release.

**Comment by npetzall** [comment]
@rafalkasa should we just go ahead and do a release?

**Comment by rafalkasa** [comment]
Nils

Sorry that I'm not active in the project SchemaSpy, but my other activities
totally consume my time and energy :-)
If you can please try to release 6.1.0. If not maybe in next week I can hep
in the process of release SchemaSpy.

Best Regards
Rafal


śr., 11 wrz 2019 o 20:14 Nils Petzäll <notifications@github.com> napisał(a):

**Comment by npetzall** [comment]
@rafalkasa  no worries, it's a spare time project.

I'll see if I get time tonight else it'll be beginning of next week.

**Comment by npetzall** [comment]
So, I've done my best, either re-open if things are wrong or file a new issue.
