### ISSUE TITLE
Jar inside of docker image

### ISSUE THREAD

**Issue by renannprado** [schemaspy/schemaspy#583]
I'm currently working on an automation inside of our CI system and I would like to use schemaspy to generate documentation of the database.
I have done some modifications in the image, as I jenkins doesn't like when the image has an entrypoint.
Now I'll have to run an the image by doing the `java -jar schemaspy...jar`, however I see that the jar name has the version in its name.
It would help a lot if the jar inside of the image didn't contain version strings so that one can always refer to the jar with same name regardless of the tag of the image.
Of course I can do that by myself, but would be nice if this change was included in the official docker image. If I have time to do it, I'll send a pull request to change.

**Comment by npetzall** [comment]
I'm understand what you want to do. Remove the version from the jar inside of the image which is simply just change the add directive in the dockerfile. 

I don't really understand what the entrypoint directive has to do with jenkins, since that should be handled by docker. 

I found an jenkins issue and it seems that if you pass `-entrypoint=` in jenkins docker pipeline with the entrypoint script that we have it might work. 

https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-51307

Third comment from the end.

**Comment by renannprado** [comment]
Yep, you can pass the `-entrypoint=''` argumento to jenkins, but I wouldn't like to have such a thing in every pipeline, that's why I'm cleaning up the entrypoint (I have to extend the image to add cloudsql drivers as well). But that's not a problem, it's very specific to jenkins.
So I was taking a look at how flyway is doing (I also had to clean up the entrypoint of flyway image as well), they are adding their entrypoint to `/usr/local/bin/flyway` so that you can refer to it from anywhere in the image, and they also put the version numbers in the jars. 

Yes, now reevaluating, I can actually still rely on the current `/entrypoint.sh` (which doesn't care about the version), it is not as nice as having something in like `/usr/local/bin/schemaspy` IMO.

If you think it's a good idea, I can send a patch to improve it and create a `/usr/local/bin/schemaspy`.

Thanks for the fast reply!

**Comment by renannprado** [comment]
@npetzall I was trying to use the entrypoing, but now I realized that I cannot set again the `--outputDirectory` because the entrypoing already defines it. :(

**Comment by npetzall** [comment]
I don't know why you would want to change it. Since you always either need to mount it or need to copy from it.

You don't need to extend it to add drivers just mount them. 

When creating the image it was for schemaspy only and to be used as a containerized application so putting stuff in the path was not required. 

Your never supposed to be in the container.

**Comment by renannprado** [comment]
@npetzall I can't mount anything while using the jenkins docker plugin (as far as I know, at least), so I do need to include inside of the image.

The docker plugin already mounts the current working directory inside of the repository and plus I'm using kubernetes jenkins slaves, which makes things even more tricky.

**Comment by npetzall** [comment]
https://github.com/larrycai/dockerfile-examples/blob/master/Jenkinsfile

But I'm just googling. I'm gonna have quick look since I suspect it will run in `sh` and I think `java -jar schemaspy-*.jarʼ should work.

**Comment by renannprado** [comment]
When you're using kubernetes for jenkins slaves, things are trickier because the library has to mount the volume of your pod (where your workspace is) into new container (schemaspy) that you're trying to run. That works just fine. But for me to mount a new folder is not that easy because the lib is using calls like `docker volume inspect`, knowing what is the container ID of your pod and so on to find the volume of the current pod to then actually do the mount inside of the schemaspy container. This is one example of call:

`docker run .... --volumes-from c0cebfd32a152c083d8b3a55cf697e303dbdfd35ef02b716ecec3a300468e546`

Anyway, I wouldn't like to do that mainly because:
1 - I won't put the drivers inside of the git repository
2 - I wouldn't like to download the drivers in every build for every pipeline

So we're putting the extra drivers inside of the image so that "out-of-the-box" you already have everything that you need to use schemaspy.

Regardless, I don't have any limitation whatsoever, I'm able to get everything to work. It's just that the current entrypoint doesn't seem to be good enough, at least not from my point of view.
You can disregard my initial will to remove the version from the jar, because to me it seems we have more room for improvement in the entrypoint itself. I see at least three things that could be improved:
1 - I don't follow why is it required to extract the jar to then run it if there is already a main class set in the manifest, shouldn't `java -jar schmeaspy...` work?
2 - Put the entrypoint into the path with a proper name like `schemaspy`
3 - It's hardcoding an output path that, in case you want to change it while using the entrypoing, you can't

**Comment by npetzall** [comment]
> 1 - I don't follow why is it required to extract the jar to then run it if there is already a main class set in the manifest, shouldn't java -jar schmeaspy... work?

Thinking about it, I've changed how `-dp` works and it can probably be removed.
Previously `-dp` only handled single files now it can handle directories. The extraction of main-class is not needed and we can skip using `-cp` and main class I think. It was a hack to avoid specifying drivers using `-dp` and a container internal path.

As en example 
`C:\docker run schemaspy/schemaspy:latest -dp /drivers/mysql-something-somthing.jar -t mysql....`
`C:\docker run schemaspy/schemaspy:latest -t mysql...`

We could still do the check if /drivers or /drivers_include should be used and then set `-dp` when running `java -jar schemaspy-*.jar`

> 2 - Put the entrypoint into the path with a proper name like schemaspy  

This is doable.

> 3 - It's hardcoding an output path that, in case you want to change it while using the entrypoing, you can't.

This could be changed to an env. It's mainly for ease of use.
When running docker command you just need to mount the folder and not specify -o with a container internal path and also mount that.

As an example
`C:\docker run schemaspy/schemaspy:latest -v C:\Users\npetzall\schemaspy-output:/my-output" -o /my-output -t mysql....`
`C:\docker run schemaspy/schemaspy:latest -v C:\Users\npetzall\schemaspy-output:/output -t mysql`

But it could be change to ENV and ENV can be overriden.

**Comment by npetzall** [comment]
@renannprado would #601 handle most of the issues?
