### ISSUE TITLE
-vizjs produces squished diagram titles

### ISSUE THREAD

**Issue by Kamyabnz** [schemaspy/schemaspy#586]
Trying to use -vizjs for creation of diagrams, only relationships Diagrams look squished. By using the Master and the prebuild .jar

## Expected Behavior
The relationship Diagrams should look decent, the title should not be interfering with [Type]

## Current Behavior
The End of Diagram Titles are interfiering with table [Type] and you cannot read the last part of the title. With all of the Diagrams this is being seen and with longer titles it looks much worse. 

![Issue-Vizjs-piuc01](https://user-images.githubusercontent.com/32940190/63087682-0fd02200-bf53-11e9-81eb-73b923dfef94.PNG)

## Possible Solution
Maybe the VizJSDot.java should get some kind of title size reduction? 
To be honest, I don't know what you can do to make the diagram bigger and let the font stay the same size. I tried to make the title font smaller, but there is only one main font size option that sets of both texts the font size.

## Context
* Database type (e.g. MySQL): Informix
* Database driver version (is you use a special one): JDBC.4.10.JC4DE
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

x <--- Because because of privacy reasons

1. -jar schemaspy-6.1.0-SNAPSHOT.jar
2. -debug
3. -t informix 
4. -dp  D:\informix-drivers\JDBC.4.10.JC4DE\lib\ifxjdbc.jar;D:\informix-drivers\JDBC.4.10.JC4DE\lib\ifxjdbcx.jar
5. -host xxxx.xxxx.com
6. -port xxxx
7. -db axxxx
8. -server db
9. -connprops IFX_TRIMTRAILINGSPACES\\=1
10. -u username
11. -p password
12. -all
13. -vizjs
14. -o D:\OutputSchemaSpy6-1-Pre-made

## Your Environment
* Version used: Prebuild 6.1.0-SNAPSHOT and also latest Master maven build
* Environment name and version (e.g. Chrome 39): Chrome 76
* Operating System and version (e.g. Windows 10): Windows 10
* Java version: java version "1.8.0_212"

**Comment by npetzall** [comment]
I'm gonna see if I can recreate this. I had a quick glance at code that produces the dot-file/content.
It' seems that the "table/box" width is only calculated for columns.
So if this is correct, having a table with long name and all columns short should produce the issue.

In either case, what would you prefer larger "table/boxes" or smaller text?

**Comment by Kamyabnz** [comment]
I think a bigger table/box should do the work but still, if it is not really dynamic, then It would still lead to the same problem throughout the process if very large titles are being used. If you would add that it also calculates the size for the titles too then it would be much better, because of font form factors will stay the same.

**Comment by npetzall** [comment]
https://github.com/schemaspy/schemaspy/blob/master/src/main/java/org/schemaspy/output/dot/schemaspy/DotNode.java

Somewhere in there

**Comment by Kamyabnz** [comment]
@npetzall i have created a solution for this bug, i will create an PR today. I have created the same maxWidth function for the Title too and it seams to work.

**Comment by npetzall** [comment]
Fixed with #615 which was based of #598
