### ISSUE TITLE
connection failure - request a runable example for the example database chinook

### ISSUE THREAD

**Issue by junqi108** [schemaspy/schemaspy#593]
i followed the steps described on the schemaspy webpage, however i still do not know how to setup the server. i always met a connection error
## Steps to Reproduce (for bugs)

-java -jar schemaspy.jar -gv C:\PROGRA~2\Graphviz2.38 -sso -debug
code as follows
1.# type of database. Run with -dbhelp for details
schemaspy.t= mssql
# optional path to alternative jdbc drivers.
schemaspy.dp= H:\DatabaseDiagram\mssql-jdbc-7.0.0.jre8.jar
# database properties: host, port number, name user, password
schemaspy.host=localhost (also tried my IP address 10.400.204.....)
schemaspy.port=1433
schemaspy.db=chinook
# output dir to save generated files
schemaspy.o=H:\DatabaseDiagram\
# db scheme for which generate diagrams
schemaspy.s=public

## Context

* Database type (e.g. MySQL):
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39): 
* Operating System and version (e.g. Windows 10): windows 7
* Java version:
jre1.8.0_191
Could you email me a copy of runable code for chinook database: junqi108@gmail.com
![image](https://user-images.githubusercontent.com/13222562/64928417-4d82dc00-d86c-11e9-9736-a60a6f97839e.png)

**Comment by mprins** [comment]
See #566

**Comment by npetzall** [comment]
Which version and edition of sql server are you using?

Could you supply the full stacktrace, think there should be a caused by in the end which should explain more if it's Auth, network or driver. 

Using sso requires native library to be loaded and additional configuration of connectionString and that you have installed sql server with windows authentication.

**Comment by junqi108** [comment]
Thanks npetzall: 
here is the full debug information. 
i installed sqljdbc_7.4, and sqljdbc_6.4. for the version of 7.4. both has the connection issues. Does not know how to setup the server and connectionString. Could you provide an example code for it? thanks very much in advance. 
![image](https://user-images.githubusercontent.com/13222562/65005102-df651480-d952-11e9-8c8d-fc7479d0690e.png)

**Comment by npetzall** [comment]
Could you try with the 6.1.0-SNAPSHOT https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.1.0-SNAPSHOT.jar

We have improved logging since 6.0.0 and I think we added `-t mssql08` also for sql server 2008 or newer.

And to get stacktrace you need to add `-debug`

We are about to release 6.1.0 I just need a cpl of minutes at my computer.

**Comment by npetzall** [comment]
If you want windows authentication (single sign-on) have a look at https://schemaspy.readthedocs.io/en/latest/sso.html#mssql

And I think the error might be better in 6.1.0-SNAPSHOT if something is wrong.

**Comment by junqi108** [comment]
hi Npetzall: thanks for the tips. it is getting better. now it is mainly the connection problem with the localhost. seems blocked by the firewall... 
java -jar -Djava.library.path=h:\DatabaseDiagram\sqljdbc_7.4\enu\auth\x64\ h:\DatabaseDiagram\schemaspy-6.1.0.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp H:\DatabaseDiagram\mssql-jdbc-7.4.1.jre8.jar -host localhost -port 1433 -db chinook -gv C:\PROGRA~2\Graphviz2.38 -debug

![image](https://user-images.githubusercontent.com/13222562/65181564-6f21d480-dab3-11e9-87ac-64c1dc07b912.png)

**Comment by junqi108** [comment]
I installed the microsoft SQL server 2017
![image](https://user-images.githubusercontent.com/13222562/65182149-c2485700-dab4-11e9-9c10-49c607a7eb24.png)

**Comment by npetzall** [comment]
Could you try:
`sqlcmd -S tcp:MAR-L-427801,1433 -E`
And also
`sqlcmd -S np:\\MAR-L-427801\pipe\sql\query -E`

If the first doesn't work, but the second does. It might be firewall, but could also be that TCP/IP isn't enabled.

https://www.blackbaud.com/files/support/infinityinstaller/content/installermaster/tkenablenamedpipesandtcpipconnections.htm

**Comment by junqi108** [comment]
Dear npetzall:
thanks for the patient guide. i have configured the TCP/IP setup as instructed by the website. the two commands that you give seems work now. i think we are one step away from succeed now. 
the final error i got is login to database failed with for user ""
![image](https://user-images.githubusercontent.com/13222562/65276749-8973b500-db7c-11e9-9dba-3e36ec880ae3.png)

**Comment by junqi108** [comment]
with one \ in the integratedSecurity\=true, also returns the login error,
![image](https://user-images.githubusercontent.com/13222562/65277684-91345900-db7e-11e9-9247-a8640c18b35c.png)

**Comment by npetzall** [comment]
I wonder if the trusted security gets enabled or not.

Small correction of argument order moving -jar after library.path:
`java -Djava.library.path=h:\DatabaseDiagram\sqljdbc_7.4\enu\auth\x64\ -jar h:\DatabaseDiagram\schemaspy-6.1.0.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp H:\DatabaseDiagram\mssql-jdbc-7.4.1.jre8.jar -host localhost -port 1433 -db chinook -gv C:\PROGRA~2\Graphviz2.38 -debug`

We can force a known error to check if integratedSecurity is used. 
`java -jar h:\DatabaseDiagram\schemaspy-6.1.0.jar -sso -connprops integratedSecurity\\=true -t mssql08 -dp H:\DatabaseDiagram\mssql-jdbc-7.4.1.jre8.jar -host localhost -port 1433 -db chinook -gv C:\PROGRA~2\Graphviz2.38 -debug`
This should cause an unsatisfiedLinkError

I'm also unsure if the schema for Chinook is public or if it should be dbo but we will notice when we get it to login. 

Then there's the possibility that the windows account doesn't have access to Chinook database.

**Comment by junqi108** [comment]
I feel the sso option is not running in this case. the two command that you provided give the same error about the log in with user '' failed. 
![image](https://user-images.githubusercontent.com/13222562/65393332-7e669200-ddd3-11e9-97de-5f2945526ec6.png)
![image](https://user-images.githubusercontent.com/13222562/65393530-dc947480-ddd5-11e9-89e9-c7361ae4b62a.png)
I try to change the permission for this file and database, but still got the same error
![image](https://user-images.githubusercontent.com/13222562/65393493-55df9780-ddd5-11e9-85be-0f38a1b07f87.png)

**Comment by npetzall** [comment]
Wait a minute. That doesn't look like a mssql database, and that's not how you administrate permissions in sql server.

Chinook database exists for multiple dbms, the file have in the image i suspect is sqlite and not mssql.

**Comment by npetzall** [comment]
`sqlcmd -S tcp:MAR-L-427801,1433 -E -Q "select * from sys.databases"`

If that doesn't list Chinook, then Chinook is not in the mssql or as before the user doesn't have access to it.

**Comment by junqi108** [comment]
sorry, Npetzall. I mistook it as a mssql. i will close this issue and explore more. sorry.
