### ISSUE TITLE
Spark complex type map<string,string> breaks orphan diagram generation

### ISSUE THREAD

**Issue by dmoore247** [schemaspy/schemaspy#599]
## Expected Behavior
Should generate diagram and not abort

## Current Behavior
schemaspy generates .dot file with:
 ```<TR><TD PORT="customTags" COLSPAN="2" ALIGN="LEFT"><TABLE BORDER="0" CELLSPACING="0" ALIGN="LEFT"><TR ALIGN="LEFT"><TD ALIGN="LEFT" FIXEDSIZE="TRUE" WIDTH="15" HEIGHT="16"></TD><TD ALIGN="LEFT" FIXEDSIZE="TRUE" WIDTH="183" HEIGHT="16">customTags</TD></TR></TABLE></TD><TD PORT="customTags.type" ALIGN="LEFT">map<string,string>[255]</TD></TR>```
Then:
`~anaconda3/pkgs/graphviz-2.40.1-hefbbd9a_2/bin/dot -Tpng workloads_cluster_agg.1degree.dot -o x.png -Tcmapx`
Generates error:
```
Error: not well-formed (invalid token) in line 11 
... map<string,string> ...
in label of node workloads_cluster_agg
<map id="workloads_cluster_agg" name="workloads_cluster_agg">
<area shape="rect" id="node1" href="../../tables/workloads_cluster_agg.html" target="_top" title="workloads_cluster_agg" alt="" coords="5,5,175,53"/>
</map>
```
## Possible Solution
Escape the angle brackets in the `map<string,string>` data type rendering

## Steps to Reproduce (for bugs)
run `java -Xss4096k -jar schemaspy-6.1.1-SNAPSHOT.jar -t databricks -debug -s prod -vizjs -norows -loglevel config`

I'm scanning a small schema of 10 tables, one table has a complex data type with a map<string,string> data type.

## Context
I'm trying to map our production data lake, managed by spark on cloud storage. Hive/Spark table field types are supported.

* Database type : Custom Databricks (spark) type
* Database driver version: simba: SparkJDBC41.jar Spark SQL - 2.4.3 (from databricks.com)
* Your DDL (sample how to reproduce the issue):

```
CREATE TABLE table1 (date DATE, 
        col2 STRING(255), 
        col3 STRING(255), 
        col4 DOUBLE(15,0), 
        col5 STRING(255), 
        col6 STRING(255), 
        col7 BOOLEAN, 
        col8 MAP<STRING,STRING>(255), 
        col9 TIMESTAMP, 
        col10 STRING(255), 
        col11 STRING(255), 
        col12 STRING(255)
        );
```
* Full command including arguments how you run SchemaSpy:
`java -Xss4096k -jar schemaspy-6.1.1-SNAPSHOT.jar -t databricks -debug -s prod -vizjs -norows -loglevel config`

## Your Environment

* Version used:  schemaspy-6.1.1-SNAPSHOT.jar [pull from master as of last night]
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10): `18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
* Java version:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)
```

**Comment by npetzall** [comment]
We have only made spot fixes for this so we already have html escaping on a few places in the dot generation. Should probably be proactive this time and do it for anything that will be in the "html" portion of dot-file.

**Comment by npetzall** [comment]
I'll try to get a fix in tonight.

**Comment by npetzall** [comment]
This is now in master and a snapshot build will soon be finished.

https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.1.1-SNAPSHOT.jar

**Comment by dmoore247** [comment]
It ran, it generated the orphan table diagram, no errors. Schemaspy for the win!
