### ISSUE TITLE
Yellow warning about diagraming tool, no error message about diagraming failure (vizjs used)

### ISSUE THREAD

**Issue by dmoore247** [schemaspy/schemaspy#602]
## Expected Behavior
To see screen without a warning, and probably a table schema at the bottom of page.

## Current Behavior
![image](https://user-images.githubusercontent.com/1122251/65272872-f1c78580-daed-11e9-8777-b1f78fed164e.png)

Note, the diagrams on the Relationship tab work fine.

## Context
It's confusing, there were no error messages, yet bottom of page has yellow warning.
It would be less confusing for my upcoming demo not to have the warning.
`java -Xss4096k -jar schemaspy-6.1.1-SNAPSHOT.jar -schemas "x,y,z"`
with config file:
```
# This is template of configuration file for schemaspy
# Change name to schemaspy.properties and put in your working directory

# type of database. Run with -dbhelp for details
schemaspy.t=databricks

# optional path to alternative jdbc drivers.
schemaspy.dp=~/schemaSpy/

# database properties: host, port number, name user, password
schemaspy.host=w.abcefghigh.net
schemaspy.port=443
schemaspy.workspaceId=99999999999999
schemaspy.cluster=9999-999999-xxxxx999
schemaspy.db=default
schemaspy.u=token
schemaspy.p=dapi9999999999999999
schemaspy.vizjs=true

# set log level
schemaspy.loglevel=config

# turn on debug
schemaspy.debug

# disable row counting to improve performance
schemaspy.norows

# output dir to save generated files
schemaspy.o=./output

# db scheme for which generate diagrams
schemaspy.s=schema

# Uncoment to generate diagrams for all schemas in database
schemaspy.all

# Uncoment to skip creating diagrams for views
#schemaspy.noviews
```

## Your Environment

* Version used: 6.1.1 (latest pull from main, from last night)
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):
`18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
* Java version:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)
```

**Comment by dmoore247** [comment]
Same yellow banner below every table view. Orphan Table view is fine:
![image](https://user-images.githubusercontent.com/1122251/65273658-a910cc00-daef-11e9-92d5-9db8bb70a7ed.png)

**Comment by npetzall** [comment]
I've discussed this I think one time before. We don't do table diagrams if they are Orphans.

I think we ended up in a clinch regarding flag for message or just having the diagram in table page even if it's orphan. 

I was for having the diagram either way. Sort of a consistency thing, there will always be a visual representation of the diagram. 

I suspect life happened and other issues came a long. 

So which way do you lean, always diagrams or a flag to avoid the error?

**Comment by dmoore247** [comment]
Why not diagram if orphan, cause there are no relationships to show?
I'm new to this tool, and I've only analyzed a spark/hive schema which has no explicit relationships.
I work in analytics, lots/all of analytical databases won't have explicit relationships.
I like this tool can be expanded to read derived relationships from a custom table for example.

The default should be to not provide generic warning when the cause is it's an orphan table.
In a way, a diagram isn't needed because we just walked through the table fields.
The diagram adds the ability to see entire column list and types in one glance instead of pagnating 10 at a time. Let me see all columns at once I definitely won't need a diagram.
Extra flags will steepen the learning curve.

Diagram all the time would be cool too. 
Hope this feedback helps.

**Comment by npetzall** [comment]
Well, I have some kind of memory but, we do have conflicting issues #553 fixing the error and also #376

**Comment by npetzall** [comment]
The flag i mentioned isn't supposed to be used by user. It's internal so that we only give warning when we had a diagram issue.

**Comment by dmoore247** [comment]
Me too: "I'm in favor of just adding the diagram with just the single table and no relationships as mentioned by myself in #376"

Looks like this issue might be a duplicate then :)

**Comment by npetzall** [comment]
I'll close all of them before the night is over.

**Comment by npetzall** [comment]
duplicated by #376

**Comment by npetzall** [comment]
Should soon be available in a new snapshot.

> I like this tool can be expanded to read derived relationships from a custom table for example.

With schemameta you can add relationships, but I think we have two queries//calls we do to get relationships. We could have overrides for them and you would be able to get the data from the database.

As for hive, we have done a cpl changes to support it. But since most queries can be overridden. We can possibly just create a databaseType that has overrides for all queries/calls so that it uses the meta data in the hive metastore. That was an idea way back when i tried to extend the hive support.

**Comment by dmoore247** [comment]
This fixed worked, I see tables at bottom of pages, no more yellow warnings!
