### ISSUE TITLE
Authentication/Login Page before the Home Page

### ISSUE THREAD

**Issue by SanFrancesco-AI** [schemaspy/schemaspy#605]
## Question

Is it currently possible to have an HTML login page before the home page is shown?

Thanks

**Comment by npetzall** [comment]
Which homepage?
Since it's an offline html report, there is no restriction for a user to remove the "login" if one would exist.
If you want to host the report on a webserver, then it would be something to configure in the webserver.

**Comment by SanFrancesco-AI** [comment]
Ah right, I'll configure it in the webserver.
Thank you so much :-)
