### ISSUE TITLE
Link in diagram goes to wrong schema

### ISSUE THREAD

**Issue by philippe-lavoie** [schemaspy/schemaspy#608]
I have a foreign key that links a table from schema to another schema. Say table A in schema X links to table B in schema Y. So when I'm looking at X/A.html then I should be able to go to the table in /Y/B.html

## Expected Behavior
- Clicking on the diagram should go to the table in the other schema, i.e. url should be /Y/B.html
## Current Behavior
- the url is not relative to root and links to /X/Y/B.html

## Possible Solution
- prepend .. to all links to make sure you pickup the proper schema

## Context

SchemaSpy 6.1

**Comment by npetzall** [comment]
Is this with `-vizjs` or without?

**Comment by philippe-lavoie** [comment]
That's without -vizjs,

The fix is

```java
--- a/src/main/java/org/schemaspy/output/dot/schemaspy/DotNode.java
+++ b/src/main/java/org/schemaspy/output/dot/schemaspy/DotNode.java
@@ -81,7 +81,7 @@ public class DotNode {
         if (dotConfig.useRelativeLinks()) {
             return (table.isRemote() ? "../../../" + table.getContainer() : "../..") + "/tables/";
         }
-        return (table.isRemote() ? ("../" + table.getContainer() + "/tables/") : path);
+        return (table.isRemote() ? ("../../" + table.getContainer() + "/tables/") : path);

     }
```

I think that the line above the one I fixed is also wrong, i.e. `../../..` but I don't have a test case for that.

**Comment by npetzall** [comment]
I'm gonna try to setup tests for all possible cases, sadly there are three.
Graphviz with PNG
Graphviz with SVG
VizJS with SVG

**Comment by npetzall** [comment]
I did the suggested change, but then I ruined the link in the relationship diagram.
So there is a quick fix moving the relationship.html into a subfolder, which probably will cause issues with every other link.

Quick solution is to switch to `-vizjs` it uses the location of the svg file and will work.

I'll get into the refactoring tomorrow.
