### ISSUE TITLE
disable implied relationships

### ISSUE THREAD

**Issue by Tragen** [schemaspy/schemaspy#609]
Currently schemaspy finds a lot of relationships which are wrong for us.
It's a very old database and the same column names are used in many tables but are not related.

I've tried this but was sure it didn't work
        <table name="*">
            <column name="*" disableImpliedKeys="all">
        </table>

What I need is an easy way to disable all implied relationships and only use the ones I have supplied via XML.
Is this possible?

**Comment by npetzall** [comment]
https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html#html-report-related

`-noimplied`

**Comment by Tragen** [comment]
🤦‍♂️I was looking everywhere. Thanks
