### ISSUE TITLE
-renderer param is ignored

### ISSUE THREAD

**Issue by epieddy** [schemaspy/schemaspy#611]
When specifying -renderer on the command line, the value is ignored

https://github.com/schemaspy/schemaspy/blob/9569ef87b8affe5d0d329b8b829d580b1f49ef2e/src/main/java/org/schemaspy/Config.java#L997

On this line, it should be `if (renderer == null) {` instead of `if (renderer != null) {`

**Comment by npetzall** [comment]
First look it seems Strang, I'll have a look at it.
