### ISSUE TITLE
using schemaspy connect oracle, shows catalog problem

### ISSUE THREAD

**Issue by katty0924** [schemaspy/schemaspy#616]
schemaspy: schemaspy-6.0.0.jar
oralce jdbc:ojdbc6-12.1.0.1-atlassian-hosted.jar
command :java, -jar, lib/schemaspy-6.0.0.jar, -t, orathin, -dp, lib/ojdbc6-12.1.0.1-atlassian-hosted.jar, -host, 10.91.250.41, -port, 1521, -u, oracle, -p, passw0rd, -db, helowin, -o, C:\Users\pygou\output, -nohtml, -noimplied

ERROR LOG:
Catalog (-cat) was not provided and unable to deduce catalog, wildcard catalog can be used -cat %

**Comment by npetzall** [comment]
Yeah, that's a long story. In most cases adding `-cat "%"` solves the issue.

**Comment by npetzall** [comment]
Duplicate #160
