### ISSUE TITLE
Official Docker Image: Exit on Completion?

### ISSUE THREAD

**Issue by MorrisonCole** [schemaspy/schemaspy#622]
Hello!

Thank you for the fantastic project 👍 

This isn't a bug so much as a specific use case that I'm wondering if there is some supported way to implement. Essentially I want to do as follows in CI:

* Start up my database in a Docker container
* Start up SchemaSpy via the official Docker image
* Exit CI step successfully once SchemaSpy has successfully generated documentation

Right now I'm running this via `docker-compose` successfully, but I can't seem to get a hook when SchemaSpy has finished its work.

I can do some hacky things like checking for the output directory and waiting, etc., but I'd rather avoid that!

**Comment by npetzall** [comment]
I'm gonna guess that the database won't shut it self down.

So I'm gonna propose something like
`docker-compose up -d database`
`docker-compose run schemaspy`
`docker-compose down`

**Comment by MorrisonCole** [comment]
@npetzall awesome, thanks. I guess this was more a Docker question than a schemaspy one, but hopefully it'll be useful for others trying to implement something similar!

(Didn't realise that schemaspy was actually exiting at the end and could just use `run`!) 👍
