### ISSUE TITLE
Diagram producer might be missing on single table page

### ISSUE THREAD

**Issue by Octacon100** [schemaspy/schemaspy#634]
For all the single table pages for tables without any relationships, I see a "Diagram producer might be missing" warning at the bottom of the page instead of a table diagram. I'm not sure what causes this, as graphviz is installed and the diagrams are being created on the "Relationships" and "Orphan Tables" pages. It makes the documentation look like something is missing.

## Expected Behavior
It would be great to see a table diagram instead of a warning.

## Current Behavior
See the attached image.
![diagram producer missing](https://user-images.githubusercontent.com/1951510/71376937-2fc2c280-2591-11ea-8dd4-af9b97c4af60.png)

## Steps to Reproduce (for bugs)
Here's the command line call I was using:
java -Djava.library.path=C:\SchemaSpy\jdbc\sqljdbc_7.2\enu\auth\x86\ -jar schemaspy-6.1.0.jar -configFile schemaspy_Surveillance.properties -all

## Context

* Database type (e.g. MySQL): Sql Server 2017
* Database driver version (is you use a special one): jdbc 7.2
* Your DDL (sample how to reproduce the issue): N/A
* Full command including arguments how you run SchemaSpy:
java -Djava.library.path=C:\SchemaSpy\jdbc\sqljdbc_7.2\enu\auth\x86\ -jar schemaspy-6.1.0.jar -configFile schemaspy_Surveillance.properties -all

## Your Environment

* Version used: 6.1.0

* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10): Windows 10
* Java version: 1.8.0_231

**Comment by npetzall** [comment]
Hi this has been fixed I think #603. So download snapshot/latest. Link in readme

**Comment by npetzall** [comment]
It was added 2 days after the release of 6.1

**Comment by Octacon100** [comment]
@npetzall Wow that was fast. Got the latest one, looks good to me! I'll close this out.
