### ISSUE TITLE
Support for Impala

### ISSUE THREAD

**Issue by codek** [schemaspy/schemaspy#64]
(Copied from old sourceforge site)

Hi,
I tried to configure schemaspy to work against Impala, but after getting all the jdbc jars in place I hit a null pointer exception:

java.lang.ArrayIndexOutOfBoundsException: 1
at com.cloudera.hivecommon.core.CoreUtils.parseSubName(Unknown Source)
at com.cloudera.impala.jdbc41.Driver.parseSubName(Unknown Source)
at com.cloudera.jdbc.common.BaseConnectionFactory.acceptsURL(Unknown Source)
at com.cloudera.jdbc.common.AbstractDriver.connect(Unknown Source)
at net.sourceforge.schemaspy.SchemaAnalyzer.getConnection(SchemaAnalyzer.java:582)
at net.sourceforge.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:157)
at net.sourceforge.schemaspy.Main.main(Main.java:42)

Any hints?

Thanks!
Dan

**Comment by rafalkasa** [comment]
Impala JDBC driver is quite specific to use this driver with SchemaSpy to the class path more external jars must be added.

You can read more about this here on Cloudera Impala page https://www.cloudera.com/documentation/enterprise/5-9-x/topics/impala_jdbc.html#jdbc_setup

To use impala JDBC driver please set `-loadjars=true` if enabled SchemaSpy will load to the JAVA classpath additional jars used by JDBC Driver

**Comment by rafalkasa** [comment]
@codek before I will close this issue, could you verify how support for impala is working with your database ? If it is working please let me know.

You can download  [schemaspy@latest](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1-jar-with-dependencies.jar) using this link.

**Comment by codek** [comment]
Hi there, thanks very much for the quick response. I'm not on an impala project this week, but I should have access to an environment next week and I will test then and report back!

**Comment by rafalkasa** [comment]
@codek did you try to test the SchemaSpy with  Cloudera Impala ?

**Comment by npetzall** [comment]
@rafalkasa I think we have some Cloudera Impala at work. I'll check tomorrow.

**Comment by rafalkasa** [comment]
@npetzall from my perspective @codek didn't answer by last 20 days so we should close this issue.
The last version of SchemaSpy has support for Cloudera Impala jdbc driver using `-loadjars=true` paramter
