### ISSUE TITLE
Output is not correct

### ISSUE THREAD

**Issue by ahmad1995** [schemaspy/schemaspy#658]
I used schemaspy with the -visjs option and its showing only text and weird output

## Expected Behavior
the page should be viewed correctly with diagrams 

## Current Behavior
only text and some missing files like table-name.html

## Context

* Database type (e.g. MySQL): Mariadb
* Database driver version (is you use a special one):mariadb-java-client-2.5.4.jar
* Full command including arguments how you run SchemaSpy: 
java -jar schemaspy-6.1.0.jar -vizjs -t mariadb -o /root/er -host localhost -db employees -u root -p 0000 -dp /root/mariadb-java-client-2.5.4.jar -all

## Your Environment

* Version used: 80.0.3987.132
* Environment name and version (e.g. Chrome 39): Chrome Version 80.0.3987.132
* Operating System and version (e.g. Windows 10): CentOS Linux release 7.7.1908
* Java version: OpenJDK Runtime Environment (build 1.8.0_242-b08)
![Annotation 2020-03-07 102012](https://user-images.githubusercontent.com/17090398/76138993-44c1d480-605d-11ea-91c3-5fbe13d4b16f.png)

**Comment by npetzall** [comment]
It seems it doesn't load/write css/Javascript for the report.

Do you get any errors when running. 
If you open the webdevelopment tools after opening the report do you see any errors?

Does output folder contain folder bower?
Does output folder contain Schemaspy.css?

**Comment by ahmad1995** [comment]
Thank you for replying , i found out that my service is not copying every folder in the directory to the client machine, hence the page is loading incomplete files set; I resolved the issue and everything is working just fine.
Thanks again.
