### ISSUE TITLE
Its not fetching the tables with table type "memory" in embedded h2db

### ISSUE THREAD

**Issue by hazraarka072** [schemaspy/schemaspy#667]
I am trying to create the schema from in memory h2db which is part of springboot application.

## Expected Behavior
I have created custom properties file which extends from h2.properties. In the custom properties file The custom file looks like this.

extends=h2
selectTablesSql=SELECT table_name,table_catalog,table_schema, ' ' as table_comments, ROW_COUNT_ESTIMATE as table_rows FROM INFORMATION_SCHEMA.TABLES  where TABLE_SCHEMA = :schema  AND TABLE_CATALOG =:catalog

It should return all the tables from  INFORMATION_SCHEMA.TABLES with given  👍 schema  and :catalog

## Current Behavior
Only the cached tables are being fetched

## Steps to Reproduce (for bugs)

1. Start a springboot application with embedded h2database.
2. Create some table in public schema and table_type should be "memory"
3. Use the sam custom properties if you want and run schemaspy

* Database type (e.g. MySQL):h2db 
* Database driver version (is you use a special one):1.4.0

* Full command including arguments how you run SchemaSpy: java -jar schemaspy-6.1.0.jar -debug -vizjs

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):Windows 10
* Java version:1.8

**Comment by npetzall** [comment]
Just some clarification. You open the h2database after the Springboot application has exited or closed the database? Or have you embedded schemaspy in the springboot application?

**Comment by hazraarka072** [comment]
I don't have embedded schemaspy..
I am running the springboot application with embedded h2 database, then running the schemaspy jar from cmd while the application is still running

**Comment by npetzall** [comment]
From the h2 database docs it sounds like it's not supported to have database open by two processes at the same time. 

But do you get the same result if you shutdown the springboot application and then run schemaspy.

**Comment by hazraarka072** [comment]
Actually the **embedded** h2 db is up only when the application is running. And when I am running the schemaspy its fetching tables. But only the **cached**  one. Not the **_tabletype_** **"memory"**

**Comment by npetzall** [comment]
I did a test with version 1.4.200 and it works without any modification.
Also tested with your sql override and it work as well.

H2Embedded with file `/tmp/memorytable`

With your query:
TABLE_NAME |TABLE_CATALOG |TABLE_SCHEMA |TABLE_COMMENTS |TABLE_ROWS |
-----------|--------------|-------------|---------------|-----------|
TABLE1     |MEMORYTABLE   |PUBLIC       |               |0          |
TABLE2     |MEMORYTABLE   |PUBLIC       |               |0          |

Data in database
TABLE_NAME |TABLE_CATALOG |TABLE_SCHEMA |TABLE_COMMENTS |TABLE_ROWS |TABLE_TYPE |STORAGE_TYPE |
-----------|--------------|-------------|---------------|-----------|-----------|-------------|
TABLE1     |MEMORYTABLE   |PUBLIC       |               |0          |TABLE      |CACHED       |
TABLE2     |MEMORYTABLE   |PUBLIC       |               |0          |TABLE      |MEMORY       |

Just for clarification there is no TABLE_TYPE memory or cached, only STORAGE_TYPE.

I've tested embedded mode as explained here https://www.h2database.com/html/cheatSheet.html
And now I've tested server mode TCP and it works.

So if this is really a problem I need:
1, the spring.datasource.url from application.properties
2, a create table statement which doesn't show up when running schemaspy
3, the `-db` argument that you are using with schemaspy
