### ISSUE TITLE
Encoding error while creating diagrams

### ISSUE THREAD

**Issue by ydessert** [schemaspy/schemaspy#669]
While generating a pgsql database using bult-in vizjs, some of the diagrams are not rendered and an "encoding" error is show in the diagram box.

## Expected Behavior
Diagrams should be generated properly

## Current Behavior
![image](https://user-images.githubusercontent.com/5662448/79590068-bd916300-80d6-11ea-9032-d9523bc37143.png)
The content is : 
`This page contains the following errors:
error on line 63 at column 117: Encoding error
Below is a rendering of the page up to the first error.`
Part of the diagram is show below the error.

Test with -debug option do not provide relevant information.

## Context
Database type Postgresql (9.3.24)
Database driver version (42.2.12)
schemaspy-6.1.0 and schemaspy-6.1.1-SNAPSHOT
* Full command including arguments how you run SchemaSpy:
java -jar schemaspy-6.1.1-SNAPSHOT.jar -t pgsql -db mydb -host localhost -u myuser -p mypassword -dp postgresql-42.2.12.jar -s public -noads -o ./generated -vizjs

## Your Environment
* Environment name and version : Chrome 81.0.4044.113
* Operating System and version :  Windows 10
* java version "1.8.0_241"

**Comment by npetzall** [comment]
I'm guessing it's a problem with the dot-files. If you have a problem with a table that isn't sensitive could you attache its dot file. Should be located in /generated/diagrams/table/ and have the extension `.dot`. The path might a bit wrong occupied with kids so can't double check.

**Comment by ydessert** [comment]
Here are the details:
Seems the `log` table have the problem:
`error on line 64 at column 117: Encoding error``

The rendering below the error is the following:
![image](https://user-images.githubusercontent.com/5662448/79593644-1283a800-80dc-11ea-9eef-cab1a2934bb5.png)
Seems that the number of rows is not displayed. 

Attached is the .dot file.
[logs.1degree.zip](https://github.com/schemaspy/schemaspy/files/4494210/logs.1degree.zip)

**Comment by npetzall** [comment]
Had a quick look now on the phone and I don't trust the text editor to a 100%. But it look like there might be an issue with thousand separator. So you you try adding `-norows` to commandline to avoid row count and see if you still get the error. If not I know what to fix.

**Comment by ydessert** [comment]
Hi Nils,
Adding the `-norows` solve the issue.
All the table diagrams are properly generated with the option.

**Comment by npetzall** [comment]
Thanks, great. Now I know what to fix.

Note to self, we have written row count at other places. So make sure to make the consistent.

**Comment by npetzall** [comment]
@JonEgilH or anyone else having this problem with this the `-norows` solution

I'm having trouble re-creating the issue, so I need additional information.

Running `java -XshowSettings:properties` in cmd or terminal will print some useful information.
Not all properties may be printed but the parts that will be interesting for me is:
* file.encoding
* sun.jnu.encoding 
* sun.stderr.encoding 
* sun.stdout.encoding 
* user.country
* user.country.format
* user.language
* user.variant

I have found an issue where we write the SVG in the default charset and that might be different from UTF-8 which SVG should be written in. But I would like to be able to re-create the issue so that I can verify that I'm fixing your issue.

**Comment by ydessert** [comment]
Here are the properties:
Property settings:
    file.encoding = Cp1252
    file.encoding.pkg = sun.io
    sun.jnu.encoding = Cp1252
    sun.stderr.encoding = cp850
    sun.stdout.encoding = cp850
    user.country = FR
    user.language = fr

**Comment by npetzall** [comment]
@ydessert thank you and happy holidays
