### ISSUE TITLE
Typo when executing schemaspy.jar with debug enabled

### ISSUE THREAD

**Issue by JackyDFu** [schemaspy/schemaspy#673]
Executing the following in command line to see debug messages:

`D:\schemaspy>java -jar schemaspy-6.1.0.jar -debug`

But I don't see any stack trace, instead I am told again to use -debug:

`INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to see them`

When I add an extra empty space before "debug" instead, it works:
``D:\schemaspy>java -jar schemaspy-6.1.0.jar - debug`

I found this extra information in the schemaspy documentation:
https://schemaspy.readthedocs.io/en/latest/faq.html?highlight=debug

However, as mentioned above, the jar tells the user to use `-debug` instead of `- debug`.
Likewise the github faq of schemaspy tells so:
https://github.com/schemaspy/schemaspy/blob/v6.1.0/docs/source/faq.rst

## Steps to Reproduce (for bugs)
1. Provide schemaspy.jar and configuration properties;
schemaspy.t=ora
schemaspy.dp=D:\schemaspy
schemaspy.host=[host]
schemaspy.port=[port]
schemaspy.db=[db]
schemaspy.u=[user]
`omit password and provoke error to test debug parameter`
schemaspy.p=
schemaspy.o=D:\schemaspy
schemaspy.s=dbo

2. execute schemaspy with parameter `-debug` ->stack trace appears
3. execute schemaspy with parameter `- debug` ->stack trace omitted, hint use `-debug` appears

## Your Environment
* Version used: 6.1.0
* Operating System and version (e.g. Windows 10):
* Java version: JDK 8 232 (OpenJDK)

**Comment by npetzall** [comment]
Could you double check the steps to reproduce they seem to be what's expected.

Also from what shell are you executing? Cmd, powershell, git bash?

**Comment by JackyDFu** [comment]
I cannot reproduce this error anymore, so I think it might not be an error after all, never mind. Thank you for your answer and time.

I used Cmd.
