### ISSUE TITLE
is it possible to document relations between objects from different schemas?

### ISSUE THREAD

**Issue by aisbergde** [schemaspy/schemaspy#675]
## Expected Behavior

I would like to document relations between objects in different schemas.

## Current Behavior

one documentation per schema is created (that why the name is **schema**spy?

## Possible Solution

investigate relations not only inside a schema

## Context

* Database type (e.g. MySQL): MS SQL Server
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy: "-all"

**Comment by npetzall** [comment]
This is somewhat possible depending on which dbms is used. It boils down to how catalogs and schemas are structured.

If you look in the documentation there is an option `-all` and I think there is one called `-schemas` which allows for a multianalysis to be triggered. This is pretty dull tool. It creates individual reports per schema but for schema crossing relationships the links will actually work.

This can also be augmented with the Schemameta xml.

**Comment by npetzall** [comment]
The other schemas won't be available for implied relationships. I think that it would find too many false positives.

**Comment by aisbergde** [comment]
I use these 2 options. I should create a small demo database to check if in this case relations are documented.

**Comment by aisbergde** [comment]
I checked, it works:
tables in the current folder are without schema
related tables in other schema are included like SchemaName.TableName
