### ISSUE TITLE
documentation: some more information about the implementation of "Rails-based naming convention"

### ISSUE THREAD

**Issue by aisbergde** [schemaspy/schemaspy#676]
## Expected Behavior

I want to adapt my database design to be able to document virtual relations.

## Current Behavior

I have near no physical relations in my databases but a lot of virtual relations. I use the AnalyticsCreator and relations are a main concept. But these relations are not exported into the database because this is not supported by MS SQL Server. Only physical relations between tablese would be possible (and the datatype must also be the same). But the most important relations are also between views and views or between views and tables.

I am looking for some ways to document all this realations. When I see this option:  

> [-rails]
> Use Rails-based naming convention to find relationships between logical foreign keys and primary keys.

I think this could be a good idea. I found this, maybe this is related to the option?
https://guides.rubyonrails.org/active_model_basics.html
But this is not related to databases. So I would like to know what are "Rails-based naming convention" in the context of schemaspy and what exactly is implemented.

## Possible Solution

I could try to use "Rails-based naming convention"

I could also export information about relations into the database if schemaspy would be able to use this information.

**Comment by npetzall** [comment]
https://gist.github.com/iangreenleaf/b206d09c587e8fc6399e#relations-in-models

**Comment by aisbergde** [comment]
I added the link in the documentation and created a pull-request there
