### ISSUE TITLE
Minimalize layout size as much as possible, and copy all JavaScript and Html plugins localy

### ISSUE THREAD

**Issue by rafalkasa** [schemaspy/schemaspy#7]

**Comment by npetzall** [comment]
@rafalkasa What is the status on this? Done, almost done? Not started?

**Comment by rafalkasa** [comment]
@npetzall I started working on this so is almost done 😄 I decide to use bower and gulp together.
bower to manage local dependencies and gulp to minimalize layout as much as possible because bower is downloading to much stuff

**Comment by npetzall** [comment]
Ahh, bower-local branch.
