### ISSUE TITLE
-o option is ignored

### ISSUE THREAD

**Issue by LeighJoinery** [schemaspy/schemaspy#704]
I have installed all relevant drivers and get the following error under windows 10
![image](https://user-images.githubusercontent.com/44618556/82492698-86034580-9ade-11ea-810e-d526abb963d2.png)

**Comment by npetzall** [comment]
Hi

It looks like you are using the 5.0 which is 10 years old. There might be a lot of things going on there that I have no clue about. I wasn't involved in the beginning of this "continuation".

So I'm gonna do some wild guesses or at least some suggestions.

1, `"` around all paths even the output.
2, If there is some illegal character on the command line, you might narrow it down by changing the order of the arguments.
`java -jar schemaSpy_5.0.0.jar -t firebird -o .... -dp .... -u ... -p ...`  
`java -jar schemaSpy_5.0.0.jar -t firebird -o ....  -u ... -p ... -dp ....`
3, I'm not sure if it defaults to localhost for hostname in 5.0.0 could try adding `-host ...

**Comment by LeighJoinery** [comment]
Many thanks, didn't even look at the version tbh. I linked form a website
will download the latest asp

Kind Regards

Leigh Walford

-- 
JMS Pro Senior Python Developer / JMS Pro Junior C++ Developer/  JMS Pro
Testing Lead / JMS Pro Support Lead

------------------------------------------------
Joinerysoft Ltd, 21a Stuart House, Cromwell Business Park Chipping Norton.
OXON. UK
Tel: 01608 643302
Fax: 01608 643309
www.joinerysoft.com
