### ISSUE TITLE
Support for foreign tables

### ISSUE THREAD

**Issue by ferbalos** [schemaspy/schemaspy#712]
# Expected Behavior
Possibility to get not only _normal_ tables schemes but also **foreign tables** .

## Current Behavior
When trying to get the relations from a schema containing only foreign tables, schemaspy shows the following error:
```
INFO  - The following profiles are active: default
INFO  - Started Main in 0.861 seconds (JVM running for 1.157)
INFO  - Starting schema analysis
INFO  - Connected to PostgreSQL - 10.6
INFO  - Gathering schema details
Gathering schema details...(0sec)
Connecting relationships...WARN  - No tables or views were found in schema 'myschema'.
ERROR - The schema exists in the database, but the user you specified 'user' might not have rights to read its contents.
ERROR - Another possibility is that the regular expression that you specified for what to include (via -i) didn't match any tables.
WARN  - Empty schema
null
INFO  - StackTraces have been o
```

## Possible Solution
Give the user the possibility to decide if getting normal tables, foreign tables or both.

## Steps to Reproduce (for bugs)
Normal start of schemaspy to get an schema that only contains foreign tables.

**Comment by npetzall** [comment]
I checked and please correct me if I'm wrong but it's a table type in pgsql.

So what you can do is...
Create a file in the same location as the schemaspy-jar. Call it `pgsql-wft.properties`.

It should contain the following information:
```
extends=pgsql
tableTypes=TABLE,FOREIGN TABLE
```

We only look for tables of type TABLE by default but this can be extended as show above.
So you could add TEMPORARY TABLE if you want that as well.

The relevant documentation: 
https://schemaspy.readthedocs.io/en/latest/advanced_usage.html#supply-or-override-database-type
https://schemaspy.readthedocs.io/en/latest/configuration/databaseType.html
https://schemaspy.readthedocs.io/en/latest/configuration/databaseType.html#layout
https://schemaspy.readthedocs.io/en/latest/configuration/databaseType.html#other-properties

It might be useful to expose tableTypes and viewTypes as command line arguments or in the config-file that can be used.

**Comment by ferbalos** [comment]
@npetzall , thank you very much for your reply. I didn't know about that possibility, thanks for your detailed instructions and the references to the documentation.

Applying your "how to" I can get the foreign tables info, but they are stored as _orphan tables_ because Schemaspy can't get the constraints. Maybe this is due to the fact that they are foreign tables. Nevertheless, I know now how to better use Schemaspy.

> It might be useful to expose tableTypes and viewTypes as command line arguments or in the config-file that can be used.
Yes I agree.

Cheers,
