### ISSUE TITLE
Cant' connect to localhost (using the docker image)

### ISSUE THREAD

**Issue by fpuga** [schemaspy/schemaspy#715]
I have a postgresql database inside a vagrant machine with the guest port mapped to the host port 5432. I'm using the latest docker image of schemaspy (6.1).

When i try to connect using localhost or 127.0.0.1 the connection fails, but when using the `private_network` ip of the Vagrant machine it works.

So this fails:
 ```
docker run -v "$PWD:/output" schemaspy/schemaspy -t pgsql -host localhost -port 5432 -db postgres -u postgres -p postgres
ERROR - Connection error: 
Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
WARN  - Connection Failure
Failed to connect to database URL [jdbc:postgresql://localhost/postgres] Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

But this works:

```
docker run -v "$PWD:/output" schemaspy/schemaspy -t pgsql -host 192.168.100.182 -port 5432 -db postgres -u postgres -p postgres
```

Maybe this issue is related: #639

**Comment by npetzall** [comment]
I think that this is already documented on the docker hub page.

> Depending on OS you can't run with --network="host" to gain access to host with 127.0.0.1 (OSX, Windows)
So don't use loopback, you might get stuck in the container. Adding an alias for the loopback is possible and will work else use something other than localhost or 127.0.0.1.

Localhost is the container itself. This is how docker works.

**Comment by fpuga** [comment]
Oh, my fault. I miss that piece of info. Sorry a lot. Y close this.

**Comment by npetzall** [comment]
No worries, I'm gonna look over the text and see if it can be mentioned earlier.
