### ISSUE TITLE
MS SQL Server Stored procedures and Functions are not imported in html

### ISSUE THREAD

**Issue by souravduttamca** [schemaspy/schemaspy#716]
MS SQL Server Stored procedures and Functions are not imported in html

![Routines](https://user-images.githubusercontent.com/69119075/89128726-5ed0e780-d515-11ea-9e23-7dbc8380d2da.png)

**Comment by npetzall** [comment]
We have some questions when creating a new issue.

Commandline/arguments for schemaspy and which version of dbms you are using and version of schemaspy. 

This could be as simple as using `-t mssql08` or `-t mssql17` instead of `-t mssql`. But could be a totally different issue but due to the lack of information at the moment I can't tell.

**Comment by souravduttamca** [comment]
Please find the used version details below:

Schemaspy Version: schemaspy-6.1.0.jar
JDBC version for SQL Server: mssql-jdbc-7.2.2.jre8.jar
DB Type: mssql05
Graphviz2.38

Everything looks good except Stored procedures and function are not import in "Routines" tab

Thanks in advance

**Comment by npetzall** [comment]
Routines and functions were added in dbType `mssql08` so if your using MS Sqlserver 2008 or newer you can use that.

If you're stuck with an older let me know which version and I'll see if I can create the queries for SP and functions.

**Comment by souravduttamca** [comment]
I am using MS SQL Server 2012 and above.
For better understanding I am sharing you the actual syntax which I run into cmd
java -jar "D:\schemaspyGUI\schemaspy.jar" -dp "D:\schemaspyGUI\sqljdbc_7.2\enu\mssql-jdbc-7.2.2.jre8.jar" -t mssql05 -db DBPL_Kinley_Go -host localhost -port 1433 -u sa -p BAJcomCAM@1533 -o "D:\schemaspyGUI\sa_DBPL_Kinley_Go_"


I am new in SchemaSpy. Can you please help me to create new db type mssql108

**Comment by npetzall** [comment]
Just change `-t mssql05` with `-t mssql08` and it should work.

**Comment by souravduttamca** [comment]
Thanks a ton. It works.

**Comment by souravduttamca** [comment]
Hi,
I have 2 queries
1> I have several schema in database like dbo, sales, admin and many others.
How do I generate different documents for different sachemas by passing schema name.
2> User Defined Table Type(UDT) document is not generating.

**Comment by npetzall** [comment]
1, Either `-all` or `-schemas dbo,sales,admin`
2, I think UDT might still be an open issue #487

**Comment by souravduttamca** [comment]
Great. point number 1 is close. Many Thanks for prompt support.
UDT is an open issue. So I close this issue now.

Thanks for your support.
