### ISSUE TITLE
Run schemaspy with servicename and not SID

### ISSUE THREAD

**Issue by francisminu** [schemaspy/schemaspy#729]
Hi,

This is mainly a query and not an issue.
I am running the below command and i keep getting error (also shown below). Any help is apprecaited.

Command:
java -jar schemaspy-6.1.0.jar -t orathin -db service_name-s schemaName-host hostName-port 1521 -u username -p password-o outputdir -debug -dp C:/ojdbc/ojdbc7.jar

I am passing servicename as -db. I also tried passing the database name and it still fails with the same message. We make use of service name and not SID

I keep getting the error:
    ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

**Comment by npetzall** [comment]
Switch to using `-t orathin-service`

Orathin and specify -db with the servicename.

**Comment by npetzall** [comment]
Long explanation is that Orathin has host:sid where sid is specified with -db

Orathin has host/servicename where -db is servicename.

**Comment by francisminu** [comment]
Thank you so much. That worked like a charm :)

**Comment by raphaelnugas** [comment]
> Switch to using `-t orathin-service`
> 
> And specify -db with the servicename.

This works so good! Thanks friend.
