### ISSUE TITLE
Feature request: Move to GraalJS to replace Nashorn, Nashorn removed in Java 15.

### ISSUE THREAD

**Issue by nhoughto** [schemaspy/schemaspy#733]
So Nashorn has been removed from Java 15 so the viz.js feature no longer works, there should be a simple change to use GraalJS to run viz.js instead. You can pull graaljs in as a dependency and don't need to mandate users actually run GraalVM.

It would increase the size of the dependencies of users though, and you may want a separate maven target to opt-in to graaljs behaviour.. if interested i can probably PR some of it..

**Comment by npetzall** [comment]
Do you know if GraalJs will work on Java 8?
If we need to do two builds Java8 and Java 15 where 15 might be a bit bigger.

Haven't even tried building on 15 will be interesting.

**Comment by nhoughto** [comment]
Yep GraalJS runs on Java 8

it will be the same size on both, as you just pull it in as a regular dependency, https://mvnrepository.com/artifact/org.graalvm.js/js/20.2.0

**Comment by npetzall** [comment]
With size I was thinking a java8 build without and java15 build with.

But I checked and it's serviceloaded as a scriptEngine. So might be possible to change a bit of classpath and instructions to download and put in a sibling directory and it's available.

Worst case, we could run the viz.js with it's own classloader and we add ./js-*.jar to that classloader and use it.

**Comment by nhoughto** [comment]
ah right yeah i just thought you'd migrate the whole thing to graaljs in all versions, then just have a maven target for schemaspy+vizjs that bundles graal and remove the nashorn code entirely..

**Comment by npetzall** [comment]
Without testing i believe that the following might work
Replace the normal start 
`java -jar schemaspy-6.1.1-SNAPSHOT.jar`
With
`java -cp schemaspy-6.1.1-SNAPSHOT.jar;js-20.2.0.jar org.springframework.boot.loader.JarLauncher`

Separator between the jars is OS-dependet `:` on linux and `;` on windows.
But I admit, I haven't used java15 so don't know if they have totally changed that so it should be some kinde of module path.

I guess I have to download and test it.

**Comment by nhoughto** [comment]
ah ok yep that could work

This also seems like a option? rather than solving it all yourself, let the library make graphviz work cross platform - https://github.com/nidi3/graphviz-java

**Comment by npetzall** [comment]
We/I looked at graphviz-java like 2 years a go, might need to take another look.

But the complex code is the generation of dot-lang files and not executing graphviz or viz.js and graphviz-java has a model for the language.

**Comment by nhoughto** [comment]
yeah didn't look into it deeply, was just thinking it seems like there are more efficient options than shelling out to `dot` binary or running viz.js. You wouldn't want to refactor the dot modelling stuff, just how 'graphviz' is expected to be run.

**Comment by mprins** [comment]
add another 16MB to the runtime jar #277

**Comment by npetzall** [comment]
@mprins I'm leaning towards opt in by downloading if your on Java15 which has no Javascript engine and only if you want viz.js

**Comment by npetzall** [comment]
Just an update, since I've been looking into this.

There are some issues with using GraalJS, it's pretty slow and going full blown GraalVM is not currently not on the map.
Both GraalJS and standalone Nashorn are built around JPMS.

So I'm going to focus on moving to Java 11 and JPMS. After that I'll look into how we can split out vizjs and script ending to an optional module/distribution.

**Comment by npetzall** [comment]
We got a pulled request to include nashorn.

So instead of moving to GraalJS we have included the standalone nashorn.

With the snapshot `-vizjs` will work on newer Java version.

For now its a single slightly larger jar file.
