### ISSUE TITLE
Docs: Document where to Download Missing JDBC Drivers, such as for Postgres

### ISSUE THREAD

**Issue by allella** [schemaspy/schemaspy#747]
## Expected Behavior
I assumed the latest drivers would be pre-installed.

## Current Behavior
When I ran the one-liner on a Postgres connection it returned:

> There were missing paths in driverPath:
> 	/org/schemaspy/drivers/postgresql-9.4.1208.jre6.jar
> 

However, I was able to resolve this by manually tracking down [a proper driver](https://jdbc.postgresql.org/download.html) and using the -dp flag.

## Possible Solution
Was my experience an edge case, or is this likely to happen to anybody using Postgres?

Or, is there's already documentation on this that I missed? If so, I feel it could be better promoted because I looked through the entire [Docs](https://schemaspy.readthedocs.io/en/latest/index.html) and this Github repo directories and ended up having to figure it out myself based on prior experience.

In any case, I'll offer to help add basic document about how to locate a proper JDBC drivers in the event there's a failure.

For example, the latest [JDBC Postgres driver](https://jdbc.postgresql.org/download.html) worked by adding the flag `-dp postgresql-42.2.19.jar`

## Context
When I received an error I turned to the docs, but didn't see anything about how to source the correct driver.

I then assumed the drivers could be found in the Github repo, but didn't locate them.

I decided to do an online search for "JDBC Postgres" because I'm familiar with ODBC concepts from work in the early 2000's with MS Access. Luckily, I landed on [the page](https://jdbc.postgresql.org/download.html) that happen to have the file I needed.

However, I don't know if many new web developers know about JDBC and would quickly figure out that they needed to manually find and download a JDBC driver.

**Comment by npetzall** [comment]
This a tricky problem, if we include the drivers we need to update them, and if an older database is used how should that be handled.

DBBeaver has an interesting solution it gives the option to download drivers when creating the connection to the database. But it would require some maintenance to keep the download options available.

But you're right the docs needs updating, either a generic statement in the "requirements" section. We have a docker image that includes drivers but they have become old already. Hence the maintenance issue. 

If we would keep all the drivers for all supported databases, there would probably be a new release of SchemaSpy a week.  Since we have a generic support for jdbc and any database(users can build their own support). Many of the configurations that we supply with SchemaSpy are user contributed.

But the problem isn't actually just web developers but any developer that isn't a Java/JVM developer might not know about JDBC.

> **Requirements**
> No JDBC driver is included with the jar-distribution of SchemaSpy. So you need to fetch one yourself. Under normal circumstances this should be as simple as search the internet for "[database managements system] JDBC driver". Make sure to verify that the driver is compatible with version of dbms that you are using .

**Comment by allella** [comment]
@npetzall thanks for the reply and work.

I understand the trouble of keeping things up to date.

Is the "**Requirements**" quote you shared part of the documentation? I didn't see that earlier and can't find it while searching around.

If we could add that requirement to the [requirements on the doc](https://schemaspy.readthedocs.io/en/latest/installation.html#requirements), then that would be a great first step.

That page currently says ,

> you must have installed two things in your system environment.

and that likely contributed to my initial confusion, since it sounds like there are three requirements:
- Java
- downloading an appropriate JDBD driver
- GraphViz (for v6.0 or less)

As a secondary improvement, if there was a list to drivers download page / instructions for the various supported engines, then that would likely avoid much of the maintenance and still put it on the user to find their proper driver version.

If you're interested in trying to compiling a list of links, then I'd be glad to contribute. For instance, just doing a quick search on the engines I use, I suspect these could reasonable landing page for the Schemaspy user, which don't frequently change.

- [MySQL](https://www.mysql.com/products/connector/)
- [MariaDB](https://downloads.mariadb.org/connector-java/)
- PostgreSQL(https://jdbc.postgresql.org/download.html)

**Comment by allella** [comment]
If you'd like, I can submit a pull request with the suggestions above.

I assume I could submit changes for https://github.com/schemaspy/schemaspy/blob/master/docs/source/installation.rst
?

**Comment by npetzall** [comment]
No, it was my suggestion. We can combine the suggestion with the links. That's the correct file, changes are really appreciated, thanks.

**Comment by allella** [comment]
PR #748 takes a crack at adding this requirement and a list of links for many of the supported engines.

I obviously didn't test or validate all the JDBC drivers, but this may be a case where any list is better than no list. At least it will give people an idea of where they might find the driver.

https://github.com/allella/schemaspy/blob/docs/update-install-requirements/docs/source/installation.rst
