### ISSUE TITLE
Typo error on website

### ISSUE THREAD

**Issue by garry** [schemaspy/schemaspy#749]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Database type (e.g. MySQL):
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):
* Java version:

Here you will find more detials about SchemaSpy option and configuration - In this line typo error about details, please change

**Comment by npetzall** [comment]
Fixed in schemaspy/schemaspy.github.io@8b8009e19202ef36ec3d184a33e6ce9958280e0a
