### ISSUE TITLE
Bumps

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#751]
- [x] Switch to build on Java 11 (sonar doesn't support 8) (will probably effect maven) 
> The version of Java (1.8.0_252) you have used to run this analysis is deprecated and we stopped accepting it.
Please update to at least Java 11. You can find more information here: https://sonarcloud.io/documentation/upcoming/
- [x] Bump test containers
* Seems ability to make assumptions about docker is available both in junit4/5 for testcontainers.
- [x] Bump/Upgrade to junit5
- [ ] Decide on switching to gradle
- [ ] Check other dependencies for newer versions
- [x] Build using Github Actions instead of Travis-ci

**Comment by npetzall** [comment]
Travis has no good solution for the docker-hub rate-limit. Since we don't want to spread credentials to forks.

GitHub Action has a free rate GitHub runners. So we should probably move to GitHub Actions.

**Comment by npetzall** [comment]
So just tested, Github Actions is the way to go.
I'll see how much I can migrate without @rafalkasa
Shouldn't be a problem, I have access to most of the external systems we use.
So I'll create my own tokens for sonarcloud and docker-hub.
As for publishing the github action already has access to the repo with an included token which is nice.

Past midnight, continue tomorrow I hope.

**Comment by npetzall** [comment]
Been sick for about 7 days. Still sick.

Todo:
* Deploy snapshot to gh-pages (unless there is something better)
* Build/Deploy docker-hub snapshot
* Deploy release to releases
* Build/Deploy docker-hub release

I have create a release-ready plugin for Github Actions that could be used if a version kan be extracted from the build. I've done it successfully with gradle and shipkit-autoversion. Which sadly i find is a good reason to migrate to gradle.....

**Comment by npetzall** [comment]
Publishing to packages seems easy and straight forward.
Same goes for docker build/publish.

However I'm a bit concerned with the releasing, it's a bit cumbersome and it want to do more of a CI/CD.

Packages has a restriction that packages that have been downloaded more than 25 times can't be deleted without contacting support and packages are limited to 500 MB.

I'm guessing that snapshot allows overwriting. But snapshotting goes against my principals regarding CI/CD. 
We always build a potential release so there is no room for snapshots.

However having a new version for each build requires link in readme to be updated. 

If we skip packages and publish to pages and are able to create a link to the actual built version that would be a reasonable workaround. That needs verification.

Then we could just have a draft waiting, implement require a commit message convention to have it auto generated.

**Comment by npetzall** [comment]
The progress of github actions migration is available https://github.com/npetzall/schemaspy/tree/github_actions
Readme has been updated to use a download.html that will download the development build.

https://github.com/npetzall/schemaspy/tree/github_actions/.github/pages contains the download "code".
https://github.com/npetzall/schemaspy/blob/github_actions/.github/workflows/npetzall.yml#L50-L66 contains the latest.json creation and the deployment to gh-pages.

So maintenance of latest is removed so a no issue if we switch to CD.

**Comment by npetzall** [comment]
May have been noticed but development and PRs are now handled by github actions.

**Comment by rafalkasa** [comment]
@npetzall it sounds as a lot of work you already have done, thank you for that 👍 🥇

**Comment by npetzall** [comment]
Bump of test containers #846

**Comment by npetzall** [comment]
Bump/Support junit5 #815

**Comment by npetzall** [comment]
Closing this since there are too many unrelated things, it was a bad issue to begin with.
But for reference, 
* no decision on gradle (it's not a question at the moment so, stay with maven)
* check dependencies for updates (should be continuous work)
