### ISSUE TITLE
Summary not showing

### ISSUE THREAD

**Issue by cheoAlejo** [schemaspy/schemaspy#76]
The nice summary shown in your sample doesn't show with my database.
Is there any configuration to tweak ?

**Your sample:**
![2017-05-03 13_19_52-chinook database](https://cloud.githubusercontent.com/assets/10518807/25675305/a19010f6-3003-11e7-8831-1b46e5b5ad78.png)

**My docs:**
![2017-05-03 13_18_56-zz_modelo_kernel database](https://cloud.githubusercontent.com/assets/10518807/25675332/b3b607e0-3003-11e7-9dc8-934b364b410b.png)

I'm using a mysql database.

**Comment by rafalkasa** [comment]
@cheoAlejo this new summary will be available in version rc2 which will be released to the end of May.
I know that many users can't wait so long :-) I'm already working on solution that each time when new PR will be merged with master new version of schemaspy@latest will be deployed to the gh-pages branch.

You can download  [schemaspy@latest](https://github.com/schemaspy/schemaspy/raw/gh-pages/schemaspy-6.0.0-rc1-jar-with-dependencies.jar) using this link.

**Comment by cheoAlejo** [comment]
Thanks for the answer.
