### ISSUE TITLE
Full schema diagram including relationships and orphan tables

### ISSUE THREAD

**Issue by marcelstoer** [schemaspy/schemaspy#763]
This branched off from #376 where @vlehm, @AndreKR and I seem to have requested the same feature.

## Expected Behavior
SchemaSpy should generate a complete visual representation of "the schema" (a vague term).

## Current Behavior
SchemaSpy generates one diagram showing relationships and a dedicated PNG/SVG file for every orphan table.

## Possible Solution
A) Include all orphan tables in the "Relationships" diagram. Easy to reason about as even orphan tables somehow fall under the relationships category as there are "_no_ relationships" to such tables. Maybe give users an option to turn this behavior off (enabled by default).
B) Keep "Relationships" and "Orphan Tables" as is but introduce a new aggregated diagram. I could live with that but I see little value in that.

## Context
We are automatically generating SchemaSpy diagrams in the build pipeline to include in the @antora documentation for several dozen projects: create an H2 file-based database, run Liquibase changeset against it, run SchemaSpy against it, copy SchemaSpy diagram files to documentation folder, Git-commit changes.

**Comment by npetzall** [comment]
Since we are back in development.

I'll say Option A, it might become cluttered, but then again that is the database design.

**Comment by marcelstoer** [comment]
Exactly 😄 If the database design is cluttered, so should be the SchemaSpy diagram.

Is this as easy as simply _not_ filtering out orphan tables?

**Comment by npetzall** [comment]
I hope so, from the looks of it. It would just mean remove the filtering, add filtering if Orphans is turned of in relationships.

**Comment by renannprado** [comment]
it would be really great if we could have it

**Comment by npetzall** [comment]
@jesperolsson-se you've done stuff in this area, can you look into this?

**Comment by jesperolsson-se** [comment]
I agree with (A) and think that orphans should be included in `Relationships` by default, even if that's a breaking change.
1. The current implementation is awkward when the database lacks real relationships but SchemaSpy identifies a dozen or so implied relationships.
2. Orphan tables are a special case of _graph partitions_, but that concept isn't included (yet).
