### ISSUE TITLE
Broken link on home page

### ISSUE THREAD

**Issue by pabloab** [schemaspy/schemaspy#796]
On [schemaspy.org](https://schemaspy.org/) > Get Started (first section) > Tutorial (third column)

> This is short description about the tool and how to use it. Please read more [here](http://schemaspy.readthedocs.io/en/latest/home.html#what-is-schemaspy).

"[here](http://schemaspy.readthedocs.io/en/latest/home.html#what-is-schemaspy)" is a broken link.

**Comment by rafalkasa** [comment]
@pabloab thank you for let us know the problem was solved with broken link
