### ISSUE TITLE
Feature Request - Release SchemaSpy as library jar file (non bootjar)

### ISSUE THREAD

**Issue by rolfhub** [schemaspy/schemaspy#800]
I'm using SchemaSpy inside a JUnit test to connect to a DB that is started via [test-containers](https://github.com/testcontainers/testcontainers-java). So that SchemaSpy is generating a report as part of my build. That works pretty well, only the packaging is a currently a little bit inconvenient for this setup. At the moment I'm extracting all files contained in the BOOT-INF folder of the schemaspy.jar and repackage them into a "simple" jar File that can be included afterwards as test dependency into my build.

Would it be possible for you to provide a "simple" non boot jar file with every release? And would it be possible to add that to maven-central?

**Comment by marcelstoer** [comment]
Can this be closed then?

**Comment by npetzall** [comment]
Closing, duplicates #157 and #277
