### ISSUE TITLE
Log4J vulnerability

### ISSUE THREAD

**Issue by projectje** [schemaspy/schemaspy#803]
It's not clear to me if this affects schemaspy since it references

\log4j-api-2.11.1.jar
\log4j-to-slf4j-2.11.1.jar

ref: https://logging.apache.org/log4j/2.x/security.html#:~:text=Fixed%20in%20Log4j%202.15.0

**Comment by npetzall** [comment]
From the ref
>  the only mitigation is to remove the JndiLookup class from the classpath: zip -q -d log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class.

We don't have the core-library, we use logback.

The two libraries are to handle libraries written with log4j, so that instead of logging with log4j it's sent over slf4j and end up in logback.
