### ISSUE TITLE
Help: I can't connect to local SQL Server 2019 database with instanceName (connection failed)

### ISSUE THREAD

**Issue by NilkOne** [schemaspy/schemaspy#829]
Hello,

When I try to connect to local SQL Server 2019, I get SSL error.

## Expected Behavior

I would like to use SchemaSpy and success to connect to SQL Server.

## Current Behavior

This is error that I get : 
```
Failed to connect to database URL [jdbc:sqlserver://localhost:1433;databaseName=BlazorPlan] 
Echec de la connexion TCP/IP Ó l'hôte localhost, port 1433. 
Erreur": "connect timed out. Vérifiez les propriétés de connexion. 
Assurez-vous qu'une instance de SQL Server est en cours d'exécution sur l'hôte et accepte les connexions TCP/IP au port. 
Vérifiez que les connexions TCP au port ne sont pas bloquées par un pare-feu."
```

## Steps to Reproduce

1. Run this command line
```
java -jar .\schemaspy-6.1.0.jar -t mssql08 -host localhost -db BlazorDB -u user -p pwd -dp .\mssql-jdbc-10.2.0.jre11.jar -o .\doc -connprops instanceName\\=SQL_ABC_19
```

## My Environment

* Version used: [schemaspy-6.1.0.jar](https://github.com/schemaspy/schemaspy/releases)
* Server version: Microsoft SQL Server 2019 - 15.0.2080.9 (X64)  
* Operating System: Windows 10
* Java version: 11.0.12
* JDBC version : [mssql-jdbc-10.2.0.jre11.jar](https://github.com/microsoft/mssql-jdbc/releases)

**Comment by npetzall** [comment]
`instanceName\\=SQL_ABC_19`

Double `\\` is only required on Linux and git bash on windows. Single should work in windows cmd.

**Comment by npetzall** [comment]
when i comes to SQL server make sure that the TCP/IP listener is configured. It used to be an issue with SQL Express installations.

**Comment by NilkOne** [comment]
Thank you,
it is strange but default port doesn't work on my local instance (SQL Server Express), 2 solutions : 
* comment this line `#schemaspy.port=1433`
* or use this [doc ](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-ver15)to specify the TCP port for IPAll (and restart the SQL Server service)
