### ISSUE TITLE
Is it possible to use multiple schemes ?

### ISSUE THREAD

**Issue by NilkOne** [schemaspy/schemaspy#830]
## Expected Behavior
Hello,

I would like to use multiple schemes.

My databse contains multiple schemes like : 
* dbo
* Identity
* HangFire
* ...

How to generate a documentation for all shemes and not only one by one ?

**Comment by npetzall** [comment]
https://schemaspy.readthedocs.io/en/latest/configuration/commandline.html#processing

**Comment by NilkOne** [comment]
Thanks
`-all` command line option is what I need
