### ISSUE TITLE
New Release? 

### ISSUE THREAD

**Issue by Ashtonian** [schemaspy/schemaspy#837]
Can you tag a new release and release it ?

**Comment by marcelstoer** [comment]
https://github.com/schemaspy/schemaspy/compare/v6.1.0...master shows that 350+ commits across 450+ files have landed on `master` since 2019-09. Why no releases since? Makes me worried that whatever version comes next is going to be a beast to verify.

**Comment by xenomachina** [comment]
Are there plans to make new releases? Do the maintainers need any help with this issue? 3 years is a _long_ time to go without a release, especially when so many improvements have been made since then.

**Comment by marcelstoer** [comment]
Should be closed as 6.2.0 is out now.

**Comment by rafalkasa** [comment]
@npetzall amazing job and I'm proud from all what you are doing for the project. 👏👏👏💪💪💪

**Comment by npetzall** [comment]
@rafalkasa Thanks but I'm not alone, we have a great community, issues are reported so we can improve, we have users answering other users question, we have contributors spending their free time to help improve SchemaSpy. We should be proud of all of them

**Comment by npetzall** [comment]
So we have 6.2.0 and 6.2.1 and hopefully a 6.2.2 tomorrow.
