### ISSUE TITLE
Graphviz version 3.0 released

### ISSUE THREAD

**Issue by mat813** [schemaspy/schemaspy#844]
## Expected Behavior
Expecting schemaspy to still work ;-)

## Current Behavior

org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version

## Steps to Reproduce (for bugs)
1. Install graphviz 3.0
2. run schemaspy

## Your Environment
* Version used: 6.1.0
* Environment name and version (e.g. Chrome 39): Arch Linux
* Operating System and version (e.g. Windows 10): Arch Linux
* Java version: openjdk 17.0.3 2022-04-19

**Comment by npetzall** [comment]
I've done a quick test with 3.0.0 and I've tried to read the changelog seems to be breaking changes regarding plugins and C-API. So this should not impact SchemaSpys usage.

I've created a pull request once it's in merged you can test it out by using the snapshot build which is linked in the readme.md
