### ISSUE TITLE
Create a brand/umbrella for SchemaSpy on snapcraft.io

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#851]
@rafalkasa since you own the github organization I feel that you should own the brand/organization on snapcraft.io

If additional member can be added, you can add me at least.

This is in relation to #710 and #845

**Comment by rafalkasa** [comment]
@npetzall I will it create today evening and include you as always thank you 😊

**Comment by rafalkasa** [comment]
@npetzall https://dashboard.snapcraft.io/snaps/schemaspy/ is currently created and share with you
