### ISSUE TITLE
Issue when use in bigquery

### ISSUE THREAD

**Issue by jackklpan** [schemaspy/schemaspy#878]
Hi,
I follow the https://github.com/schemaspy/schemaspy/issues/737#issue-734683162 to use schemaspy in bigquery.
Most tables and views are shown normally.
However, if the table is from google spreadsheet it is not shown in the schemaspy.
For example:
![截圖 2022-05-26 上午11 56 38](https://user-images.githubusercontent.com/6631491/170413142-46152d18-8f52-4240-a5ed-46050ae6f51d.png)

What might be the possible reason or any context I should provide more?
Thanks!

**Comment by npetzall** [comment]
The first thing that comes to mind is that it might be returned as a table subtype. We default to query for TABLE as type, but it could be that spreadsheets has a different type.

I need to double check how it's used and if there is a quick way to check which if any types needs to be added.

**Comment by jackklpan** [comment]
Thanks for the quick reply!
I use the [lnk](https://cloud.google.com/bigquery/docs/information-schema-tables) to check the bigquery table type.
It shows `external` if it's from spreadsheets. (The `view` type can be shown correctly in schemaspy)
However, I am not sure is this the same as the type you mentioned.
![截圖 2022-05-27 下午12 54 37](https://user-images.githubusercontent.com/6631491/170632246-494cd43b-7c37-4535-8245-1ba4f4993f95.png)

**Comment by npetzall** [comment]
A possible solution might be to add tableTypes in your databaseType file. 

```
tableTypes=TABLE,EXTERNAL
```

**Comment by jackklpan** [comment]
Thanks! It works!
And also need to add `RequestGoogleDriveScope=1;` to the `connectionSpec` for other people reference.
