### ISSUE TITLE
Refactor and remove WriteStats

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#893]
Proposal

Make Graph comparable or implement equals.
Return Graph from DotTableFormatter all the way back to MustacheTableDiagramFactory.

Instead of using WriteStats, compare the two Graphs.

**Comment by jesperolsson-se** [comment]
I agree that this would be an improvement. It can definitely be implemented now, even if we end up removing the comparison later.

The bigger question is why the entire thing is needed. What need we are trying to satisfy by asking the graph if it is identical to another. Quite often, it's more appropriate to let the object do the thing or collaborate on a higher level of abstraction. (Consider the graphs (in-)equal. What do you want to do next?)

In this particular case, `MustacheTableDiagramFactory` has a lot of weird logic ([perma-link](https://github.com/schemaspy/schemaspy/blob/ec07a6d661978c876a468880a03a3a23e23b8bd0/src/main/java/org/schemaspy/output/html/mustache/diagrams/MustacheTableDiagramFactory.java)), so I suspect that if we sort that out we'll no longer need to know about equality.

**Comment by npetzall** [comment]
I think the current behavior is inherited, so there is probably no real reason or some thing like it's more evident that there is no second degree of relationships when it's missing than when they are identical.

If we are gonna be totally honest the most correct way would be to avoid creating the graph to begin with. Since the graph shouldn't know if the table has relationships that are of the 2nd degree.

The write equals is used twice and the second should use the table hasImplied(int degrees).

So adding a hasExplicit(int degrees).

Should solve this as well and it would increase the confidence that separation of parent/child is less used. But still needs to be investigated in #886

**Comment by jesperolsson-se** [comment]
This suggestion makes sense to me, and provides a clear direction. I believe it's feasible.

Effort is, however, likely higher than expected. The representation of implied relationships is a bit all over the place so a lot of code will need to be unraveled. It isn't just on the code level, but very much a design question of how to assign responsibilities. Still, pretty much every small improvement will contribute to maintainability and testability by itself, so I'd say it's mostly a priority decision.

**Comment by npetzall** [comment]
I miss spoke about implied not having a different connecting line. Implied currently has a dashed line.
https://github.com/schemaspy/schemaspy/blob/90ac4f8d4552337f203a5ca843526c58bd5e6e00/src/main/java/org/schemaspy/output/dot/schemaspy/Edge.java#L147-L148

So it really just feels like skipping the real generation and only having the generation with implied 1st and 2nd degrees.

For summary there might be lots of relationships. Where implied can probably destroy the diagram(too much data).

With this change the only way to get diagrams without implied would be with the argument `-noimplied`. If implied are a problem this option should already be used, or the `-degrees` argument.

**Comment by npetzall** [comment]
WriteStats has been removed in #894.

The issue regarding Table diagrams has been moved to issue #904
