### ISSUE TITLE
Don't use @Autowire in application classes

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#91]
I propose that we move all wiring into `@Configuration` classes. Limit the ComponentScan to only scan a subpackage configuration.

In `@Configuration` class one would be free to use `@Autowire`.

Reason for this is to expose dependencies as constructor arguments which is easy to mock instead of private fields, classes will also not depend on spring.

**Comment by Riggs333** [comment]
+1 for using **constructor injection** in every bean instead of field injection and therefore removing the use of `@Autowired` annotation.

I do not see a benefit in having configuration classes (besides the `Main` class) yet. Could you explain on it a little bit more or give an example?

**Comment by npetzall** [comment]
You could skip component scanner completely and just use the Main.class, but sooner or later your gonna get a merge conflict you didn't want.

So using multiple configuration classes is for decoupling. Say we wanna split one of the services that are 500+ rows. Depending on the level of decoupling it would require multiple updates in one single config shared by all services. Say we are more than one doing similar work on another service.

**Comment by rafalkasa** [comment]
fixed #101 by @Riggs333
