### ISSUE TITLE
Travis-CI doesn't run integrations tests

### ISSUE THREAD

**Issue by npetzall** [schemaspy/schemaspy#93]
failsafe-plugin that runs integration tests is bound to verify phase.
travis only runs clean package, package is the phase before verify.

**Comment by aadrian** [comment]
> travis only runs clean package, package is the phase before verify.

Those are only defaults if nothing is configured. One can configure it however to a desired command: https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step

**Comment by npetzall** [comment]
@aadrian First I thought you would say something about jCommander.

The fact is that the .travis.yml executes the travis.sh in the repo. Which only runs clean package.
So it should be a small thing to fix.

I'm gonna fixit tomorrow, if it's not fixed. I just need a reminder.

**Comment by npetzall** [comment]
Fixed in #92
