### ISSUE TITLE
CodeCache is full. Compiler has been disabled.

### ISSUE THREAD

**Issue by JRFoulkes** [schemaspy/schemaspy#932]
## Expected Behavior
Output files

## Current Behavior
Writing/graphing summary.INFO  - Gathered schema details in 3 seconds
INFO  - Writing/graphing summary
.Java HotSpot(TM) Client VM warning: CodeCache is full. Compiler has been disabled.
Java HotSpot(TM) Client VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
CodeCache: size=32768Kb used=28660Kb max_used=30988Kb free=4107Kb
 bounds [0x02140000, 0x04140000, 0x04140000]
 total_blobs=3295 nmethods=3020 adapters=203
 compilation: enabled

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
java -jar schemaspy.jar -vizjs

config file:

# type of database. Run with -dbhelp for details
schemaspy.t=mssql08-instance
# optional path to alternative jdbc drivers.
schemaspy.dp=C:\Users\Downloads\schemaspy\driver\Microsoft JDBC Driver 7.2 for SQL Server\sqljdbc_7.2\enu
# database properties: host, port number, name user, password
schemaspy.host=DESKTOP
schemaspy.instance=APP
schemaspy.db=name
schemaspy.u=user
schemaspy.p=password
# output dir to save generated files
schemaspy.o=C:\Users\Downloads\schemaspy\output
# db scheme for which generate diagrams
schemaspy.s=dbo

**Comment by npetzall** [comment]
Hi, which version of Java are you using.

Memory management has changed between versions so it's good for us to know.

I suspect that it's the vizjs and nashorn that is filling the code cache.

Possible options are to increase the code cache

* Add `-XX:ReservedCodeCacheSize=64m` this could be lower current seems to be 32m, should be 48m.
* Enabled CodeCacheFlushing, if it's disabled `-XX:+UseCodeCacheFlushing`

There is also a possibility that you are using an older Java like 8.
Java 11 has enabled more memory ergonomics, so the CodeCache adjusted.
Checking my Java 11 installation I have CodeCacheFlushing enabled, and the ReservedCodeCacheSize is 256m.

**Comment by JRFoulkes** [comment]
Thanks @npetzall I installed Java 11 and it worked without issue.
Just to note I installed Java 8 as per the documentation, I assume that is out of date now, sorry I am no familiar with Java or this tool but I am happy with the outcome!

Thanks again.
