### ISSUE TITLE
Table column comments not appearing

### ISSUE THREAD

**Issue by svha1de** [schemaspy/schemaspy#94]
I have comments on columns in my Oracle database. SchemaSpy 5.0 has picked them up correctly, but 6.0.0-rc1 does not, they appear blank in the html output. I am running on exactly the same schema and DB, the only change is the jar file used, and the issue is repeatable, i.e. occurs in 100% of the cases.
I am running against Oracle 12c, using the thin driver. My Java version is  1.8.0_131-b11.
Output on V5:
![image](https://cloud.githubusercontent.com/assets/28760504/26162337/c6becd62-3b26-11e7-9a77-0880f13d9e38.png)

Output on V6:
![image](https://cloud.githubusercontent.com/assets/28760504/26162383/eaf90c10-3b26-11e7-84d5-4558cc6f23fc.png)

Clicking the Comments buttons shows/hides the column for comments, but the column is still empty.

**Comment by npetzall** [comment]
If I didn't do anything with the database setup.
Comments should be available in the internal representation of the database.
I haven yet produced any html or such.

**Comment by svha1de** [comment]
If I run with the -nohtml option, I get the XML representation, but it does not contain the comments either.
Comments as seen in SQLDeveloper:
![capture1](https://cloud.githubusercontent.com/assets/28760504/26309694/45307c38-3efe-11e7-8eec-9b84b97430f2.PNG)
No remark in XML:
![capture2](https://cloud.githubusercontent.com/assets/28760504/26309732/7487588a-3efe-11e7-8e7a-ba18e81e28cb.PNG)
For completeness, the XML model as well is attached

[orcl.CEMDB.xml.zip](https://github.com/schemaspy/schemaspy/files/1018853/orcl.CEMDB.xml.zip)

**Comment by svha1de** [comment]
If I run the V5 schemaspy with the -nohtml option, it does pick up the remarks
![image](https://cloud.githubusercontent.com/assets/28760504/26357871/f64d9636-3fd0-11e7-86fa-1461b026f5a1.png)

Again, XML model is attached
[orcl.CEMDB-schemaspy-5.xml.zip](https://github.com/schemaspy/schemaspy/files/1022381/orcl.CEMDB-schemaspy-5.xml.zip)

Thanks a lot for looking into the matter, highly appreciated!

**Comment by npetzall** [comment]
@rafalkasa @svha1de 
This seems to have be fixed since rc1.
I backported my oracle test to rc1.
ShouldBePopulatedWithTableTest OK
ShouldBePopulatedWithTableTestAndHaveColumnName OK
ShouldBePopulatedWithTableTestAndHaveColumnNameWithComment Failed

**Comment by npetzall** [comment]
Hmm, got it working in rc1.
It's an inconsistency in how it retrieves the schema.

@svha1de Are you using -s, -schemas, -schemata or -all and with what arguments?

**Comment by svha1de** [comment]
My complete command line looks like this:
`java -jar schemaspy-6.0.0-rc1.jar -t orathin -host ora12c.local -port 1521 -db orcl -u CEMDB -p stmsfmw1 -o bug -dp ojdbc6dms.jar;dms.jar;ojdl.jar;orai18n.jar -hq -gv "c:\Program Files (x86)\Graphviz2.38" -norows -loglevel fine -nohtml`

**Comment by npetzall** [comment]
@svha1de could try adding -s CEMDB

**Comment by svha1de** [comment]
Excellent! This does the trick!
![image](https://cloud.githubusercontent.com/assets/28760504/26540622/8630bba4-4452-11e7-85d6-8a2650aaa315.png)

You rock! Thanks a lot for helping with this (and for picking up this great tool for further development)

**Comment by npetzall** [comment]
I'll dubbel check that this is solved later in 6.0.0 else we have a new usecase to handle @rafalkasa

**Comment by anilchaurasiya** [comment]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/66078010/123669710-ff30a880-d859-11eb-8e9a-488c62af016c.png">

**Comment by anilchaurasiya** [comment]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/66078010/123669815-212a2b00-d85a-11eb-9be8-7fe66d20e9a6.png">

I am unable to get comment in the documentation while using SchemaSpy as highlighted in this screenshot.
Provide the solution for this issue. 
I am using this command :
 java -jar schemaspy-6.1.0.jar -configFile ./Schemaspy.properties -o Output

**Comment by npetzall** [comment]
@anilchaurasiya create a new issue this is 5 years old. In new issue please provide database engine and versions.

**Comment by anilchaurasiya** [comment]
@npetzall I unable resolve this issue please help me with solution , how to get comments added in the comment section while creating documentation using schemaspy.

**Comment by anilchaurasiya** [comment]
@npetzall  I am using PostgreSQL v11.8.

**Comment by npetzall** [comment]
@anilchaurasiya create a new issue, this is 5 years old and it's oracle and not postgresql.
