### ISSUE TITLE
Using "user" as the value of another flag is being recognized as the user flag

### ISSUE THREAD

**Issue by MetalArend** [schemaspy/schemaspy#952]
## Steps to Reproduce (for bugs)
Run `docker run --rm -it schemaspy/schemaspy:6.1.0 -u "user" -p "user"`

## Expected Behavior
The password "user" should be read as the password, not as a user flag.

## Current Behavior
The "user" after the `-p` flag is being wrongly interpreted as a second `-u` flag, and the command errors out about the user flag being provided twice.

**Comment by npetzall** [comment]
Multiple JCommand parameters have single word names. They should be removed, since this is probably the cause.
