### ISSUE TITLE
Updated release of schemaspy in Docker hub

### ISSUE THREAD

**Issue by willb611** [schemaspy/schemaspy#959]
## Expected Behavior

Releases are kept up to date in Docker hub in branches other than "snapshot". 

## Current Behavior

 The current "latest" is from 3 years ago https://hub.docker.com/layers/schemaspy/schemaspy/latest/images/sha256-9c341f547038fea9735083ba5c620f45b62a7d2dec55b5da43814840d1107edf?context=explore
There is no tagged version either which is up to date, the latest was version 6.1.0 from 3 years ago.

## Possible Solution

Update "latest" to latest stable version, add back versioning like 6.2.0, or 7.0.0, etc. https://hub.docker.com/r/schemaspy/schemaspy/tags 😄 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Database type (e.g. MySQL):
* Database driver version (is you use a special one):
* Your DDL (sample how to reproduce the issue):
* Full command including arguments how you run SchemaSpy:
At the moment to use up to date versions of Schemaspy (and drivers which are needed for newer database versions), you have to use "snapshot" version.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10):
* Java version:

**Comment by npetzall** [comment]
Latest stable release 6.1.0, latest docker tag points to tag 6.1.0.

So releases are in sync.

You might be looking for #837

**Comment by willb611** [comment]
Ah yeah, you're right! thanks 😄
