### ISSUE TITLE
Full support for H2 2.x

### ISSUE THREAD

**Issue by marcelstoer** [schemaspy/schemaspy#960]
I expected this to be a duplicate but to my surprise it appears that I'm indeed the first to report this.

## Expected Behavior
SchemaSpy 6.1 and master to create a schema from an H2 2.x database.

## Current Behavior
SchemaSpy thinks the schema be empty.

```
INFO  - Gathering schema details
Gathering schema details...WARN  - Failed to retrieve sequences using sql 'SELECT seqs.sequence_name, (seqs.current_value + seqs.increment) as start_value, seqs.increment FROM information_schema.sequences seqs WHERE seqs.sequence_schema = :schema'
Column "SEQS.CURRENT_VALUE" not found; SQL statement:
SELECT seqs.sequence_name, (seqs.current_value + seqs.increment) as start_value, seqs.increment FROM information_schema.sequences seqs WHERE seqs.sequence_schema = ? [42122-214]
(0sec)
Connecting relationships...WARN  - No tables or views were found in schema 'PUBLIC'.
ERROR - The schema exists in the database, but the user you specified 'sa'might not have rights to read its contents.
ERROR - Another possibility is that the regular expression that you specified for what to include (via -i) didn't match any tables.
WARN  - Empty schema
null
INFO  - StackTraces have been omitted, use `-debug` when executing SchemaSpy to see them
```

## Possible Solution
Dunno

## Steps to Reproduce (for bugs)
1. Populate a file-based H2 database.
   - `java -cp h2-*.jar org.h2.tools.Shell`
   -  when asked for URL enter e.g. `jdbc:h2:~/h2-test`
   - exit
   - start console and connect to database, `./h2.sh`
   - populate schema by creating objects e.g. 
```sql
   CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);
```
2. Run SchemaSpy against it.

## Context
* Database type (e.g. MySQL): H2
* Database driver version (is you use a special one): 2.1.214
* Your DDL (sample how to reproduce the issue): any
* Full command including arguments how you run SchemaSpy:
```
-t
h2
-u
sa
-dp
/Users/marcelstoer/.m2/repository/com/h2database/h2/2.1.214/h2-2.1.214.jar
-db
/my-file-based-h2-database
-o
/some-output-path
```

## Your Environment
* Version used: 6.1 and master
* Environment name and version (e.g. Chrome 39):
* Operating System and version (e.g. Windows 10): macOS
* Java version: 11

## Analysis
- H2 2 changed the `INFORMATION_SCHEMA` which causes the "Failed to retrieve sequences" error: http://h2database.com/html/migration-to-v2.html#information_schema
- The reason SchemaSpy thinks my H2 2 schema be empty ("No tables or views were found") appears to be because the `BasicTableMeta#type` in H2 2 is `BASE TABLE` rather than `TABLE`: https://www.h2database.com/html/systemtables.html#information_schema_tables

  | H2 1.x      | H2 2.x |
  | ----------- | ----------- |
  | <img width="670" alt="Screen Shot 2022-09-20 at 17 33 27" src="https://user-images.githubusercontent.com/624195/191302765-f7c87ae6-354e-4aed-9316-66d704bbae63.png">      | <img width="658" alt="Screen Shot 2022-09-20 at 17 36 40" src="https://user-images.githubusercontent.com/624195/191302646-3d0b8502-33bc-4a07-8fb8-874d27bd64d3.png">       |

- A `databaseType` like this `h2-2.properties` will address the issues (not sure if there are others). I verified that `selectSchemasSql` and `selectViewSql` are still correct:
  ```properties
  extends=h2

  selectSequencesSql=SELECT seqs.sequence_name, (seqs.base_value + seqs.increment) as start_value, seqs.increment FROM information_schema.sequences seqs WHERE seqs.sequence_schema = :schema
  tableTypes=BASE TABLE
  ```

**Comment by npetzall** [comment]
@marcelstoer If you want the credits, create a pull request with the above h2-2.properties and I'll merge it.
