### ISSUE TITLE
 Failed to generate Table diagram -- RelationShipDiagramError (SchemaSpy - GraphViz)

### ISSUE THREAD

**Issue by itsubaidshahid** [schemaspy/schemaspy#980]
Trying to create the DB schema ER Diagram using the below command but unable to generate the ER diagrams sue to some issue with graphViz configurations. schemaSpy is creating the html based file of all the tables and .dot files also being created successfully in specified output directory. But those then .dot files are not being converted into ER diagrams to be added in .html to display.

**Versions :**

1. Java : v8
2. schemaSpy : v6.0.1
3. graphViz : dot - graphviz version 7.0.2 (20221119.0110)
4. mysql : mysql-connector-java-8.0.30.jar

**Command :**

**java -jar .\schemaspy-6.1.0.jar -t mysql -dp C:\mysql-connector-java-8.0.30.jar -db datagenerator_poc -gv 'C:\Progr
am Files (x86)\Graphviz'  -host 127.0.0.1 -port 5000 -s mysql  -u root -p staging123 -o /SchemaSpy**

```
SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.1.0 on DESKTOP-O4DE6AA with PID 10936 (C:\Users\Ascend\Desktop\ATS Codebase\demo\src\main\resources\lib\schemaspy-6.1.0.jar started by Ascend in C:\Users\Ascen
d\Desktop\ATS Codebase\demo\src\main\resources\lib)
INFO  - The following profiles are active: default
INFO  - Started Main in 1.314 seconds (JVM running for 1.814)
INFO  - Starting schema analysis
INFO  - Connected to MySQL - 8.0.31
INFO  - Gathering schema details
Gathering schema details.........................................(34sec)
Connecting relationships.........................................(14sec)
Writing/graphing summary.INFO  - Gathered schema details in 14 seconds
INFO  - Writing/graphing summary
INFO  - Graphviz rendered set to ''
..ERROR - RelationShipDiagramError
Failed to produce diagram for: \SchemaSpy\diagrams\summary\relationships.implied.compact.dot
ERROR - RelationShipDiagramError
Failed to produce diagram for: \SchemaSpy\diagrams\summary\relationships.implied.large.dot
.ERROR - Failed to produce diagram for: \SchemaSpy\diagrams\orphans\help_keyword.1degree.dot
Failed to generate Orphan diagram
ERROR - Failed to produce diagram for: \SchemaSpy\diagrams\orphans\help_relation.1degree.dot
Failed to generate Orphan diagram
ERROR - Failed to produce diagram for: \SchemaSpy\diagrams\orphans\plugin.1degree.dot
Failed to generate Orphan diagram
ERROR - Failed to produce diagram for: \SchemaSpy\diagrams\orphans\replication_group_configuration_version.1degree.dot
Failed to generate Orphan diagram
ERROR - Failed to produce diagram for: \SchemaSpy\diagrams\orphans\time_zone.1degree.dot
Failed to generate Orphan diagram
ERROR - Failed to produce diagram for: \SchemaSpy\diagrams\orphans\time_zone_leap_second.1degree.dot
Failed to generate Orphan diagram
ERROR - Failed to produce diagram for: \SchemaSpy\diagrams\orphans\time_zone_name.1degree.dot
Failed to generate Orphan diagram
.....(1sec)
Writing/diagramming detailsINFO  - Completed summary in 1 seconds
INFO  - Writing/diagramming details
..Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:71)
        at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
        at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:80)
        at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:426)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:260)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:123)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:98)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:87)
        at org.schemaspy.Main.main(Main.java:55)
        ... 8 more
Caused by: org.schemaspy.output.diagram.DiagramException: Dot missing or invalid version
        at org.schemaspy.output.diagram.graphviz.GraphvizDot.generateDiagram(GraphvizDot.java:193)
        at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:68)
        ... 16 more

```

**Comment by npetzall** [comment]
See #963 #944

**Comment by itsubaidshahid** [comment]
@npetzall After following directions to upgrade to v6.1.1, The previous error gone. Now new error is appearing regarding the size of cell is too small to render the content.

**Error shown below :**

```
INFO  - Gathering schema details
Gathering schema details.........................................(49sec)
Connecting relationships.........................................(22sec)
Writing/graphing summary.INFO  - Gathered schema details in 22 seconds
INFO  - Writing/graphing summary
INFO  - Graphviz renderer set to ':cairo'
..ERROR - dot -Tpng:cairo relationships.implied.compact.dot -orelationships.implied.compact.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo relationships.implied.compact.dot -orelationships.implied.compact.png -Tcmapx: in label of node time_zone
ERROR - dot -Tpng:cairo relationships.implied.large.dot -orelationships.implied.large.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo relationships.implied.large.dot -orelationships.implied.large.png -Tcmapx: in label of node time_zone
.ERROR - dot -Tpng:cairo orphans.dot -oorphans.png -Tcmapx: Warning: cell size too small for content
ERROR - dot -Tpng:cairo orphans.dot -oorphans.png -Tcmapx: in label of node db
```

**Comment by npetzall** [comment]
This somewhat misguided, have look at the diagrams. It's logged as error but the messages are warnings, I believe there is an issue regarding that.

**Comment by itsubaidshahid** [comment]
Diagrams are generated, but the issue is as per the logs in schemaSpy job, I am unable to see the tables/view directory to see the relationships between ER diagrams, However separate diagrams are generated in Orphans, Summary and tables folders.

**Comment by itsubaidshahid** [comment]
Okay then we need to show those ERRORS as WARN. to avoid confusions.

Furthermore On which path I can see this kind of relationship Diagram between tables on my local ?
Sample:
https://schemaspy.org/sample/relationships.html

**Comment by npetzall** [comment]
If you have the output, you should have the same relationships.html. You could check the source to be certain, but I think it should be under diagrams/summary.

**Comment by itsubaidshahid** [comment]
I do have multiple tables and with relationships in the DB but the generated html diagram is not showing all the tables its only showing 4 tables, instead I have atleast 20+ tables in DB.

![image](https://user-images.githubusercontent.com/118800088/215981942-134ce7c8-58e9-4698-b9e8-bba83f4ca872.png)

**Comment by npetzall** [comment]
Do they end up in Orphan tables?

**Comment by itsubaidshahid** [comment]
No, lets say we have two tables, one is **USER**, 2nd one is **USER_ROLES**. **USER** table holds the one-to-many relationship with **USER_ROLES**, but its not being generated in the output file as shown in the above diagram.

let me share the **CMD** which is being used to generate the relationship diagram : 

**CMD :** _java -jar .\schemaspy-6.1.1-SNAPSHOT.jar -vizjs -t mysql -dp .\mysql-connector-java-8.0.30.jar -db datagenerator -host 127.0.0.1 -port 5000 -s mysql  -u <user> -p <password> -o C:\Users\Ascend\Desktop\ubaid-schemaspy-test\_

**Comment by npetzall** [comment]
The strange thing is that the example you mentioned is same type of relationship that is shown in the diagram.

Just to help track down the issue. 
If its a diagram rendering issues or a information retrieval issue.

The tables that you are missing in the diagram are also missing from the tables page?

If possible for a missing table could you extract the create statement?

From the previous log statements it seems that SchemaSpy doesn't see any other tables. This might be access restrictions different accounts have different access or that the tables have a different type than table.

A small SQL script to recreate the issue would be a great help.

**Comment by itsubaidshahid** [comment]
So two points to validate your concern, 

1. It does not seems the information retrieval or some kind of access issue, Because I am using the same user on mysql-workbench and able to made changes easily in all tables with that user.

2. schemaSpy is creating the other tables as well and total 38 tables its importing from mysql DB see below image. But still in all those tables USER_ROLES and few others seems to be missing. (Should I try with the admin user who have all the access for the DB ?)

![image](https://user-images.githubusercontent.com/118800088/216345437-9792c8eb-b702-4bed-93a9-ae7f74bd3fe3.png)

**Comment by itsubaidshahid** [comment]
Just verified that I am using the master/admin user which has not access restrictions.

**Comment by npetzall** [comment]
Admin shouldn't be required. We have test for basic cases. And it should show views, unsure if views are included in diagrams. But I'll have to test also what happens if a table is partitioned.

But still Strang as the diagrams you get are only implied as if fk information can't be retrieved.

**Comment by itsubaidshahid** [comment]
Along with fk information its also not getting all the tables as well, Can you verify the command above which is being used to generate the output.

**Comment by npetzall** [comment]
I see no direct issues with the command. But I have some bad history with the MySQL driver.

They changed stuff before so I need to test with that version to be sure that it should work. Which version of the MySQL are you using. So that I can check the combination.

**Comment by itsubaidshahid** [comment]
Yes please, Using this Jar : **mysql-connector-java-8.0.30.jar**

**Comment by npetzall** [comment]
Is the server 8.0.31?

**Comment by itsubaidshahid** [comment]
Server Information :
![image](https://user-images.githubusercontent.com/118800088/216354289-d9b82be2-bbb4-42d1-9874-1b003e240915.png)

**Comment by npetzall** [comment]
It's tables + views 38 so with 24 tables, there should be 14 views.

But there might be missing tables.

**Comment by npetzall** [comment]
One important thing is that MyISAM doesn't support fk so there won't be any relationship unless implied based on name+type

**Comment by itsubaidshahid** [comment]
> It's tables + views 38 so with 24 tables, there should be 14 views.
> 
> But there might be missing tables.

Yes, lots of tables are missing almost 15-20 tables.

**Comment by itsubaidshahid** [comment]
> One important thing is that MyISAM doesn't support fk so there won't be any relationship unless implied based on name+type

Yes I noticed, So also shared the SS here, In case of MyISAM we can ignore those tables, But what about the other tables which have InnoDB.

Did you try to replicate with above mentioned versions ?

**Comment by npetzall** [comment]
I'm so freaking sorry I'm gonna blame it on recovering from the flu. Brain isn't working 100% yet.

CMD for MySQL `-db` and `-s` should have the same value, update `-s` to `datagenerator`

**Comment by npetzall** [comment]
With the `-s mysql` it will return mysql internal tables and views. For managing dbms, instead of application tables/views.

**Comment by itsubaidshahid** [comment]
It worked mate, thanks for the quick pick on that,
Will it not be showing the tables which does not have relationships, I mean single entity tables ?

Requirement is to get all the tables with relationships and without relationships on the same page. To show in UI for the user to understand DB schema in better way.

**Comment by npetzall** [comment]
It won't show orphan tables in relationship diagrams, but you'll have each orphan table as a diagram in output/diagrams/orphans. So you can include them. But if you include the whole html report that can be navigated. 

I don't have a super memory but if a diagram/picture of all tables is what you want regardless of relationships I think it's a feature request, if it doesn't already exist as a feature request.

**Comment by itsubaidshahid** [comment]
Much appreciated and thanks for your support.
