### ISSUE TITLE
SS 6.1.0 can't find dot

### ISSUE THREAD

**Issue by arnieHouston** [schemaspy/schemaspy#988]
## Expected Behavior
The generation should complete.

## Current Behavior
The debug information is insufficient. Doesn't show what values are in place for each parameter.
In regards to the graphical rendering portion, just say's it can't find dot.

The resultant site has a complete index.html but no table files.

## Possible Solution
No clue.
We really need a switch to SKIP graphical generation altogether. Its a nice to have but hardly necessary.

## Steps to Reproduce (for bugs)
My cmd file:

@echo off
C:\dev\Java\jdk-19.0.1\bin\java -client -Xms4g -Xmx4g -jar schemaspy-6.1.0.jar ^
-debug ^
-gf "c:\dev\graphviz\7.1.0" -lq -renderer :cairo ^
-dp ./ ^
-i "TABLE_NAME" ^
-t db-file ^
-db dbname -norows -cat user_catalog -s sname ^
-u xyz -pfp -o "c:\dev\doc\dbname"

If I use -visjz instead, I get a NPE because this.scriptEngine is null.

## Context
Trying to document a single table. When it gets to the graphical rendering part, it cannot find dot, even though it is on the path (ends in \bin part) and responds at the command line before running the cmd script above. Just says "Dot missing or invalid version". Doesn't show the command (dot -V) it is executing with the path. Above, I've tried ending the gf parameter with and without \bin to no avail.

It is generating two of the .out files and if I run "dot file-name.dot > file.txt" it is generated.

## Your Environment
Windows 10/64 | OpenJDK 19.0.1 | GraphViz 6.0.1 or 7.1.0 | Oracle 19
Tried running SS 6.0.0 and it fails simply by saying "application startup failed" without echoing anything.

**Comment by npetzall** [comment]
See #963

**Comment by npetzall** [comment]
NPE for script enginge is because alla scriptengines were removed from jdk around 15, it works on Java 11 else you need to add a scriptengine.

**Comment by arnieHouston** [comment]
Ah. Downloaded shapshot and it worked. THANK YOU! (And I noticed I had gf above instead of gv.)

What about having a swtich to disable the rendering altogether if it isn't needed or desired? Maybe -gd (graphics disabled).

Also, re the JDK 19/JS issue. Will there be instructions for more current JDKs?

**Comment by marcelstoer** [comment]
Should be closed as 6.2.0 is out now.

**Comment by npetzall** [comment]
Version constraint for GraphViz removed and nashorn has been added as JavaScript engine in version 6.2.0

**Comment by npetzall** [comment]
@arnieHouston 
> What about having a swtich to disable the rendering altogether if it isn't needed or desired? Maybe -gd (graphics disabled).

Could you create a new issue explaining the exact outcome.

Ther is the option `-nohtml` which only produces the xml "report". But would this be with html generated, and dot-files but no rendered png/SVG?
